### ISSUE TITLE
media playback

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#210]
Is it possible to jumpt to anywhere in the media file? At the moment it only allows you to play from the beginning. Also, is it possible to pop the media player out so you can continue browsing the catalog while playing a media file? Even just to go back and look at the metadata for the item you are listening to?

**Comment by nthieberger** [comment]
Let's rebadge this as (1) transcoding all existing eligible files to HTML5 formats, (2) building a process wherein all newly ingested items are transcoded (3) building a viewer that allows delivery of these files

**Comment by stasb** [comment]
Hi Nick, 

To clarify the current requirements for this issue:

1. Process all existing eligible files in the database and convert to HTML5 formats.
2. Change the existing transcoding process so that any newly uploaded files are in an HTML5 format.
3. Build the player that allows skipping to anywhere in the file, and the ability to pop out and keep playing.

Does this sound correct?

Thanks

**Comment by nthieberger** [comment]
Yes it does. And I am working to get a routine that provides visual representation of the audio files aper the attached. So a slider could be put under this image to allow users to identify where in the file they want to listen to.
![td1-0376-0376a](https://cloud.githubusercontent.com/assets/611488/7364614/dd12889c-edcb-11e4-9885-20e48b807f0a.jpg)

**Comment by silviapfeiffer** [comment]
You can do this now on the web using the web audio api.

Best Regards,
Silvia.

**Comment by nthieberger** [comment]
See also #347

**Comment by nthieberger** [comment]
This is another part of the media playback setup. Fraunhofer have provided us with an algorithm to generate images from audio files which indicate what the contents are and will be a useful navigation tool for us and for users. The latest version is here:
ftp://paradisec@ftp.iais.fraunhofer.de
using the password
N01se$pec77

We have tested it here and tweaked it so I hope it all works ok. It will need to be run over the whole collection and then added as a part of the ingest function. See my email message to Terem of June 4th, but please use the more recent version that you can download from the ftp site.

**Comment by nthieberger** [comment]
Please implement this to work its way through the existing collection (creating 'spectrum' files) and to run on accession of any new item.

**Comment by nthieberger** [comment]
Media needs to play from anywhere, not just from the beginning, this is critical. Please implement this functionality.

**Comment by agrimmtt** [comment]
@nthieberger seeking should be working now. Please let me know if there's any problems with it.

**Comment by AmandaPDSC** [comment]
I think this can be closed now - @nthieberger ?
