### ISSUE TITLE
Batch operations

### ISSUE THREAD

**Issue by jangari** [nabu-catalog/nabu#266]
Nick FG has asked whether Nabu can do batch operations to files, so we did a bit of testing. It seems that while any field can be updated as a batch operation, the selection of the batch relies only on the advanced search function, and files cannot be added or removed from it. So for instance, Nick needs to add a single piece of metadata to 50 items in a collection of 300. Searching for those items will return all 300, but cannot be whittled down any further as far as we can see.

Is there a way we can beef up the advanced search functionality to allow us to refine results? Perhaps a 'search within these results' or something? And the ability to remove a single search result from the set would also be useful.

**Comment by AmandaPDSC** [comment]
Though #106 is now closed, there are some issues relating to search sets that have not yet been addressed. It's good to be able to return to the search results, but we need to be able to refine search sets in nuanced ways. E.g. exclude some items from a found set, or add two search sets together. The bulk update function is less meaningful if we have limited control over the search set.
