### ISSUE TITLE
essence files uploading but not listed in catalogue

### ISSUE THREAD

**Issue by jangari** [nabu-catalog/nabu#295]
I've noticed there are some files that have been harvested from Azoulay by the Nabu server and stored in the archive, but have not been included in the catalogue as yet.

In particular, see RN1:
http://catalog.paradisec.org.au/collections/RN1/items/005004

The item page say there are no essence files, yet four exist in the archive (not including the hidden xml file):
```
aidan@catalog:/srv/catalog/RN1/005004$ ls -l
total 993600
-rwxrw-rw- 1 deploy deploy  18167936 Dec  4 15:27 RN1-005004-A.mp3
-rw-rw-rw- 1 deploy deploy 666845638 Dec  4 15:24 RN1-005004-A.wav
-rwxrw-rw- 1 deploy deploy   8200320 Dec  4 15:29 RN1-005004-B.mp3
-rw-rw-rw- 1 deploy deploy 324127204 Dec  4 15:31 RN1-005004-B.wav
-rw-rw-r-- 1 deploy deploy      2207 Oct 31 13:54 RN1-005004-CAT-PDSC_ADMIN.xml
```
This appears to be the case for all of collection RN1 since around the beginning of November (judging by the record modified date of the last item to have essence files listed).

**Comment by stasb** [comment]
Hi, has this issue currently been resolved?

**Comment by AmandaPDSC** [comment]
I think it's resolved - @nthieberger ?
