### ISSUE TITLE
Allow multiple collectors

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#306]
I can't see where the 'cite as' field is in an item or collection entry in NABU? I'm sure it used to be there (as in #141)

The following is an OLAC citation form (from the OAI feed) and it is strange for several reasons (that could be to do with how OLAC do things ?) 
- it has no title
- it has no URI, not any reference to the PID
- It lists Corin Bone as a 'depositor' but he is an 'operator'

Nick Thieberger (compiler); Corin Bone (depositor); Nick Thieberger (depositor); Nick Thieberger (recorder); Kalsarap Namaf (speaker); Iokopeth (speaker); Limas (speaker); Linuk (speaker). 1998. Pacific And Regional Archive for Digital Sources in Endangered Cultures (PARADISEC).

**Comment by nthieberger** [comment]
we need to approach OLAC and ask for > collector to be allowed

**Comment by JonoGillett** [comment]
Potentially the OLAC feed details in this ticket are out of date - it's worth re-investigating both roles and multiple collectors.
