### ISSUE TITLE
Unwrappable lines cause map box to expand

### ISSUE THREAD

**Issue by jangari** [nabu-catalog/nabu#339]
I was looking through some collections and came across this one:
http://catalog.paradisec.org.au/collections/JL1
In which a url in the item description caused the line to not be able to wrap. This seems to have had an effect on the map box as it now occupies a larger portion of the screen. Also, inspecting the element in my browser and removing (just from the page source) the url, the map returned to normal size.

Issue is likely with the way the columns are dynamically resized with respect to each other.

**Comment by nthieberger** [comment]
Quick fix is to put spaces into the url to stop it being too long

**Comment by enwardy** [comment]
fixed this by updating the link
