### ISSUE TITLE
Introduce transcoding system for essence files

### ISSUE THREAD

**Issue by silviapfeiffer** [nabu-catalog/nabu#347]
I would really like to have a transcoding system that stores all media in ogg format or mp4 for delivery, with names that can be predicted by NABU for use in eventual online annotation/transcription of media. A user should be able to transcribe media online for submission to an editorial process (this is not part of the current request unless you think it can be done relatively easily. I have seen this by a local group http://lp20.org/transcriber/test/web/transcriber.html select file>open remote index file) that could put on top of a media file)

**Comment by nthieberger** [comment]
And what about this for playback? video.js http://www.videojs.com/

**Comment by baristuncay** [comment]
We need to investigate:
1. What formats to transcode to
2. Need to have different versions for mobile and desktop
3. Where to store the files and file naming

**Comment by nthieberger** [comment]
for video, we need 2 video formats to cover all
browsers: webm & mp4 (h.264, aac).

**Comment by JonoGillett** [comment]
@nthieberger Regarding point 3 - Do you want these to be admin style files which are accessible for the viewer, or should they be created as essences?

**Comment by nthieberger** [comment]
The difference being, should they be visible to users or only to the viewer app? I think they can be visible to users. We currently expose mp3 files anyway and would only be adding a webm and mp4 to any video that doesn't have it already.

**Comment by agrimmtt** [comment]
While looking at existing essence objects, I noticed that there's roughly equal number of objects with mimetypes of 'audio/x-wav' and 'audio/mpeg'. It seems like every audio item has one of each.

How is this being done? If possible, I'd like to examine extending that system to handle conversion of audio into audio/ogg and video into the desired formats.

**Comment by nthieberger** [comment]
We generate mp3 as part of the ingestion process. We will also be
generating webm for future video ingestion (done by an external service,
DAMSmart), but do need that conversion to be applied to existing video
content. It seems that HTML5 only requires mp3 files for audio so we don't
need ogg as a format anymore.

**Comment by AmandaPDSC** [comment]
@nthieberger this seems like it's resolved - or do we still need to retrospectively create mp4s? And should we just get DAMSmart to do this?
