### ISSUE TITLE
Add a captcha to sign up

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#360]
While we are safe enough with sign up avoiding bots by requiring email confirmation, there are still entries stored that are unconfirmed (http://catalog.paradisec.org.au/admin/users/2352) and take up space. Do they get deleted after a set time period if they remain unconfirmed? Could we add a captcha to make it one step harder for vexatious users?

**Comment by enwardy** [comment]
Nick T: "no need for Captcha"
