### ISSUE TITLE
Looks like the comment list is always empty

### ISSUE THREAD

**Issue by silviapfeiffer** [nabu-catalog/nabu#364]
http://catalog.paradisec.org.au/admin/comments

**Comment by nthieberger** [comment]
Yes, a comment was received this morning by email, but it does not appear on the comments page. I am not sure that it is worth any effort right now as the email function works and we can deal with the issue immediately.

**Comment by silviapfeiffer** [comment]
I think comments don't just appear but have to be authorised by an admin. Might want to check if that comment was authorised.
