### ISSUE TITLE
duplicate an item

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#373]
It would be useful to be able to duplicate an item and allow the user to assign a new name: in cases where the name was wrongly given initially, or where items are sufficiently similar that it would save effort to duplicate and edit rather than create new. Perhaps a button that allows an item's entire contents to be duplicated?

**Comment by nthieberger** [comment]
Error generated when an item was created and saved

**Comment by jangari** [comment]
Still not working. Duplicate button goes to a 'new item' page, but clicking 'add' goes to a 404, and navigating back to the item list doesn't show new item.

**Comment by JonoGillett** [comment]
Staging now has some changes that should resolve this issue. Please test it and let me know if there are any further problems.

**Comment by nthieberger** [comment]
I just tried it and it worked ok
