### ISSUE TITLE
private collection rights

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#374]
We should be able to assign editing rights to a user to work with a private collection. At present a private collection cannot be seen, even if a user is assigned rights to edit it.

**Comment by AmandaPDSC** [comment]
Also private items don't seem to be findable in an advanced search - they should be (by someone with admin access or edit access to that collection)

**Comment by AmandaPDSC** [comment]
We just tried an advanced search on a private collection (CLC) and it failed to produce any results

**Comment by agrimmtt** [comment]
As per the meeting, we haven't been able to reproduce this.

**Comment by AmandaPDSC** [comment]
It seems this issue is not resolved after all. We assigned edit and download to a number of private items in the CLC collection, but they still don't show up in a search for "CLC" for the two users assigned access. If we give users the URLs for these items, they can see them and download them. But they should show up in a search

**Comment by agrimmtt** [comment]
@AmandaPDSC I've made some changes. Can you see if it works for you?

**Comment by AmandaPDSC** [comment]
yes, seems to be working now

**Comment by agrimmtt** [comment]
Oops - I fixed it for "Edit Access", but not for "View/Download access". Please indicate what Urgent level tag it should have.

**Comment by AmandaPDSC** [comment]
i was able to download the files using my test user account...

**Comment by agrimmtt** [comment]
After the most recent change, users who only have read/download rights (as opposed to edit rights) can now do an item search for those items.

Also, users who have edit rights or read/download rights to items within a collection can now search for that collection on the collection tab.
