### ISSUE TITLE
adding more fields to search function

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#376]
We should be able to search on any field to allow us (in Advanced search) to locate all audio files or video files, etc

**Comment by agrimmtt** [comment]
Can you provide an example of this?

**Comment by nthieberger** [comment]
Hi Andrew. This item is not listed as urgent so please do not go ahead with it now. I think we agreed we would provide a hierarchy of items for you to work on, so please work on those items listed as urgent.
