### ISSUE TITLE
implement checksum checking

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#378]
We store checksums in a separate directory, but we need to keep them with the items and to implement a way of checking them through ingest and then for any delivery

**Comment by nthieberger** [comment]
Related to this and to #412 : attach a checksum to all files that currently do not have one (e.g. JW1 has only some files with checksums.) Please find all items that have no checksums and generate them)

**Comment by enwardy** [comment]
has grown into issues #653 and #654
