### ISSUE TITLE
DOI minting

### ISSUE THREAD

**Issue by jangari** [nabu-catalog/nabu#379]
Raising this as an issue since Intersect will likely be going ahead with this and we need to have a discussion about how it will affect the workflow. 

1. Everything currently in the catalogue will need a DOI, so how to do this?
2. How and when will we actually mint them, i.e., at what point in the pipeline.
3. The DOI should become part of the BWF header. So:
   * Stuff already archived will have to be unsealed and resealed
   * Audio will have to be handled differently from non-audio
4. What happens when an audio file needs to be resealed? Presumably it will retain the same DOI.

**Comment by stasb** [comment]
Hi,

Would you be able to explain in further detail what is meant by 'DOI', 'BWF', and 'minting'?

**Comment by nthieberger** [comment]
We are ready to move this along now. DOI is a digital object identifier. We will export XML that minimally contains five metadata elements: title, year, author, publisher, identifier (and url), but also can contain additional elements (university, maybe funding source) and these are sent to a validation service and then stored by the DOI authority who send us a DOI that we need to ingest into our catalog. This is fine for collection and item-level, but we may need to develop an XML form of export for files. Now that the OAI-PMH feed includes resolvable file urls we can include them in this DOI process, but they will need to inherit some metadata from the item-level.

Here are some references
 
Understanding Data Citation and DOIs  
A general overview of data citation and DOIs 
http://ands.org.au/cite-data/index.html 

Implementation Guidelines for institutions and data managers
http://www.ands.org.au/cite-data/institutions.html

Implementation Guidelines for researchers and custodians
http://ands.org.au/cite-data/researchers.html

An overview by Griffith University of some of the issues that you will need to consider and then manage when you implement DOIs
http://ands.org.au/cite-data/griffith_doi_guidelines-4.pdf

The ANDS Policy statement on the use of the CMD Service
http://www.ands.org.au/services/cmd-policy.html

FAQ - http://ands.org.au/cite-data/doi-q-and-a.html

Videos of past ANDS events in which you'll find several on DOIs
http://ands.org.au/presentations/audio-video.html

Preparation for Technical Minting of DOIs
A description of the CiteMyData service
http://ands.org.au/services/cite-my-data.html

CiteMyData Technical documentation
http://ands.org.au/services/cmd-technical-document.pdf

**Comment by nthieberger** [comment]
Aidan will liaise with Alan Glixman and Terem to move this along

**Comment by JonoGillett** [comment]
At the moment I'm just aiming for the minimal metadata required to mint a DOI, coming from all levels of the catalog - collections, items and essences.

Regarding the DOI metadata, the documentation describes fairly broad options for the different fields - particularly publisher and publicationYear. For example it suggests that the publisher could be Paradisec itself, or the individual who produced the dataset.

For the purposes of DOIs I imagine we'd want it to be as fine-grained as possible, e.g. at the individual level where possible. In that case which type of user role would count as the publisher? Collector maybe, or something else?
Similarly for the creator field - I imagine that should be the collector?
And for the publication year, that is described as "the first time the dataset was publicly available" - would that just be the time the collection/item/essence was created in the system?

**Comment by jangari** [comment]
I would suggest that the publisher is always PARADISEC while the creator is the collector. Publication year, I'm assuming refers to the publication of the resource rather than the publication of the DOI, right? But then again, DOIs are identifiers for objects, not published resources (necessarily). I might seek Alan's assistance on this one.

**Comment by nthieberger** [comment]
(1) Does a doi entered into a browser resolve to the correct place in NABU?
(2) Where is the collection-level doi displayed?

**Comment by agrimmtt** [comment]
@nthieberger 
(1) Typing http://dx.doi.org/10.5072/12/56927330A60BB into the address bar of a web browser takes you to http://catalog.paradisec.org.au/collections/AA1/items/001
(2) Currently, there's no DOI displayed because collections doesn't have a "Cite As" table row. How should we display DOIs in collections?

**Comment by nthieberger** [comment]
Can we add a 'Cite as' field to the collection that includes the collector name, date, title (collection id in brackets) and url/doi?

**Comment by agrimmtt** [comment]
Collection already had citation information (sorry for not noting this previously), in the following format:

Collector name (collector), date, title (without collection id), Digital collection managed by PARADISEC. url today's date

Although not shown on the page, it was used in XML information about the collection.

I've changed it to

Collector name (collector), date, title (with collection id in brackets), Digital collection managed by PARADISEC. url/doi, no mention of today's date.

For an example, see http://144.6.225.96/collections/AA1 for one using a DOI, and http://144.6.225.96/collections/YT1 for one using a URL.

@nthieberger , are you happy with the version produced? Shall I get rid of "(collector)" or "Digital collection managed by PARADISEC", or undo any of the changes I've made?

**Comment by agrimmtt** [comment]
Hi @nthieberger , I forgot to follow up on this ticket in my most recent email.

Can you let me know if you're happy with the following? As I've noted before, the citation I'm proposing below is different from what used to be used.

You can't currently see the new citation format on the production or staging server. Let me know if you want to see it on the staging server.

![screen shot 2016-04-05 at 9 30 48 am](https://cloud.githubusercontent.com/assets/13618655/14267181/3f44192e-fb11-11e5-943d-c5fb4cc432cf.png)
![screen shot 2016-04-05 at 9 31 16 am](https://cloud.githubusercontent.com/assets/13618655/14267180/3f43adc2-fb11-11e5-8c35-5e0b5636a329.png)

**Comment by nthieberger** [comment]
This looks fine, thanks.

**Comment by agrimmtt** [comment]
@nthieberger Done. You can see an example of `[Open Access]`, `[Closed Access]` and `[Other Access]` at http://144.6.225.96/collections/AA1 , http://144.6.225.96/collections/AB1 , and http://144.6.225.96/collections/JHER respectively. It'll be made available on the next deploy.

**Comment by agrimmtt** [comment]
The change to the "Cite as" has been successfully deployed to production. In addition, every collection, item, and essence has now had a DOI minted.
