### ISSUE TITLE
Users with identical names need to be able to be differentiated

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#380]
If there are 2 or more users with an identical name, there is no way of seeing from a drop down list which of those users is a contact only and which is linked to an email account. This becomes an issue when assigning edit rights. Perhaps the user number could be displayed next to the user name, so that an admin could go into the list of users, check the user number of the person to whom they want to assign rights and then select that number from the drop down list?

**Comment by stasb** [comment]
Hi, has this issue now been resolved?

**Comment by AmandaPDSC** [comment]
Yes, resolved

Sent from my iPad

On 28 Apr 2015, at 1:22 pm, "Stas Belkov" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, has this issue now been resolved?
