### ISSUE TITLE
CSV export does not handle chinese characters

### ISSUE THREAD

**Issue by jangari** [nabu-catalog/nabu#382]
Exporting a collection or items as CSV doesn't display chinese characters. They get garbled. Possibly an encoding issue.

**Comment by nthieberger** [comment]
Exports in all formats (CSV, XML) must be unicode compliant

**Comment by agrimmtt** [comment]
http://catalog.paradisec.org.au/items/search?utf8=%E2%9C%93&search=CI1 and http://catalog.paradisec.org.au/collections/search?utf8=%E2%9C%93&search=CI1 both looked fine when I looked at CSV.

If it's still an issue, can you please provide an example of it going wrong?

**Comment by nthieberger** [comment]
Yes, they look ok to me too thanks
