### ISSUE TITLE
Rules for access conditions of whole collections

### ISSUE THREAD

**Issue by jangari** [nabu-catalog/nabu#386]
There is a discrepancy between the access conditions for collections and for individual items. For example, an 'open' collection might contain an item or more that are 'closed'. This becomes a problem for allowing third parties access to collections which are open, as they would infer from that, that the whole collection is open. 

As such, we think the following automated access condition rules should be put in place:
- if collection access is set to X, then all items are set to X (and user warned).
- if individual item is set to Y when collection is X, the collection access condition is set to 'Mixed'
- if collection is 'Mixed' and all items except one is X, and the last one gets set to X as well, then collection changes to X

For example, a collection is set to 'open', and the user is warned that this will set all items to 'open'. Then the user changes one item to 'closed', the collection is changed automatically to 'mixed (see individual items for access conditions)'. If they then change that item back to 'open' the collection level access is reverted to 'open'.

**Comment by nthieberger** [comment]
I think we can close this as the conditions are visibly indicated in the list at the item level.
