### ISSUE TITLE
Spreadsheet import does not use ISO639-3 codes

### ISSUE THREAD

**Issue by jangari** [nabu-catalog/nabu#390]
The spreadsheet metadata upload function has columns for subject language and content language, and the spreadsheet instructions say to use ISO639-3 (ethnologue) codes. However, codes do no upload whereas language names do.

This should be fixed so that the user must insert languages as ethnologue codes (for the forced consistency) rather than by name, which may vary and may not be correctly associated with a language in the database table.

**Comment by agrimmtt** [comment]
It's now possible to use language codes on the staging server http://144.6.225.96/ . This will be fixed on the production server with the next deploy.
