### ISSUE TITLE
User emails need to allow duplicates

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#391]
When setting up a new user the system should allow an email address to be duplicated across different users, for example, in the case of an existing user who sets u a collection for a deceased researcher and who will be the main contact for that collection. It currently stops the creation of a new user if the email address is already in the system.

**Comment by silviapfeiffer** [comment]
That will be difficult because we use the email address for users to log in.

**Comment by enwardy** [comment]
perhaps this is unresolvable, and a user who wants to have user accounts under two separate names will need to just use an alternative email address? @nthieberger

**Comment by nthieberger** [comment]
yes, we can leave this one
