### ISSUE TITLE
Users able to assign rights in their own items/collections

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#394]
A redesign of our current access rights. This would involve users being able to determine rights in their own materials, and also to assign individual access rights to other existing users. This will minimise the work we, as admins, have to do.

**Comment by JonoGillett** [comment]
As far as I can see this task has already been done. Any user with the ability to manage an item/collection can allow other users to access that record. There are different permissions for read and manage available, so you can specify the level of access too. (Although that being said, you can only choose either read/download OR full admin e.g. they can also change the permissions)

Is there more to it than just this, or could this task be considered complete?

This screenshot is taken as a regular logged-in user with no admin privileges but who has been given Edit permissions on the given item. It is on the item edit page.
![image](https://cloud.githubusercontent.com/assets/10914573/6588328/07bad8b4-c7e4-11e4-8767-8dba5c22c8db.png)

**Comment by nthieberger** [comment]
OK, thanks. Yes, you are right, this functionality does work.
