### ISSUE TITLE
mp3 id3 tags - fix language codes

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#395]
ID3 tags need to have the subject language in the TLAN field

**Comment by jangari** [comment]
They currently have the 'language as given' field. They should have the same content as the import xml file, which looks like "Kagate" syw.

**Comment by agrimmtt** [comment]
I've changed http://144.6.225.96/collections/AA1/items/001.xml?xml_type=id3 from having

    <TLAN>Salako, Badamea</TLAN>

to having

    <TLAN>"Kendayan" knx</TLAN>

@nthieberger @jangari is this what you wanted?

**Comment by nthieberger** [comment]
yes, thanks.
