### ISSUE TITLE
Various delivery options for NABU

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#398]
Can we discuss what is involved in making a version of NABU for mobile devices? Especially once #210 and #397 are resolved it will be good to allow annotation of items in the collection from mobile devices.

**Comment by enwardy** [comment]
seems to me like this could be a reasonably high priority, given increasing usage of mobile devices, @nthieberger @LindaBarwick  ?

**Comment by nthieberger** [comment]
Actually the current NABU is responsive and works ok on small devices so we can close this?
