### ISSUE TITLE
advanced search should be available to all users

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#401]
non-admin users currently can't access advance search - this function should be available to all registered users.
See #365

**Comment by LindaBarwick** [comment]
The issue may be that the advance user function is tied to bulk editing of results. Bulk edit should be available only to admin users  (i.e. not to others who may have edit access to a particular collection - e.g. depositors)

**Comment by stasb** [comment]
Hi, has this issue now been resolved?

**Comment by AmandaPDSC** [comment]
Yes, resolved

Sent from my iPad

On 28 Apr 2015, at 1:16 pm, "Stas Belkov" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, has this issue now been resolved?
