### ISSUE TITLE
Allow multiple funding agencies

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#402]
Currently only one is permitted but we need to allow that work arises from multiple funding sources. This will be a problem for the ANDS feed but that is for them to address.

**Comment by jangari** [comment]
I don't think it will be a problem for the ANDS feed. RIF-CS supports multiple 'related activities' which is where the funding agency/grant goes.

**Comment by JonoGillett** [comment]
Currently a collection has a single grant identifier, and belongs to a single funding body. What is the expected behaviour of grant identifiers when there are multiple funding bodies?

Is a grant identifier a property of the funding body AND the collection (i.e. it is a property of their relationship). And thus should a collection be able to have as many grant identifiers as it has funding bodies?

**Comment by nthieberger** [comment]
Yes, a grant identifier belongs to a funding body and there should be as
many of each as there is of the other. But, it should be possible to have a
funding body without a grant identifier. And there should be the
possibility of having an arbitrary number of grants.

**Comment by jangari** [comment]
Right, so the two fields 'funding body' and 'grant identifier', are paired. Kind of like a person-role relation.
And as Nick points out, the whole two field chunk should be infinitely repeatable. 

This change will require (possibly) modification to the rif-cs feed to repeat the output xml chunk, but I'm not sure how this will play out.

So, if a collection is funded by two different ARC grants (let's say DE123 and LE456), then the user should have to enter both grant identifiers, and for each identifier, select which funding body (both will be the same). The result will be two 'related objects' in the RIF-CS record, one pointing to `http://purl.org/au-research/grants/arc/DE123` and the other pointing to `http://purl.org/au-research/grants/arc/LE456`.

I think a funding body without a grant identifier would be sub-optimal, and I wonder how it would resolve in the RIF-CS, but I suppose if it doesn't point anywhere, then at least the catalogue references that this collection was funded by an unspecified grant from a specific funding body.

**Comment by LindaBarwick** [comment]
We also need to be able to delete mistaken entries (currently not possible) - Nick thinks maybe just adding a zero to the list?
