### ISSUE TITLE
Insert country and language information at the collection level if it is there at an item level

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#404]
Have NABU insert country and language information at the collection level when it is added at the item level. This will ensure that collection-level information correctly reflects the contents of the collection

**Comment by LindaBarwick** [comment]
If there are multiple countries and languages then the collection should include them all.

**Comment by agrimmtt** [comment]
This issue was resolved by the deployment made on Monday 4 January, even though it wasn't mentioned in today's email.
