### ISSUE TITLE
delete directories

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#406]
These directories and their contents need to be deleted from the collection
AT1, ATKK1, EH1, GH1, KCL1, LM1, RF1, DG2, MK1, SAW5

**Comment by LindaBarwick** [comment]
This is a one-off thing. crossreference to #375

**Comment by nthieberger** [comment]
OK, all are deleted except for SAW5 which still needs to be deleted

**Comment by silviapfeiffer** [comment]
done
