### ISSUE TITLE
Extend and fix current test suite

### ISSUE THREAD

**Issue by silviapfeiffer** [nabu-catalog/nabu#408]
I just ran guard and the test suite is a bit broken. Somebody should really fix it and add some more tests.

**Comment by agrimmtt** [comment]
I tried checking out 25da2b33113602fdfa6ff04806d3b301198c3683 , a commit from around that time. It had 5 examples, 2 failures, and 1 pending (an automatically generated spec). By comparison, the current develop branch ( bc6e7bf3b2a364b9c1673148e76cfa7e8b6682e4 ) has 70 examples, 0 failures, 1 pending (apparently the same pending spec as from that time).

Does this meet the criteria of fixing it and adding some more tests?

**Comment by silviapfeiffer** [comment]
WFM :-)
