### ISSUE TITLE
Amend cronjob email address

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#409]
Delete 'aidan.wilson@unimelb.edu.au' from the cronjob messages that go to <deploy@paradisec.intersect.org.au>

**Comment by silviapfeiffer** [comment]
Does he have a new one or has he left the project?

**Comment by nthieberger** [comment]
Can it be changed to aidan.b.wilson@gmail.com ?

**Comment by nthieberger** [comment]
Is it possible to allow us to amend this list ourselves? Maybe build a module that has these addresses in it?

**Comment by silviapfeiffer** [comment]
@johnf fixed it today. I think this may be one of the things to hand over to your new developers.

**Comment by silviapfeiffer** [comment]
Just ran newaliases to actually activate the change in email address.

**Comment by jangari** [comment]
Incidentally, I only just updated my email address in NABU from unimelb to my gmail address. I don't know how the addresses of the recipients of cron messages are handled, but it sounds like there's a list somewhere, possibly hard-coded in the cron scripts.

**Comment by johnf** [comment]
They are in /etc/aliases on the server

On Sun, Apr 26, 2015 at 09:56:21PM -0700, Aidan Wilson wrote:
> Incidentally, I only just updated my email address in NABU from unimelb to my gmail address. I don't know how the addresses of the recipients of cron messages are handled, but it sounds like there's a list somewhere, possibly hard-coded in the cron scripts.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/nabu-catalog/nabu/issues/409#issuecomment-96503508

Cheers,
John

-- 
John
Blog                             http://inodes.org
LCA2014                          http://linux.conf.au
