### ISSUE TITLE
Reports to depositors

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#410]
Send a report to depositors (maybe allow them to check a box that approves this?) on download of an item of theirs and its destination. Send annual reports on downloads and destinations?

**Comment by nthieberger** [comment]
We will add a question to our deposit form asking if they want to get reports. We should then add a note at the bottom of the report that asks them to contact us if they want to stop receiving reports.

**Comment by nthieberger** [comment]
The report sends the time/date of download and country of downloader (not their email address as this raises privacy issues)

**Comment by stasb** [comment]
When should the report be sent, in relation to the collection creation date? Should it be sent annually, the first send being 1 year from the collection insertion date?

**Comment by nthieberger** [comment]
Would it be possible to allow users to ask for a report whenever they want it? I realise that many files will never be downloaded so the reports will be empty if we do it every year as I originally suggested. What do you think @LindaBarwick  @AmandaPDSC ?

**Comment by LindaBarwick** [comment]
Yes that seems sensible to me

On Tuesday, April 21, 2015, nthieberger <notifications@github.com> wrote:

> Would it be possible to allow users to ask for a report whenever they want
> it? I realise that many files will never be downloaded so the reports will
> be empty if we do it every year as I originally suggested. What do you
> think @LindaBarwick <https://github.com/LindaBarwick> @AmandaPDSC
> <https://github.com/AmandaPDSC> ?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/nabu-catalog/nabu/issues/410#issuecomment-94552464>.
>


-- 
Sent from Gmail Mobile

**Comment by AmandaPDSC** [comment]
Yes, agreed

**Comment by stasb** [comment]
In terms of the backend, is the 'depositor' the collector of the item, or the operator? 

i.e. each item belongs to both a collector and an operator, I assume the collector is the depositor?

**Comment by nthieberger** [comment]
Usually, but not always the collector is the depositor (e.g. a deceased estate has a different depositor to collector). The operator is the person who digitises the files and has no rights in it.

**Comment by stasb** [comment]
So for the purposes of the report, should it be sent to the collector of the item?

**Comment by stasb** [comment]
Completed this feature. For users to request a download report, they must navigate to the dashboard page, and click on 'Depositor Report'. This will lead to a page where a date range can be specified, and the user clicks on a button for the report to be sent. The report will contain all downloads within the specified range, with the date, country, collection title, item title, and file name. No report will be sent if no results are found.

Please let me know if this sounds correct, and please provide feedback once deployed.

**Comment by nthieberger** [comment]
This sounds right, thanks. We'll see how it works out once deployed

**Comment by nthieberger** [comment]
I just tried it but it generated an error

**Comment by nthieberger** [comment]
Tried again and it generated an error again

**Comment by JonoGillett** [comment]
Staging has been updated with fixes for this issue, please test and let me know if there are any further problems.

**Comment by nthieberger** [comment]
This works now, but the report does not have country information for most items, presumably because it is not given by the downloader?

**Comment by JonoGillett** [comment]
Yes, it currently uses the information provided by the users in their profile to fill out the Country.
If they choose not to provide it, then the report will not contain that.

How would you like to proceed regarding this?

**Comment by nthieberger** [comment]
Just tried it again and it failed

**Comment by nthieberger** [comment]
This works, but the report should also contain some indication of who downloaded items
