### ISSUE TITLE
change address in export feeds

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#414]
Currently we have this :"Project Director based at the Department of Linguistics, University of Sydney, Transient Building, F12 University of Sydney, NSW 2006. Project Manager based at the School of Linguistics and Applied Linguistics, University of Melbourne, Victoria 3010, Australia NSW 2006 Australia."

But please change it to this:
PARADISEC Sydney Unit: Sydney Conservatorium of Music, C41, The University of Sydney, +61 2 9351 1383
PARADISEC Melbourne Unit: School of Languages and Linguistics, University of Melbourne, +61 2 8344 8952
PARADISEC Canberra Unit: College of Asia and the Pacific,The Australian National University, +61 2 6125 6115

**Comment by stasb** [comment]
Hi Nick,

Which part of Nabu creates this export data?

Thanks.

**Comment by nthieberger** [comment]
This is one of the xml feeds from NABU, see the API link at the bottom of
the catalog homepage.
Nick

**Comment by stasb** [comment]
Currently the addresses take the form of either:

'PARADISEC Sydney, Department of Linguistics, second floor Transient Building F12, Fisher Road, The University of Sydney, Camperdown Campus, NSW 2006, AUSTRALIA, Phone: +61 2 9351 2002
'

or

'Anna Margetts c/o PARADISEC, Department of Linguistics, The University of Sydney'

Do we want both variants to have the Sydney, Melbourne, and Canberra address lines all together as one field, as per the original issue comment?

**Comment by nthieberger** [comment]
No, this is only in the OAI-PMH and RIF-CS feeds and should be changed as per the original issue above. I'm not sure where you are seeing this one 'Anna Margetts c/o PARADISEC, Department of Linguistics, The University of Sydney'

**Comment by stasb** [comment]
Hi Nick, could you paste the part of the feed where the information you want changed appears? And the surrounding context? Not sure exactly which field you mean.

**Comment by nthieberger** [comment]
Actually, I realise this may have been put into our registration of the archive rather than being part of the feed, sorry. I'll ask the data harvesters and see if they can edit the details at their end.

**Comment by stasb** [comment]
Ok cool, so this issue is resolved?
