### ISSUE TITLE
Deleting files

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#417]
It seems that it is not advisable/permitted to delete files in the HFS, but that this should be done from within NABU. However, there are files in the HFS that do not appear in NABU for various reasons and need to be deleted, e.g., the collection LSNG1, and the two items: JM4-df, JM4-test

What can we do about these? Is it best to get Terem to delete them in a way that doesn't cause any further problems?

**Comment by AmandaPDSC** [comment]
It seems that deleting an item or a collection in Nabu doesn't necessarily delete all of the associated files. Is there any reason for this not to happen automatically?

**Comment by silviapfeiffer** [comment]
We were careful about deleting files. Terem should probably implement that
now that we have some experience.

Best Regards,
Silvia.

**Comment by nthieberger** [comment]
OK, so we need to be able to delete files in the repository that are not in the catalog (housekeeping). We should be able to do this directly using sftp or ssh, but how do we prevent terrible mistakes from happening, like the wrong directory being deleted ...? Maybe it needs to be done via NABU? The problem is that these files do not appear in NABU.

**Comment by silviapfeiffer** [comment]
Nothing should ever get in the repository without being in NABU.

**Comment by nthieberger** [comment]
Please also delete catalog/NT10/testonly/

**Comment by nthieberger** [comment]
Please assign admin rights to me, Linda and Amanda to delete files in the HFS. But send the deleted file to a staging area and require another admin to approve deletion

**Comment by AmandaPDSC** [comment]
Closing issues that duplicate this one - files that need deleting: LSNG1, LL1-006, LL1-007, SINM-OTP980, collection EG1

**Comment by nthieberger** [comment]
Please also delete RB5-temptest-CAT-PDSC_ADMIN.xml

**Comment by JonoGillett** [comment]
The directory LL1/006 contains files which I can't see anywhere else (different names, file sizes) are these files definitely OK to go?

**Comment by nthieberger** [comment]
Yes they need to go, thanks (they are duplicated in a complicated way in 006A and 006B)

**Comment by JonoGillett** [comment]
I have now deleted the following
Collections:
- LSNG1
- EG1

Items:
- LL1/006
- LL1/007
- SINM/OTP980
- RB5/temptest
- NT10/testonly
- JM4/df
- JM4/test

I think that covers everything from the different deletion tasks, but feel free to re-open if I've missed something.

**Comment by nthieberger** [comment]
Another to delete please: AMQ1 and its contents

**Comment by nthieberger** [comment]
I deleted this collection (AMQ1) and its contents

**Comment by JonoGillett** [comment]
I've closed this task since it's complete. For any new deletions please raise a new task so we can track it
