### ISSUE TITLE
spreadsheet upload

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#419]
An issue that keeps coming up for us is that we have to upload data into NABU via a spreadsheet. It generally can be tweaked to work, but a recent spreadsheet will not upload. Can you please advise why not, and perhaps adapt the upload system to make it easier to do, perhaps generating a validation error message that gives the user a clue about what is not right in the file? It could be to do with unicode characters, but, if so, this needs to be fixed as we want to be able to import all kinds of unicode characters.

**Comment by stasb** [comment]
Fixed this by changing the session store to active record based. Flash messages were being exceeded in size.

The current script does collect messages and errors regarding the upload, so you should be able to see what is wrong with the XLS files you upload. Try this out once this fix goes live, and let me know if you have further trouble with the uploads, and I can adjust the script accordingly.

**Comment by nthieberger** [comment]
I just tried to upload a spreadsheet and got the error. I tried with the collector's name as 'Arthur, Capell' and as Capell, Arthur'. The preferred form should be 'Arthur Capell'

**Comment by JonoGillett** [comment]
Could you email me through the failing spreadsheet when you get a chance?


Regarding the preferred form - As mentioned in a different issue, the upload needs a way to differentiate between first names (potentially plural) and last names (potentially plural), as otherwise it will fail to find the right user.

My suggestion would be to split the name field into first name and last name fields. That way you don't need to worry about syntax, you just put the bits in the relevant table cell.

**Comment by nthieberger** [comment]
Similar problem with this one, it has a single name 'VKS' for the collector. Is that what is causing it to fail to upload? We need to be able to allow single names.

[PDSC_minimal_metadataxls.xlsx](https://github.com/nabu-catalog/nabu/files/7439/PDSC_minimal_metadataxls.xlsx)

**Comment by AmandaPDSC** [comment]
Just had this same problem with a spreadsheet for the CLC collection. The only way it worked was to put the collector as Linda, Barwick.

**Comment by agrimmtt** [comment]
With the new version of Ruby deployed, and a minor change to the code, it'll be possible to handle `.XLSX` files - the newer Excel spreadsheet format. This is now awaiting deployment to the production server.

**Comment by agrimmtt** [comment]
Fixed by the latest deployment.

**Comment by AmandaPDSC** [comment]
this solution is a bit opaque to me - were the issues with format of collector names actually a problem with uploading xlsx files?

**Comment by agrimmtt** [comment]
@AmandaPDSC Yes. They were uploading an XLSX file and the system used to only handle XLS files.

**Comment by AmandaPDSC** [comment]
Ok, the problem I noted wasn't solved by changing the spreadsheet format, but was to do with Collector name format, so I'm still a bit puzzled. But perhaps you're saying that this issue is solved by the update?

**Comment by agrimmtt** [comment]
@AmandaPDSC Ah - the problem that @nthieberger had on October 5 is different from the one you had. Is it ok if we create a separate ticket for your problem?

**Comment by AmandaPDSC** [comment]
ok, but the original problem when this issue was reopened - 17 Jul 2015 - was also about the format of collector name

**Comment by agrimmtt** [comment]
Issue #528 "Create additional fields in the minimal metadata spreadsheet" also relates to getting information from spreadsheets, and will be worked on at the same time.

**Comment by agrimmtt** [comment]
Hi @AmandaPDSC ,

Issue #528 "Create additional fields in the minimal metadata spreadsheet" has been completed. The new spreadsheet has separate cells for first names and last names, so name format will not be a problem any more.
