### ISSUE TITLE
Reconfigure URLs

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#420]
We currently have unpredictable URLs generated by NABU , so, for example
http://catalog.paradisec.org.au/collections/AC2/items/FIJ021/essences/1030824

resolves what should be this url
http://catalog.paradisec.org.au/repository/AC2/FIJ021/AC2-FIJ021-004.jpg

But we want to be able to resolve to the image and not just the page

I am getting some work done (by Marco La Rosa) to build a viewer for image files but the problem is that the urls are not predictable. The URLS need to also be provided in the OAI-PMH feed (under DC:TOC) so that external services can pick them up properly. I can get Marco to talk directly to you if need be.

**Comment by nthieberger** [comment]
I'm unable to construct the image links in Nabu as I don't have all of the information required in the XML output. Consider the XML @:
http://catalog.pdsc/oai/item?verb=GetRecord&identifier=oai:paradisec.org.au:AC2-ETHGS101&metadataPrefix=olac

In there I can see the images associated with the item (dcterms:tableOfContents) and the URL of the item within
Nabu (dc:identifier). However, to get to the actual image page (not the image link itself) I need to construct (using
the 001 as as the example):
http://catalog.paradisec.org.au/collections/AC2/items/ETHGS101/essences/968480

Note that unique id as the last component - 968480. That is not included in the output so I can't even generate it programmatically.

So, Nabu needs some development to either:
- change the url structure to something that can be programmatically determined; e.g. 
http://catalog.paradisec.org.au/collections/AC2/items/ETHGS101

and then the image pages might be at:
http://catalog.paradisec.org.au/collections/AC2/items/ETHGS101/AC2-ETHGS101-001
http://catalog.paradisec.org.au/collections/AC2/items/ETHGS101/AC2-ETHGS101-002
etc
and the images themselves at:
http://catalog.paradisec.org.au/collections/AC2/items/ETHGS101/AC2-ETHGS101-001/display
http://catalog.paradisec.org.au/collections/AC2/items/ETHGS101/AC2-ETHGS101-002/display

or some such.

OR (THIS IS THE BETTER OPTION)

The URLs in Nabu can be anything provided that the fully qualified URLs to the image pages and images themselves are output in the XML so that they can be used as is without requiring programmatic generation.

This is the better option as any apps that use the OAI endpoint will keep working if the Nabu urls change.

**Comment by stasb** [comment]
I have currently changed the XML feed so that the full URL to the essence page is shown, instead of the file name. To get to the actual asset URL, '/display' needs to be added onto the end of this URL.

The data will now look like:

<dcterms:tableOfContents xsi:type="dcterms:URI">
http://catalog.paradisec.org.au/collections/BP3/items/002/essences/985314
</dcterms:tableOfContents>

If you would like to include the file name also, and the link to the file itself, could you advise how you would like this to display in the XML feed? I am not sure how to correctly tag it.
