### ISSUE TITLE
datestamp in OLAC/ OAI feed

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#422]
Something has happened in the OAI-PMH feed over the past few days that has stopped datestamping. This means the the harvester does not pick up our feed as it can't see new records. We have been updating the catalog over that time so there are definitely new records there. Can you please fix the datestamp?

**Comment by JonoGillett** [comment]
Could someone confirm if this is still an issue? It hasn't been raised recently.

**Comment by nthieberger** [comment]
I think it may still be an issue. For example, none of the BB2 tapes we have been accessioning lately appears in the OLAC view here: http://www.language-archives.org/language/pit

They have been up for some time, more than enough for the OLAC harvester to find them.

Can you please check on the datestamp in this stream:
http://catalog.paradisec.org.au/oai/item?verb=ListRecords&metadataPrefix=olac

to see what the most recent date is there?

**Comment by nthieberger** [comment]
Seems to be ok now
