### ISSUE TITLE
allow all origins to access /oai

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#423]
The server admins need to add some configuration to the webserver that says
"allow all origins to access /oai". Given that this app was developed by Silvia / John, it's
likely that the webserver in use will be nginx and so the configuration @
http://enable-cors.org/server_nginx.html needs to be added in the location fragment
defining the OAI endpoint.

This info should be enough to send to the appropriate admins. They should be able
to determine what to do based on what I've written here though they can call Marco (+61 401 738 392) if they need to

**Comment by stasb** [comment]
This is now completed and in production. Please let me know if you experience any more CORS related issues.
