### ISSUE TITLE
peculiar search fail

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#424]
I'm not sure what is happening here. Searching for RB3 in the item search generates an error, but any other identifier there seems fine. 

http://catalog.paradisec.org.au/items/search?utf8=%E2%9C%93&search=rb3

Case is not a problem. Searching for rb3 in the collections tab is fine too.

**Comment by nthieberger** [comment]
I have now replicated this with RB5 at the item level. It generates an error.

**Comment by JonoGillett** [comment]
The problem is due to sorting collectors by last name, where last name isn't guaranteed to have a value. I have changed this to sort on "last names first names" which guarantees a value will be present and consistent for sorting purposes.

http://144.6.225.96/items/search?utf8=%E2%9C%93&search=rb3
