### ISSUE TITLE
Automate transcode of TIF to jpg

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#425]
We need to build in a transcoding of all uploaded TIFs to jpg. And we need to do this for all the existing files. cf #418

**Comment by stasb** [comment]
Hi Nick, to clarify:

- when uploading a TIF, this must be converted to a jpg and saved?
- all existing TIFs that exist in the system must be converted to jpgs, and the TIF files removed?

Thanks

**Comment by nthieberger** [comment]
That's right, two processes, one dealing with existing files and one that is part of the pipeline for new items. But we need to only convert TIFs that do not already have a jpg, as some of the jpg files have been created at a potentially higher resolution than the ones that will be created

**Comment by silviapfeiffer** [comment]
Can I suggest keeping the tiff files around some they are uncompressed and this provide higher quality.

**Comment by nthieberger** [comment]
Of course! We are an archive! We want TIF but we also need to deliver at lower resolution, hence the need to make jpg

**Comment by nthieberger** [comment]
yes, sorry, I missed that in Stas's question. No, TIFs must not be altered or removed!

**Comment by JonoGillett** [comment]
Is the intention here that these become separate essence files? For example if I upload high_res.tiff it should be saved as high_res.tiff and high_res.jpg and listed in the item's essences as 2 lines?

Or are you thinking of storing the tiff in a less public way and only presenting the jpg from the catalog?

**Comment by nthieberger** [comment]
We want to store both, distinguished only by their extension

**Comment by JonoGillett** [comment]
I have modified the ingest system to process files with the type tiff and produce jpegs and pdfs automatically. I haven't put it on staging yet, I just wanted to make sure I was heading in the right direction.
[NOTE: this currently doesn't address the issue of converting existing files in the catalog]

The output of uploading a single-page TIF (AA1-001-3MB) is:
* x1 TIF file (the original)
* x1 converted JPEG file

The output of uploading a multi-page TIF (AA1-001-28MB) are as follows:
* x1 TIF file (the original)
* x3 single-page full-size JPEG files, 1 for each page
* x1 three-page PDF file, with jpeg quality

All files listed above are added as essence files to the item in question (AA1-001) and show up as so:
![image](https://cloud.githubusercontent.com/assets/10914573/8051645/736d2786-0ec2-11e5-83c1-5a4d2607f218.png)


Does all of that sound sensible to you folks? Have I missed anything?

**Comment by nthieberger** [comment]
This sounds good, but this item has no TIF files in it so I hope you are using it as a hypothetical  example. Please also ensure that any file with 'PDSC_ADMIN' is excluded from this process as they are admin files and not content files.

**Comment by JonoGillett** [comment]
It is sort of hypothetical. I am just using that collection/item as an easily locatable test on my development machine. I uploaded a TIF file into my test version of that item (as shown above), and it produced the output there. It doesn't affect the version on staging or production.

Due to the part of the ingest that I added the processing, it already ignores any files with the admin marking.

**Comment by JonoGillett** [comment]
I have now updated staging.

As an example of the quality of this process, the items here are the ones I've been using for testing (the multipage one is taken from GB01-001 and the other is just a sample TIF I found)
http://144.6.225.96/collections/JG1/items/001

**Comment by nthieberger** [comment]
This still needs work as it has to be applied to all of the existing collection

**Comment by AmandaPDSC** [comment]
Is this working as an automated process now? There seem to be .jpgs in Nabu corresponding to the .tifs that Nick Ward and I have been uploading this week into the GB collections.

**Comment by JonoGillett** [comment]
This is currently working as part of the upload process, so newly uploaded files will be transcoded.
However it will need to be applied to all the existing content as well, which has not yet been done.

**Comment by nthieberger** [comment]
We really need to get this done as the new viewer requires low res jpg and thumbnail files.

**Comment by agrimmtt** [comment]
The code for this has been pushed to production, and the transcoding is being run. It's still in progress, but closing anyway.

**Comment by agrimmtt** [comment]
Transcoding has been completed for existing content.
