### ISSUE TITLE
Please provide an XML list of all fields in the catalog

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#427]
I have someone developing an XML encoding (in Encoded Archival Description, EAD) to replace the files we write to the collection when we save an item. In order for them to figure out what the fields are they need an XML output of every field in our catalog, at both a collection and item-level. Can Terem please provide this so I can get the EAD equivalents worked out?

**Comment by nthieberger** [comment]
ok, it looks like I can get this at the item level by adding .xml to the url, but not at the collection level?

**Comment by silviapfeiffer** [comment]
It used to work when you're logged in to just put a .xml behind the item or the collection. Might be worth debugging why that stopped working.

**Comment by JonoGillett** [comment]
So from the looks of the XML view, it only shows up if you can manage the collection (or item, for the item view). 
Otherwise it will likely show you a blank page (or maybe a "This xml document has no style information... etc etc" message).
This sort of makes sense, given that the view will contain all the information including admin stuff.

Nick, could you confirm whether or not you are able to view the XML data for a collection you are able to manage? If you can't, then a screenshot or description of the output you get would be helpful.

**Comment by nthieberger** [comment]
I can see the xml for my own collections. The elements that need to be included from the collection level for each item are the following (that is, from <identifier> through to </admin info>

<identifier>NT1</identifier>
<readyForExport>true</readyForExport>
<private>false</private>
<title>South Efate (Vanuatu)</title>
<description>
Records in this collection were made during fieldwork, mainly in Erakor Village, Efate, Vanuatu between 1996-2000. They consist of audio recordings of South Efate speakers, originally on audio cassettes (hence there are often A and B sides of a single item). There is a total of 38 hours of language material, and the collection includes time-aligned transcripts for many recordings, and interlinear text for a small proportion of them. It also includes field notes. The material here is the basis for Thieberger's grammar of South Efate which also cites primary material in this collection. Where there is a transcript the file has the same name as the recording with a .txt extension. These transcriptions are not as accurate as the versions that are found in the interlinear annotation, and also have relics of earlier transcription conventions (p$ and m$ for coarticulated p̃ and m̃). Many of these transcripts have then been interlinearised in the version that can be found in NT8. More recordings and other material in South Efate can be found in collections NT1 to NT7 in PARADISEC. A description of the collection given here: http://languages-linguistics.unimelb.edu.au/thieberger/sefate.html
</description>
<collector>Nick Thieberger</collector>
<operator/>
<university>University of Melbourne</university>
<countries>
<country>Vanuatu - VU</country>
</countries>
<languages>
<language>Efate, South - erk</language>
<language>Lelepa - lpa</language>
</languages>
<region>Erakor, Eratap, Lelepa</region>
<geographicLocation>
<south_limit>-17.882</south_limit>
<north_limit>-17.418</north_limit>
<east_limit>168.652</east_limit>
<west_limit>168.033</west_limit>
</geographicLocation>
<accessInfo>
<adminAccess>
<userName>Nick Thieberger</userName>
<userName>Linda Barwick</userName>
<userName>Steve Cassidy</userName>
<userName>Various Various</userName>
<userName>Amanda test Harris</userName>
</adminAccess>
<dataAccessConditions>
Open (subject to agreeing to PDSC access conditions)
</dataAccessConditions>
<dataAccessNarrative/>
</accessInfo>
<depositInfo>
<metadataSource>depositor</metadataSource>
<orthographicNotes>p$ and m$ are co-articulated labio-velars</orthographicNotes>
<media/>
<recordCreated>2012-09-27 20:02:15 +1000</recordCreated>
<recordLastModified>2015-02-25 16:20:04 +1100</recordLastModified>
<adminComment>
Collection digitised in 2001. NICK THIEBERGER COLLECTION DATA 51 CDs, total of 38 hours of language material original medium: audio cassette date of recordings: 1996-2000 All burned as .AIFF data CDs. Archive copy of each CD in .AIFF data format.
</adminComment>
</depositInfo>
<adminInfo>
<depositFormReceived>true</depositFormReceived>
<tapeLocation>returned to depositor</tapeLocation>
<fieldOfResearch>200320 - Pacific Languages</fieldOfResearch>
<fundingBody>ARC - Australian Research Council</fundingBody>
<grantIdentifier>http://purl.org/au-research/grants/arc/DP0450342</grantIdentifier>
</adminInfo>

**Comment by JonoGillett** [comment]
I don't think that comment came through properly - it might have parsed any XML and tried to show it, but it just broke.

Also, I'm not quite sure what you mean by "need to be included from the collection level for each item" - are you saying that the collection's XML output needs changing?

**Comment by nthieberger** [comment]
OK, sorry. What I want is that the collection level metadata from the identifier element through to and including the adminInfo should be included with each item-level xml that is saved to a file sitting with the objects in the collection.

**Comment by JonoGillett** [comment]
Currently the catalog file uses the same template as the Item's XML view. If I change that to include the collection information it will be displayed through that web XML view as well.
Are you fine with that happening? If so I'll just change that template, otherwise I can easily create a copy with the new data.

I don't forsee a problem here, but I thought I'd confirm.

**Comment by nthieberger** [comment]
This only seems to be the case for records that are saved from now on, but it needs to be applied to all items retrospectively.

**Comment by agrimmtt** [comment]
Nick's XML (indenting is four spaces rather than 2 - apologies):

    <identifier> through to </admin info>

    <identifier>NT1</identifier>
    <readyForExport>true</readyForExport>
    <private>false</private>
    <title>South Efate (Vanuatu)</title>
    <description>
    	Records in this collection were made during fieldwork, mainly in Erakor Village, Efate, Vanuatu between 1996-2000. They consist of audio recordings of South Efate speakers, originally on audio cassettes (hence there are often A and B sides of a single item). There is a total of 38 hours of language material, and the collection includes time-aligned transcripts for many recordings, and interlinear text for a small proportion of them. It also includes field notes. The material here is the basis for Thieberger's grammar of South Efate which also cites primary material in this collection. Where there is a transcript the file has the same name as the recording with a .txt extension. These transcriptions are not as accurate as the versions that are found in the interlinear annotation, and also have relics of earlier transcription conventions (p$ and m$ for coarticulated p̃ and m̃). Many of these transcripts have then been interlinearised in the version that can be found in NT8. More recordings and other material in South Efate can be found in collections NT1 to NT7 in PARADISEC. A description of the collection given here: http://languages-linguistics.unimelb.edu.au/thieberger/sefate.html
    </description>
    <collector>Nick Thieberger</collector>
    <operator/>
    <university>University of Melbourne</university>
    <countries>
    	<country>Vanuatu - VU</country>
    </countries>
    <languages>
    	<language>Efate, South - erk</language>
    	<language>Lelepa - lpa</language>
    </languages>
    <region>Erakor, Eratap, Lelepa</region>
    <geographicLocation>
    	<south_limit>-17.882</south_limit>
    	<north_limit>-17.418</north_limit>
    	<east_limit>168.652</east_limit>
    	<west_limit>168.033</west_limit>
    </geographicLocation>
    <accessInfo>
    	<adminAccess>
    		<userName>Nick Thieberger</userName>
    		<userName>Linda Barwick</userName>
    		<userName>Steve Cassidy</userName>
    		<userName>Various Various</userName>
    		<userName>Amanda test Harris</userName>
    	</adminAccess>
    	<dataAccessConditions>
    		Open (subject to agreeing to PDSC access conditions)
    	</dataAccessConditions>
    	<dataAccessNarrative/>
    </accessInfo>
    <depositInfo>
    	<metadataSource>depositor</metadataSource>
    	<orthographicNotes>p$ and m$ are co-articulated labio-velars</orthographicNotes>
    	<media/>
    	<recordCreated>2012-09-27 20:02:15 +1000</recordCreated>
    	<recordLastModified>2015-02-25 16:20:04 +1100</recordLastModified>
    	<adminComment>
    		Collection digitised in 2001. NICK THIEBERGER COLLECTION DATA 51 CDs, total of 38 hours of language material original medium: audio cassette date of recordings: 1996-2000 All burned as .AIFF data CDs. Archive copy of each CD in .AIFF data format.
    	</adminComment>
    </depositInfo>
    <adminInfo>
    	<depositFormReceived>true</depositFormReceived>
    	<tapeLocation>returned to depositor</tapeLocation>
    	<fieldOfResearch>200320 - Pacific Languages</fieldOfResearch>
    	<fundingBody>ARC - Australian Research Council</fundingBody>
    	<grantIdentifier>http://purl.org/au-research/grants/arc/DP0450342</grantIdentifier>
    </adminInfo>

**Comment by agrimmtt** [comment]
@nthieberger the following request hasn't yet been implemented:

> This only seems to be the case for records that are saved from now on, but it needs to be applied to all items retrospectively.

**Comment by nthieberger** [comment]
Right, sorry. The EAD part of this no longer applies, but we do need to have each xml snippet per item including the collection -level information too, for all items in the collection and then for each new item that is added.

**Comment by agrimmtt** [comment]
Code has been deployed, but needs to be run.

**Comment by nthieberger** [comment]
So can it be run now please?

**Comment by agrimmtt** [comment]
The rake task has been run.

There are now at most 208 PDSC_ADMIN.xml files that weren't generated today, and they're most likely to be associated with an outdated item identifier. Has this resolved the issue?

**Comment by nthieberger** [comment]
I think it is resolved.
