### ISSUE TITLE
NABU problems today

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#428]
NABU is behaving strangely. It is sometimes working fine, then it is saying it is 'waiting for available socket' and hangs. Is it getting overloaded with requests?

**Comment by nthieberger** [comment]
could try putting the database and feed onto a separate server perhaps

**Comment by baristuncay** [comment]
We can try breaking out parts of nabu into smaller services

**Comment by LindaBarwick** [comment]
I'm going to try logging in from another machine

**Comment by stasb** [comment]
Hi Nick, are there any particular actions that cause the error?

**Comment by nthieberger** [comment]
the action is that Marco can’t load a URL external to the app within Javascript

**Comment by nthieberger** [comment]
I think it could be the viewer that Marco wrote that is making demands on NABU. So, when it is hanging up it makes the whole system slow down.

**Comment by JonoGillett** [comment]
Have you noticed any continued performance issues? If not we may as well close this ticket until it re-appears.

**Comment by agrimmtt** [comment]
Closed due to it not re-appearing.
