### ISSUE TITLE
Server must state that it can handle byte range requests via a specific header

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#431]
More server configuration required in order to handle seeking in media for our viewer
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Configuring_servers_for_Ogg_media
Although this is for ogg I think it applies to all media types. Specifically, the server must
state that it can handle byte range requests via a specific header:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Configuring_servers_for_Ogg_media#Handle_HTTP_1.1_byte_range_requests_correctly

**Comment by stasb** [comment]
Hi Nick, I have just implemented this and it's now currently live in production. I have tested locally with a JS media player, and was able to seek mp3 files. 

Please let me know if this works with the current viewer being developed, or if any issues arise.

**Comment by nthieberger** [comment]
Hi Stas,

I just tried moving the slider along in an mp3 file, for example in
http://catalog.paradisec.org.au/collections/NT1/items/003/essences/1010228,
but it didn't work and it should. Seeking may be working but I don't know
the way to call it.

Nick

**Comment by stasb** [comment]
Hi Nick,

That small player on the the essence page is not capable of seeking. Another kind of player is required.
