### ISSUE TITLE
Advanced search failure

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#433]
I am trying to look for any item in collection  SINM that has an audio file (mime type audio/x-wav) but when I put that into the advanced search it returns no hits. There are items with these characteristics so the search needs to be fixed

**Comment by JonoGillett** [comment]
Could you confirm if this is still an issue? I am able to search based on essence file metadata and retrieve results e.g. http://catalog.paradisec.org.au/items/advanced_search?utf8=%E2%9C%93&identifier=SINM&mimetype=audio%2Fx-wav

**Comment by nthieberger** [comment]
OK, that works, but could there be a predictive text or dropdown menu of existing file types in the collection so the user doesn't have to figure out what they may be ?

**Comment by agrimmtt** [comment]
Resolved by the deployment made on Monday 4 January.
