### ISSUE TITLE
Automatic database backups

### ISSUE THREAD

**Issue by baristuncay** [nabu-catalog/nabu#437]
Need to investigate a way to automatically backup the database

**Comment by JonoGillett** [comment]
Automated nightly backups are in place as of October 4. @nthieberger please read through the below and confirm that you are happy with the approach that is in place (or raise any concerns).

It would probably be worthwhile discussing this with your infrastructure/IT people to get their thoughts/opinions (particularly about where the backups should be stored)

Backups are stored in:
/mnt/backups/data/mysqlbackups

Backup process is currently as follows:
1. Nightly backups are stored for 7 days
2. One nightly backup per week is moved to the archive (others are discarded as they reach a week old)
3. Archived backups are kept for 2 months, and as they become older than 2 months they are discarded

As an example, looking at the backups on 15/11/2016 would show the following.
/mnt/backup/data/mysqlbackups will contain:
- 7 nightly backups for 7/11 to 14/11
/mnt/backup/data/mysqlbackups/archive will contain:
- 5 weekly archives back til the 4/10 (when backups started)

**Comment by enwardy** [comment]
@nthieberger  not sure if the above summary regarding backups (posted some 16 months ago) is still current, but if so, and if it's ok, can this issue be closed off?
