### ISSUE TITLE
SINM-OTP980

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#439]
Please delete this item from the collection. [I think we not meant to delete items ourselves as it interferes with NABU's management of the file structure?]

**Comment by AmandaPDSC** [comment]
Other items/collections that need deleting: LSNG1, LL1-006, LL1-007

**Comment by nthieberger** [comment]
I don't have permissions to delete SINM-OTP980 or the others

**Comment by AmandaPDSC** [comment]
I've copied these details over to #417
