### ISSUE TITLE
Please install the viewer

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#440]
Marco La Rosa has built a viewer for our collections that is available as below. Please install this and check with him about any problems. It all works well in testing.  

Assume there is a folder called "viewer" on the webserver that comes up at the URL http://catalog.paradisec.org.au/viewer

In that folder they can just check out the code, viz:
git clone -b testing git@bitbucket.org:marcolarosa/pdsc-collection-viewer.git .

**Comment by JonoGillett** [comment]
Hi Nick,

I unfortunately don't have root permissions on the production host to be able to install this fully.
I have done the part that I am able, which is to clone the code into an accessible directory.

All that needs to be done now is to update the `/etc/nginx/sites-enabled/nabu` file with:
```
  location /viewer {
    alias /srv/www/nabu/viewer/current;
  }
```
somewhere, probably after the existing location configs.
Followed by `nginx -s reload`

The viewer should then be accessible from http://catalog.paradisec.org.au/viewer

**Comment by LindaBarwick** [comment]
Who does have the root permissions?

**Comment by nthieberger** [comment]
I've asked Silvia and John to assign permissions

**Comment by silviapfeiffer** [comment]
baris already had sudo access. Now, juliam has it too.

**Comment by JonoGillett** [comment]
Hi Folks,

The viewer is now installed at http://catalog.paradisec.org.au/viewer . Please let me know if you have any issues with the hosting. Other than that, please contact the original developer.

Cheers,
Jono

**Comment by nthieberger** [comment]
OK, thanks, this looks great (and the pdf function also works now that it is all hosted in the same place, e.g. http://catalog.paradisec.org.au/viewer/#/AC2/VUNU105). Next thing is that the 'view' button next to a file should now resolve to the new viewer rather than the original viewer. But can that be done in a way that allows the user to move between the viewer and the list of items in the catalog? And we also need to distinguish the admin view that still allows us to address the essence files, can you advise on how we may do that?

**Comment by nthieberger** [comment]
@LindaBarwick @AmandaPDSC what do you think? Maybe putting a 'View all' button above and next  to the title 'Content files' would allow users to go to the viewer?

**Comment by JonoGillett** [comment]
It might be best to create a separate issue for adding the buttons/links since the "install the viewer" part of this task is complete.
