### ISSUE TITLE
add a 'view all' button

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#441]
Putting a 'View all' button above and next to the title 'Content files' will allow users to go to the new viewer, but still allow the old view per item if required.

**Comment by JonoGillett** [comment]
I tried a couple of different positions for the link, which do you prefer?

![image](https://cloud.githubusercontent.com/assets/10914573/8154318/3d7c891e-137c-11e5-9bdc-6b54c49f1133.png)

![image](https://cloud.githubusercontent.com/assets/10914573/8154323/5435a12c-137c-11e5-9b17-70ee0eccdf9c.png)

**Comment by nthieberger** [comment]
I think the first one stands out better

**Comment by JonoGillett** [comment]
Cool. That was my preference as well, I just wanted to be sure.

**Comment by AmandaPDSC** [comment]
I agree - good solution to get to the viewer
