### ISSUE TITLE
Need a way to return thumbnails and similar "admin" files from the API

### ISSUE THREAD

**Issue by JonoGillett** [nabu-catalog/nabu#442]
Currently the repository controller, which is used for most/all of the essence file integrations with the viewer, doesn't have a way to return the additional files related to the essences. For example a thumbnail or soundimage file.

The controller needs to be able to return files while at the same time maintaining the existing security mechanisms. The controller should use the essence file's access restrictions for the related files as well. For example: someone who can view an image can also view the image's thumbnail.

*@nthieberger et al. Feel free to correct me on any of the points here. This issue is created from my interpretation of a conversation with Nick about the viewer not being able to access the thumbnails etc*

**Comment by nthieberger** [comment]
ok, how about we just use' _thumb' and '_spectrum' on filenames without using 'PDSC_ADMIN' and that way the files will be visible to users (not a preferred option) but will be able to be accessed by the viewer

**Comment by nthieberger** [comment]
Just to clarify. The filenames using -thumb-PDSC_ADMIN are now open to the viewer, is that right? But are not visible to normal users of the collection?
