### ISSUE TITLE
Search is not cleared

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#446]
After a search, there is no way to return to a pre-search state in which all records are presented. This is not even possible if doing a blank search. Clicking on the 'collections' tab should clear the existing search parameters.

**Comment by JonoGillett** [comment]
The behaviour of retaining search was introduced as a workaround for not storing result sets (to enable the "back to search results" functionality). You can clear the search by pressing the 'Clear' button at the top of the collection or item search page.

If you'd like this behaviour changed we can discuss that.
