### ISSUE TITLE
Bulk update fails

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#447]
I tried bulk update this morning and it generates an error

**Comment by JonoGillett** [comment]
Could you tell me which items, what fields you tried to update, as well as what sort of error you received? 
Even just generally, like 'add language to most of collection X' - It can be a bit hard to track down otherwise.

**Comment by nthieberger** [comment]
I tried to update SINM with 'not private' and 'open access' and it then generates the usual error 'We're sorry something went wrong'

**Comment by JonoGillett** [comment]
Staging now has changes that should fix this issue, please test it and let me know if there are any further problems.

**Comment by nthieberger** [comment]
Just tested it and it works
