### ISSUE TITLE
Bulk update failed

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#451]
I just tried bulk updating MR1 to make all items public and it gave the error

**Comment by nthieberger** [comment]
Tried the same thing on the staging server and it works ok there.

**Comment by nthieberger** [comment]
Tried again to bulk update AW2 and it failed again

**Comment by nthieberger** [comment]
This is a serious problem that is stopping us doing everyday functions in the collection. Please prioritise fixing it.

**Comment by JonoGillett** [comment]
Nick - apologies, it seems like I never got around to deploying these fixes into production.
I have updated it now, so this issue should be resolved.

Please let me know if it continues to occur.

**Comment by nthieberger** [comment]
great, works fine, thanks.
