### ISSUE TITLE
Search fail

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#452]
I did the following search: 
http://catalog.paradisec.org.au/items/advanced_search?utf8=%E2%9C%93&filename=.trs

It finds 7 files in the BN1 collection, but we have 189 .trs files in the collection so why isn't it finding them?

BN1-001-A.trs
BN1-001-B.trs
BN1-007-A.trs
BN1-008-A.trs
BN1-009-A.trs
BN1-010-A.trs
BN1-011-B.trs
BN1-012-A.trs
CH1-200202-A.trs
CH1-200202-B.trs
CH1-200203-A.trs
CH1-200203-B.trs
CH1-200204-A.trs
CH1-200204-B.trs
CH1-200205-A.trs
CH1-200205-B.trs
CH1-200206-B.trs
CH1-200206-A.trs
CH1-200208-B.trs
CH1-200208-A.trs
CH1-200401AGG-01.trs
CH1-200401BDC-01.trs
CH1-200401NDP-01.trs
CH1-200402EFS-01.trs
JHWS2-20090220-01_ALL.trs
LG1-09091401-A.trs
LG1-09091402-A.trs
LG1-09091404-A.trs
LG1-09091405-A.trs
LG1-09091406-A.trs
LG1-09091407-A.trs
LG1-09091408-A.trs
LG1-09091501-A.trs
LG1-09091502-A.trs
LG1-09091503-A.trs
LG1-09091504-A.trs
LG1-09091505-A.trs
LG1-09091601-A.trs
LG1-09091602-A.trs
LG1-09091603-A.trs
LG1-09091604-A.trs
LG1-09091605-A.trs
LG1-09091606-A.trs
LG1-09091701-A.trs
LG1-09091702-A.trs
LG1-09091703-A.trs
LG1-09091704-A.trs
LG1-09091801-A.trs
LG1-09091802-A.trs
LG1-09091803-A.trs
LG1-09091804-A.trs
LG1-09091805-A.trs
LG1-09092301-A.trs
LG1-09092302-A.trs
LG1-09092303-A.trs
LG1-09092401-A.trs
LG1-09092402-A.trs
LG1-09092403-A.trs
LG1-09092404-A.trs
LG1-09092801-A.trs
LG1-09092802-A.trs
LG1-09092901-A.trs
LG1-09092902-A.trs
LG1-09093001-A.trs
LG1-09093002-A.trs
LG1-09093003-A.trs
LG1-09100101-A.trs
LG1-09100102-A.trs
LG1-09100103-A.trs
LG1-09100201-A.trs
LG1-09100202-A.trs
LG1-09100203-A.trs
LG1-09100402-A.trs
LG1-09100403-A.trs
LG1-09100404-A.trs
LG1-09100501-A.trs
LG1-09100502-A.trs
LG1-09100503-A.trs
LG1-09100601-A.trs
LG1-09100701-A.trs
LG1-09100702-A.trs
LG1-09100703-A.trs
LG1-09100704-A.trs
LG1-09100801-A.trs
LG1-09100802-A.trs
LG1-09100803-A.trs
LG1-09100902-A.trs
LG1-09100903-A.trs
LG1-09100904-A.trs
LG1-09100905-A.trs
LG1-09101201-A.trs
LG1-09101202-A.trs
LG1-09101203-A.trs
LG1-09101204-A.trs
LG1-09101301-A.trs
LG1-09101302-A.trs
LG1-09101303-A.trs
LG1-09101304-A.trs
LG1-09101501-A.trs
LG1-09101502-A.trs
LG1-09101601-A.trs
LG1-09101602-A.trs
LG1-09101901-A.trs
LG1-09101902-A.trs
LG1-09101903-A.trs
LG1-09102001-A.trs
LG1-09102002-A.trs
LG1-09102003-A.trs
LG1-09102801-A.trs
LG1-09102802-A.trs
LG1-09102803-A.trs
LG1-09102804-A.trs
LG1-09102901-A.trs
LG1-09102902-A.trs
LG1-09102903-A.trs
LG1-09110101-A.trs
LG1-09110102-A.trs
LG1-09110103-A.trs
LG1-09110104-A.trs
LG1-09110105-A.trs
LG1-09110201-A.trs
LG1-09110202-A.trs
LG1-09110203-A.trs
LG1-09110301-A.trs
LG1-09110302-A.trs
LG1-09110303-A.trs
LG1-09110401-A.trs
LG1-09110402-A.trs
LG1-09110403-A.trs
LG1-09110404-A.trs
LG1-09110405-A.trs
LG1-09110501-A.trs
LG1-09110502-A.trs
LG1-09110601-A.trs
LG1-09110602-A.trs
LG1-09110901-A.trs
LG1-09110902-A.trs
LG1-09110903-A.trs
LG1-09110904-A.trs
LG1-09111701-A.trs
LG1-09111702-A.trs
LG1-09111703-A.trs
LG1-09112201-A.trs
LG1-09112202-A.trs
LG1-09112301-A.trs
LG1-09112401-A.trs
LR1-041806-04.trs
LR1-041806-05.trs
LR1-041806-08.trs
LR1-062406-A.trs
LR1-063006-02.trs
NT10-W08-A.trs
NT10-W08-B.trs
NT10-W11-A.trs
SAW2-092-A.trs
VG1-060014-1.trs
VG1-06003-1.trs
VG1-06004-1.trs
VG1-06005-1.trs
VG1-06006-1.trs
VG1-06008-A.trs
VG1-06008-1.trs
VG1-06010-A.trs
VG1-06010-1.trs
VG1-06012-1.trs
VG1-06013-1.trs
VG1-06014-1.trs
VG1-06015-1.trs
VG1-06016-1.trs
VG1-06017-1.trs
VG1-06018-1.trs
VG1-06019-1.trs
VG1-06020-1.trs
VG1-06021-1.trs
VG1-06022-1.trs
VG1-06023-1.trs
VG1-06024-1.trs
VG1-06025-1.trs
VG1-06026-1.trs
VG1-06027-1.trs
VG1-06028-1.trs
VG1-06029-1.trs
VG1-06030-1.trs
VG1-06031-1.trs
VG1-06032-1.trs
VG1-06033-1.trs
VG1-06034-1.trs
VG1-06035-1.trs
VG1-06036-1.trs

**Comment by JonoGillett** [comment]
It seems like the indexing was out of date. I have run a manual update and now you can find all those files.
I will have to take a look at automating this process though.

**Comment by nthieberger** [comment]
Can you let me know if this can be automated. I had reports from a user that they couldn't find something and it sounds like it was the same issue, so it would be good to have an index run every 12 hours perhaps?

**Comment by JonoGillett** [comment]
I've added it as one of the cronjobs, to run every hour. It's not too intensive and it should take under 10 minutes to complete so that's the most impact it will have - 10 minutes every hour.

I can decrease the frequency if we encounter any performance issues.

**Comment by nthieberger** [comment]
Another search fail. Looking for NT5-TokelauThatch gets zero hits, but it is there: http://catalog.paradisec.org.au/collections/NT5/items/TokelauThatch

**Comment by nthieberger** [comment]
And another, searching for SN1-ZionaChurch20131128, as an item, fails but it is the identifier of an item

**Comment by LindaBarwick** [comment]
Could the capitalisation be an issue?

**Comment by nthieberger** [comment]
maybe, but it needs to be fixed. The capitalisation of the search term is the same as the target. and 'Thatch' ot 'thatch' finds the item, but NT5-TokelauThatch and TokelauThatch do not.

**Comment by agrimmtt** [comment]
The match for "Thatch" (rhyme not intended) may be the result of the word appearing in the title and description.

**Comment by agrimmtt** [comment]
The fix for this issue has been deployed to staging, but not production.

If you go to http://144.6.225.96/items/search and do a search for NT5-TokelauThatch , you get a hit for http://144.6.225.96/collections/NT5/items/TokelauThatch .

By contrast, if you go to the production server, which hasn't had the fix deployed, at http://catalog.paradisec.org.au/items/search and do a search for NT5-TokelauThatch , you won't get a hit, indicating that the difference is because of the changes made.

This won't work with SN1-ZionaChurch20131128 , because the collection SN1 on the staging server doesn't have any items in it.

Please let me know if you're happy with the changes made.
