### ISSUE TITLE
Delete files in GB collections

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#454]
In each of the directories inside the 50 GB collections there is a file that ends in -01.tif. It needs to be deleted, e.g., GB38-001-01.tif, sftp://nickt@catalog.paradisec.org.au//srv/catalog/GB33/018/GB33-018-01.tif . This action needs to wait until all the replacement files are uploaded.

**Comment by enwardy** [comment]
That's not quite right, Nick, unfortunately. Any of the tifs that were single page originals have been left there, with their original filename, eg. GB33-028-01.tif. So these ones need to stay, but (presumably?) need to be renamed to match the new format with three digits in the final position, so: GB33-028-001.tif. 

All the OTHER -01.tif files (the multi-page ones) do need to be deleted, as they have been replaced by the -ALL.pdfs and the single page tifs (-001.tif, -002.tif etc). 

Sorry, I imagine this will complicate this task significantly.

**Comment by nthieberger** [comment]
OK, so is it possible to do a search for any file that ends in -01.tif that has no other files numbered -001  and should then be renamed to -001.tif? And then any file that is named -01.tif and DOES have other files -001.tif can be deleted.

**Comment by enwardy** [comment]
I don't know how to do that search:

files that end in -01.tif that have no other files in the same Item numbered -001.tif

any ideas?

**Comment by nthieberger** [comment]
I'm hoping that Jono can do this.

**Comment by nthieberger** [comment]
I have deleted the -01 files in all collections from GB01 to GB20

**Comment by nthieberger** [comment]
This is now ready for action

**Comment by nthieberger** [comment]
Basically this is a search for any item with files in a GB collection that contains -01. and also has a file with the same name with -001. The -01. file can then be deleted.
