### ISSUE TITLE
files uploading to Nabu in batches, then not correctly sorting within Nabu file list

### ISSUE THREAD

**Issue by enwardy** [nabu-catalog/nabu#455]
Whilst uploading files (GB tifs) from Azoulay (Send to Archive) to Nabu, a random selection of the tifs seem not to have been sent, and haven't appeared in Nabu, but then are gone from the Send to Archive Folder. No error message came through. Not sure what has happened

**Comment by enwardy** [comment]
Ok, they have actually uploaded, just that they have not slotted in to their correct order in the filelist. What has happened instead is that all of the files that were delayed, and uploaded in a later batch, have been added to the end of the filelist, and not gone into their correct numerical order. Maybe that will update automatically and put them in correct order at some point?

**Comment by JonoGillett** [comment]
Hi @enwardy could you give some specific collection and item details for this problem? There's a lot of GB collections and files there to check otherwise.

**Comment by enwardy** [comment]
@JonoGillett  -

E.g. 
GB32-001-010
GB32-007-015
GB32-009-017

and there are plenty of others. Would you like me to try to send you a complete list?

**Comment by nthieberger** [comment]
If you click on 'filename' in the NABU view of the files it resorts this list. But it is strange that all files seems to be in order except these ones until you force it to order. And then that ordering is lost f another operation occurs

**Comment by AmandaPDSC** [comment]
all we need here is that the default is to sort files by filename (not date added)

**Comment by agrimmtt** [comment]
I've changed the ordering of files on the item page. The changes have been pushed to the staging server. Unfortunately, the examples within GB32 can't be seen on staging, as each item within GB32 on staging has only one file each. @enwardy if you've got other examples that'd be applicable on the staging server, let me know.

Let me know if you're happy with the changes.

**Comment by AmandaPDSC** [comment]
Other items like NT1-20002 have a large number of files, but these were not recently uploaded and are sorting as expected. The large number of files in the GB collections were the ones recently uploaded that weren't sorting.
