### ISSUE TITLE
page names in NABU

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#457]
When looking at the history given under the 'back' button in the browser in Nabu, it just lists 'NABU' for each of the previous pages visited. It would be better if the pages could be named so that it was easier to navigate back to the desired page.

**Comment by agrimmtt** [comment]
Hi @nthieberger . I've added page names to the staging version. When viewing a collection, item, or essence, it'll show the name of the thing (for essences, it'll also have the name of the item). For cases other than viewing something, it'll indicate what kind of action you're taking, such as "Add New Collection" and "Advanced Item Search".

Let me know what you think, especially if there's any pages that need additional detail.

**Comment by nthieberger** [comment]
I think this is fine now, thanks.
