### ISSUE TITLE
files not appearing in NABU

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#467]
These files are in the collection but the audio files are not showing up in NABU. Any idea why?

SN1-TAMPIRITOA20140403-audio.eaf
SN1-TAMPIRITOA20140403-audio.mp3
SN1-TAMPIRITOA20140403-audio.wav
SN1-TAMPIRITOA20140403-video.eaf
SN1-TAMPIRITOA20140403-video.mov
SN1-TAMPIRITOA20140403-video.mp4

**Comment by JonoGillett** [comment]
I'm uncertain as to why they didn't show up the first time, but when I re-uploaded them they have been successfully entered into the system
