### ISSUE TITLE
Two collections behaving differently to others

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#471]
files in items in IG1 and IG2 are not available to this user, see the email extracts below:

"Very strange – all of those links fail for me, in both Firefox 41.0.1 and also Safari 9.0 – see attached screenshots.  And I’m definitely logged in.  It all works fine in both browsers if I try one of the other collections (e.g. IG3, IG8, etc)."

http://catalog.paradisec.org.au/collections/IG2/items/005/essences/1042515
http://catalog.paradisec.org.au/collections/IG2/items/006/essences/1042520
http://catalog.paradisec.org.au/collections/IG1/items/020/essences/1042598

As for the recordings in IG1 and IG2, when I go to those links that you provided, I can see the files, but when I click on ‘View’ I just a page that says ‘Sorry something went wrong’.  But with the other collections I go to the copyright agreement page and then to the recordings.

**Comment by agrimmtt** [comment]
Although I wasn't able to reproduce the exact error on my own machine, we believe we know what went wrong, and have fixed it.

The fix has been deployed to the staging machine, but not to production.
