### ISSUE TITLE
File information should update when files are overwritten

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#473]
Nick Fowler-Gilmore has been repairing files in the TS1 collection, but when a new files is uploaded to overwrite the previous file, the file metadata is not updated. Can some sort of look-up be triggered each time a new file is uploaded to overwrite this metadata?

**Comment by AmandaPDSC** [comment]
Is it possible to retrospectively update the file metadata? We've noticed in the list of odd sample/bit rates that for some items in this list, the file has correct rates, but the file metadata hasn't been updated. If the file metadata could be updated for all files in the collection, could we then get an updated list of sample/bit rates for wav files?

**Comment by agrimmtt** [comment]
Do you have any specific examples of this I can look at? (If you don't, that's ok)

**Comment by AmandaPDSC** [comment]
I've checked with Nick FG and Jodie who have been doing this resampling work, and they haven't got any record of which files' metadata wasn't updated. They could go through and check files manually, but otherwise don't have a way of recalling that information.

**Comment by agrimmtt** [comment]
This task was completed yesterday, as part of my work on #570 , which was completed today.
