### ISSUE TITLE
Change citation form in all items

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#475]
Related to #474 - and after or concurrent with DOI implementation we need to change the citation field of all items from having a URL to having a DOI

**Comment by agrimmtt** [comment]
What should come last? The date, or the DOI?

Should http://144.6.225.96/collections/AA1/items/001 have

> Alexander Adelaar (collector), Alexander Adelaar (recorder), 1987; Pak Nongeng tells about the first four people, food taboos, and various other topics, X-WAV/MPEG, 10.5072/12/55F22AD7DA4BC 2015-10-30.

or

> Alexander Adelaar (collector), Alexander Adelaar (recorder), 1987; Pak Nongeng tells about the first four people, food taboos, and various other topics, X-WAV/MPEG, 2015-10-30 10.5072/12/55F22AD7DA4BC.

? Also, what punctuation should separate the date and the DOI?

**Comment by LindaBarwick** [comment]
I think the DOI should come last, and also should have "DOI:" before it

**Comment by agrimmtt** [comment]
http://144.6.225.96/collections/AA1/items/001 now has

> Alexander Adelaar (collector), Alexander Adelaar (recorder), 1987; Pak Nongeng tells about the first four people, food taboos, and various other topics, X-WAV/MPEG, 2015-10-30. DOI: 10.5072/12/55F22AD7DA4BC

and http://144.6.225.96/collections/AA1/items/001/essences/967948 has

> Alexander Adelaar (collector), Alexander Adelaar (recorder), 1987; MPEG, AA1-001-A.mp3, 2015-10-30. DOI: 10.5072/12/55F22C998A7FD

Do they look ok?

**Comment by nthieberger** [comment]
It seems that no current items have proper citation forms that include the url:
So this example doesn't actually give a citation that can be tracked:

Alexander Adelaar (collector), Alexander Adelaar (recorder); Pak Kaslem tells: 2 folk stories + accounts of customary law, MPEG/X-WAV, 2016-02-23.

**Comment by agrimmtt** [comment]
Hi @nthieberger .

Thanks for pointing this out. I've changed it to show the URL if the DOI is unavailable.

An item example at http://144.6.225.96/collections/AA2/items/005

> Alexander Adelaar (collector), Alexander Adelaar (recorder), 1990; First part 'Ule'-ule'an Titilong' (by Baki' Teba), MPEG/X-WAV, 2016-02-24. http://catalog.paradisec.org.au/collections/AA2/items/005

An essence example at http://144.6.225.96/collections/AA2/items/005/essences/968005

> Alexander Adelaar (collector), Alexander Adelaar (recorder), 1990; MPEG, AA2-005-A.mp3, 2016-02-24. http://catalog.paradisec.org.au/collections/AA2/items/005/essences/968005

This will be fixed on production with the next deploy.
