### ISSUE TITLE
Change language search url to allow external searches

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#487]
We currently have a faceted search by language that creates a url like this:
http://catalog.paradisec.org.au/items/search?language_id=162

However, the number is an idiosyncratic, NABU-internal number. It is important the search uses the standard iso-639-3 code which is also stored with the language number.

Please change the search url so that it is a predictable one, so the above url would be 

http://catalog.paradisec.org.au/items/search?language_id=aia

**Comment by agrimmtt** [comment]
Would you like the same with countries at some stage?

**Comment by nthieberger** [comment]
yes, probably makes sense.

**Comment by agrimmtt** [comment]
Just to clarify, is changing the simple search sufficient, as opposed to modifying the advanced search as well?

Also, are you able to describe what the new, improved search URL will be used for? Is it just for people being able to edit the URL manually, or will some sort of external program use it?

**Comment by nthieberger** [comment]
it would allow external processes to point at our collection

**Comment by agrimmtt** [comment]
Is changing the simple search sufficient, as opposed to modifying the advanced search as well?

**Comment by nthieberger** [comment]
Just a simple search should be ok for current purposes.

**Comment by agrimmtt** [comment]
The change has been made.

Examples of collection searches:

* http://catalog.paradisec.org.au/collections/search?language_code=kit
* http://catalog.paradisec.org.au/collections/search?country_code=SB
* http://catalog.paradisec.org.au/collections/search?country_code=SB&language_code=kit

Examples of item searches:

* http://catalog.paradisec.org.au/items/search?language_code=duo
* http://catalog.paradisec.org.au/items/search?country_code=PH
* http://catalog.paradisec.org.au/items/search?country_code=PH&language_code=duo
