### ISSUE TITLE
language list is wrong

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#488]
Clicking on the content or subject language feld on the right of this screen : http://catalog.paradisec.org.au/admin/languages

pops up an incomprehensible list  that should instead be a list of language names.

**Comment by agrimmtt** [comment]
I've fixed this bug. The admin page http://144.6.225.96/admin/languages now only have lists that make sense. Are you happy with the labels?

**Comment by nthieberger** [comment]
Yes, this is good, but the same problem occurs in the following screens in the menu on the right
http://144.6.225.96/admin/countries
http://144.6.225.96/admin/agent_roles
http://144.6.225.96/admin/funding_bodies

**Comment by agrimmtt** [comment]
Thanks for spotting that. I didn't think of checking the other pages. I'll look into it at some stage.

**Comment by agrimmtt** [comment]
Reopening because it only fixes it for http://144.6.225.96/admin/languages , not for the other pages mentioned by Nick.

**Comment by agrimmtt** [comment]
The additional pages have been fixed today.
