### ISSUE TITLE
add some fields to CSV export

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#492]
Can you please provide a detailed listing with sample rates of files for the TS1 collection in the first instance, but this information should be added to the csv export so we can generate it ourselves.

**Comment by JonoGillett** [comment]
@nthieberger samplerate is a property of the Essence file, but there is currently no CSV export for Essences - unless I've missed it.

Which CSV export are you wanting to add this information to?

**Comment by nthieberger** [comment]
Is there any way of exporting samplerate info for all files, maybe as a
once off for analytical purposes?

**Comment by JonoGillett** [comment]
Just to be clear, because I sometimes find the naming confusing - you would like a list of all essence files in the system which have samplerates?
For example:

filename | samplerate
----------- | ----------------
a.mp3 | 44000
b.wav | 96000

**Comment by JonoGillett** [comment]
I've attached the list of essence files which have sample rates

[Nabu - Essence Sample Rates.pdf](https://github.com/nabu-catalog/nabu/files/50460/Nabu.-.Essence.Sample.Rates.pdf)

**Comment by nthieberger** [comment]
Yes, that's right, thanks

**Comment by nthieberger** [comment]
Hi, please can we get this again, but only or wav files and also including bitrate for the whole collection? So it should have filename, bitrate and samplerate. And can we get it as CSV please.

**Comment by agrimmtt** [comment]
This is really a CSV file, not a .txt file. It's just that GitHub doesn't allow .csv files.

This is all essence objects that have a mimetype of `audio/x-wav`. Let me know if you have any questions.

[wav_file_bitrates_20150122.csv.txt](https://github.com/nabu-catalog/nabu/files/100312/wav_file_bitrates_20150122.csv.txt)
