### ISSUE TITLE
file list for TS1

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#497]
Could we please get a list of all the files now in the TS1 collection, showing sample rates? We need to check that all of these have been resampled and have no way of exporting this data

**Comment by JonoGillett** [comment]
I have attached a listing of all the audio files for the TS1 collection, let me know if you need anything else.

[Nabu - TS1 essence files with sample rate.txt](https://github.com/nabu-catalog/nabu/files/45325/Nabu.-.TS1.essence.files.with.sample.rate.txt)

**Comment by JonoGillett** [comment]
Hi @AmandaPDSC, I'm put the information here so I'm going to close this ticket. If that wasn't what you needed feel free to re-open it.
