### ISSUE TITLE
Basic Search fail

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#500]
I'm searching for "VKS" in item basic search mode and getting the "something went wrong" message. This was working on Friday

**Comment by nthieberger** [comment]
Likewise, this search throws an error:
http://catalog.paradisec.org.au/items/search?utf8=%E2%9C%93&search=149_20

**Comment by nthieberger** [comment]
The VKS search in collections works.

**Comment by agrimmtt** [comment]
Resolved by the deployment made on Monday 4 January.
