### ISSUE TITLE
idiosyncratic error in CLC

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#506]
CLC-PVM027, CLC-PVM017 and CLC-PVM019 cannot be saved once edited. Not sure what is going wrong and haven't tested all of the CLC-PVM items

**Comment by JonoGillett** [comment]
@nthieberger could you tell me what fields you are editing? I was able to change the description of CLC-PVM019 and save it without encountering any issues

**Comment by nthieberger** [comment]
the description field.

**Comment by agrimmtt** [comment]
Resolved by the deployment made on Monday 4 January.
