### ISSUE TITLE
Add a new button to show other items of same language

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#507]
Can we add a new button somewhere near the language fields that says 'See other information in this language' and points to a page that has the following url, but is followed by the three letter code taken from the item's from the 'subject language' field:

http://www.language-archives.org/language/XXX

This will take the user to a page that shows everything in archives for that language

**Comment by agrimmtt** [comment]
So given a page like http://catalog.paradisec.org.au/collections/AC2/items/INSATJ101 , we'll have a line saying the following?

> Subject language(s)	Aceh - ace [See other information in this language](http://www.language-archives.org/language/ace)

Is that what you meant?

**Comment by nthieberger** [comment]
yes that's right

**Comment by agrimmtt** [comment]
The change is now visible on staging, and will be available on production on the next deploy.

* http://144.6.225.96/collections/AC2/items/INSATJ101 shows what a subject language and two content languages looks like
* http://144.6.225.96/collections/AA1 shows what a collection's language looks like
* http://144.6.225.96/collections/AA1/items/001 shows what an item looks like when the collection information mentions languages

**Comment by nthieberger** [comment]
OK, can this button be flush right in the field so it is always lined up straight?

**Comment by agrimmtt** [comment]
How does it look now?

**Comment by nthieberger** [comment]
fine thanks

**Comment by agrimmtt** [comment]
Reopened based on email feedback today.

**Comment by nthieberger** [comment]
this caption is truncated to 'See other information in this' which is not much use. Can the font be smaller so it all fits?

**Comment by AmandaPDSC** [comment]
Just pasting in the issues I sent by email:
could it open the OLAC results in a new window? It takes the user to an external site, so it would be good if it didn't open in the same window.
when there are a large number of languages (as in the collection VKS for example), the buttons look messy and a bit confusing at collection level. Could they be organised into a more orderly table, and maybe not appear at all in the collections snapshot that is visible within items (the box in the RH column of an item showing a summary of collection metadata).

**Comment by nthieberger** [comment]
maybe drop the font size for the button so it is not truncated so easily?

**Comment by agrimmtt** [comment]
@nthieberger @AmandaPDSC we've made it open in a new window, and we're experimenting with not using buttons. How does it look now?

* http://144.6.225.96/collections/AC2/items/INSATJ101 shows what a subject language and two content languages looks like
* http://144.6.225.96/collections/AA1 shows what a collection's language looks like
* http://144.6.225.96/collections/AA1/items/001 shows what an item looks like when the collection information mentions languages

**Comment by nthieberger** [comment]
Looks good thanks

**Comment by AmandaPDSC** [comment]
I agree, looks good

**Comment by agrimmtt** [comment]
This will be fixed on the next deployment of Nabu.
