### ISSUE TITLE
Add a new button to show other items of same language

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#508]
Can we add a new button somewhere near the language fields that says 'See other information in this language' and points to a page that has the following url, but is followed by the three letter code taken from the item's from the 'subject language' field:

http://www.language-archives.org/language/XXX

This will take the user to a page that shows everything in archives for that langage

**Comment by agrimmtt** [comment]
Why has this ticket been closed?

**Comment by nthieberger** [comment]
it duplicates #507

**Comment by agrimmtt** [comment]
:+1:
