### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#510]
Trying to download this file:

http://catalog.paradisec.org.au/collections/WS1/items/Niue/essences/1021229/download

threw an error

**Comment by agrimmtt** [comment]
I've changed it so that it'll give you an error if you try to download a file that doesn't exist.

If you go to http://144.6.225.96/collections/WS1/items/Niue/essences/1021229 , and click on "Download", it'll give you an error flash message that the file is not found.

**Comment by nthieberger** [comment]
But this file does exist. is it because it is a text file that it is not recognised? It should be available for download.

**Comment by nthieberger** [comment]
Sorry, not sure why I closed this issue, it is still a problem

**Comment by agrimmtt** [comment]
http://catalog.paradisec.org.au/collections/WS1/items/Niue now only has one essence, http://catalog.paradisec.org.au/collections/WS1/items/Niue/essences/1070985 , which downloads properly. Do you consider the problem resolved?
