### ISSUE TITLE
language filters have been changed and are now wrong

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#512]
In the Admin/Other entities/Language list the filters for content, subject and collection all contain what looks to be the title of collections. They didn't use to do this so this has somehow crept in.

**Comment by agrimmtt** [comment]
This was the result of #488 "language list is wrong". What filters, if any, do you want there?

**Comment by nthieberger** [comment]
Under both content and subject  it should be language names / codes. Under collections it should be collection identifiers (AK1 etc)

**Comment by agrimmtt** [comment]
> Under both content and subject it should be language names / codes.

If you're on the language page, languages as a filter doesn't make sense.

**Comment by nthieberger** [comment]
ok, so just delete the content and subject filters from that page. The search box gives the ability to filter for language name or code

**Comment by nthieberger** [comment]
similarly, under http://catalog.paradisec.org.au/admin/countries take out countries languages, collection languages, collections and latlon boundary

**Comment by agrimmtt** [comment]
This has been fixed, and can be seen on staging at http://144.6.225.96/admin/countries and http://144.6.225.96/admin/languages . I've also fixed a few pages that had similar problems.
