### ISSUE TITLE
Adding new items - strange behaviour

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#513]
When adding JW1-006 (and two other items) the 'add' button takes you to a 'page not found error'  but if you go back and try again, it saves the page.

**Comment by LindaBarwick** [comment]
We have been having lots of problems with creating items and collections (LB4 collection). It seems to be hanging. Multiple pushes of the "add item" or "add collection" button seem to be needed before it will write. This is currently having a detrimental effect on operations

**Comment by LindaBarwick** [comment]
this seems to be the same as #540
