### ISSUE TITLE
Nabu archiving incorrectly named files

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#519]
We received repeat Cron Daemon messages for the last few days saying that this file had been successfully archived VKS-149_20.jpg, before I realised that it is incorrectly named. I have now renamed it to include the third part of the file name VKS-149_20-A.jpg. But it seems like a bug that it was being successful sent to archive, and that we were receiving messages that this was successful, when it should have been rejected for having the wrong filename.

**Comment by AmandaPDSC** [comment]
I think this is actually about the reports, not about incorrect archiving, so I have changed the title of this issue. It's resulting in a huge number of reports that don't alert us to the fact that the file is failing to send.

**Comment by LindaBarwick** [comment]
CLC-PVM002.mov is an example

**Comment by LindaBarwick** [comment]
http://catalog.paradisec.org.au/collections/DL2/items/036 has multiple items with 4 hyphens

**Comment by LindaBarwick** [comment]
http://catalog.paradisec.org.au/collections/CH3/items/091700WEi

**Comment by LindaBarwick** [comment]
there are 138 files in total

**Comment by LindaBarwick** [comment]
we used to have this functionality of checking for conformant filenames so it's something that we have lost from NABU

**Comment by LindaBarwick** [comment]
here are our filenaming rules http://www.paradisec.org.au/naming.html

**Comment by agrimmtt** [comment]
This ticket has been resolved.
