### ISSUE TITLE
Download failing

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#521]
I just twice downloaded W10-09-A.wav, a 30 minute audio file, but it was only 15 minutes long. Is this a problem with NABU ?

**Comment by JonoGillett** [comment]
@nthieberger from the look of the catalog there is no collection W10, is that definitely the right file? could you post a link to the essence page?

**Comment by nthieberger** [comment]
Sorry! NT10-W09-A.wav

**Comment by agrimmtt** [comment]
I downloaded NT10-W09-A.wav, and OS X gave me metadata of it having a length of 30:35. I downloaded it by going to http://catalog.paradisec.org.au/collections/NT10/items/W09/essences/1011293 and clicking on "Download".

http://catalog.paradisec.org.au/collections/NT10/items/W09 has some essences that are described as having a duration of approximately 13 minutes and 0 seconds. Could you have accidentally downloaded them instead?

**Comment by nthieberger** [comment]
OK, it just worked for me too so could have been the bandwidth I was on at the time
