### ISSUE TITLE
Update RSpec

### ISSUE THREAD

**Issue by agrimmtt** [nabu-catalog/nabu#523]
Update RSpec, if not to 3.x then at least to 2.14 or 2.99.

The gem "transpec" can be used to automate this.

I lose time when I try using RSpec 3.x syntax only for it not to be available on RSpec 2.12.0.

**Comment by nthieberger** [comment]
Has this been done?

**Comment by agrimmtt** [comment]
No it hasn't.

**Comment by enwardy** [comment]
how about now?

**Comment by NickWardPDSC** [comment]
closing as Stale
