### ISSUE TITLE
Sorting by modification date doesn't work

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#524]
In the item list view of a found set of items, there are arrows facilitating sorting of each column. I tried to sort VKS records by modification date to look at the items I have been working on, and it doesn't work at all - modification dates don't seem to appear in any order.

**Comment by agrimmtt** [comment]
This has now been fixed on staging, and is awaiting deployment to production.

http://144.6.225.96/items/search?utf8=%E2%9C%93&search=AC2&per_page=1049&sort=updated_at&direction=asc and http://144.6.225.96/items/search?utf8=%E2%9C%93&search=AC2&per_page=1049&sort=updated_at&direction=asc sort by date, while on production, http://catalog.paradisec.org.au/items/search?per_page=1049&search=AC2&utf8=%E2%9C%93&sort=modification_date&direction=asc and http://catalog.paradisec.org.au/items/search?per_page=1049&search=AC2&utf8=%E2%9C%93&sort=modification_date&direction=desc fail to sort by date

**Comment by AmandaPDSC** [comment]
I'm not sure if the deployment is finished, but I just tested this, and it still didn't work...

**Comment by agrimmtt** [comment]
Try it now.

**Comment by AmandaPDSC** [comment]
yep working now - thanks
