### ISSUE TITLE
Create additional fields in the minimal metadata spreadsheet

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#528]
As per my email of January 6th, can we please add fields that can be imported – roles/names; Dialect; region; original media; data categories, discourse type - but these last two require controlled vocabularies so that may be more difficult, unless it could include a popup menu?

**Comment by nthieberger** [comment]
Please add these fields: roles/names; region; original media; data categories, discourse type, dialect, 'Language as given', region, original media

**Comment by agrimmtt** [comment]
Hi @nthieberger .

I've uploaded the changes on staging. Can you check that it does what you want it to do?

**Comment by agrimmtt** [comment]
Closing ticket as it's been deployed, and I haven't received any reports of it not meeting the requirements.

**Comment by nthieberger** [comment]
I've tried uploading the spreadsheet but it fails with the user Vanuatu
Kaljoral Senta. I have also tried Vanuatu, Kaljoral Senta neither works

**Comment by agrimmtt** [comment]
Hi @nthieberger ,

Assuming there's no privacy issues, can you please email the spreadsheet to me?

**Comment by nthieberger** [comment]
I just tried with 'Nick Thieberger' and it doesn't recognise me as a user

Please create user Nick Thieberger first

ERROR collector does not exist

**Comment by nthieberger** [comment]
Here it is

**Comment by agrimmtt** [comment]
@nthieberger I didn't get anything.

**Comment by agrimmtt** [comment]
@nthieberger You now need to put your surname in cell B10.

**Comment by nthieberger** [comment]
OK, thanks that worked. But then it asks me to create a user for the person
whose name is include with the role of 'speaker'. We allow people to add
new names in NABU without creating them in advance, so the spreadsheet
upload should do the same, although there is then a potential problem of
mismatches between spellings of names. I think we just need to allow the
spreadsheet to create new users if it does not find a match.

**Comment by nthieberger** [comment]
I just tried using the most recent version of the spreadsheet. The upload failed becuase "SUCCESS: 0 items created/updated for collection test
Saved collection test, test
Item 992.0 : Data type oratory not found - Item skipped"

But oratory is listed as a permissable data type.

**Comment by nthieberger** [comment]
When I took out 'oratory' it then still failed to import:
SUCCESS: 0 items created/updated for collection test
Saved collection test, test
WARNING: item 992.0 invalid - skipped
Added items:

**Comment by agrimmtt** [comment]
@nthieberger Can you email me the spreadsheet please? Also, as per http://catalog.paradisec.org.au/admin/data_types and the specification of #592 , oratory is not a valid Data Type.

**Comment by nthieberger** [comment]
Sorry, you are right about oratory. I was just going on the list in the
cell of the spreadsheet which needs to be changed. But even deleting that
item has not helped the spreadsheet to be uploaded. I have sent the version
I attempted to upload by email.

**Comment by agrimmtt** [comment]
@nthieberger Thanks for that spreadsheet. What's happened is that in your xlsx file, 992 is treated as a number, not a string, and the program is interpreting it as the floating point number "992.0", and not finding a match. As a temporary workaround, change the cell type of the cell with "992" in it from "Automatic" to "Text" or "String" or something like that. Do you want me to make the site able to handle such input correctly?

**Comment by nthieberger** [comment]
Yes, I tried making that cell of type 'General' to avoid that problem, but Excel is not easy to wrangle. Since I imagine items with numbers will be comon it would be best if the import knew about them and rendered them with no decimal places.

**Comment by agrimmtt** [comment]
@nthieberger A fix for this issue has been deployed to staging, and will be available on production on the next deploy.

**Comment by agrimmtt** [comment]
This change has been deployed.

**Comment by agrimmtt** [comment]
Reopening because I haven't yet dealt with the 17 July comment about creating new users.

**Comment by agrimmtt** [comment]
@nthieberger If a role doesn't correspond to an existing user, a new user should be created. But if the collector (cells B9 and B10) doesn't correspond to an existing user, should it create a new user, or tell the user that the spreadsheet is invalid? I'm in favour of the latter, so that typos don't create new users with an important role that need to be merged in later on.

**Comment by nthieberger** [comment]
Yes, tell the user it is invalid because the user doesn't yet exist. Thanks.

**Comment by agrimmtt** [comment]
@nthieberger the change for creating new users has been deployed to production. It now creates contact-only users for those involved in roles if they do not already exist.

**Comment by nthieberger** [comment]
After all of this discussion (and work) the upload still fails with the following error:
Item 01 : Data category moving image not found - Item skipped
Item 02 : Data category sound not found - Item skipped

Both are valid categories so can you please fix this?

**Comment by stasb** [comment]
@nthieberger Hi Nick, as per ticket #592, "moving image" and "sound" are no longer data categories. There are data types called "MovingImage" and "Sound".

**Comment by JonoGillett** [comment]
@nthieberger please see the above comment from Stas and let me know if you still have concerns with this ticket.

**Comment by LindaBarwick** [comment]
I think we need to change the instructions on the sheet

**Comment by JonoGillett** [comment]
@LindaBarwick If I recall correctly you folks manage the template mentioned on www.paradisec.org.au/deposit
Are you happy to update the instructions to match the new behaviour, or would you like me to provide some wording for it?

**Comment by LindaBarwick** [comment]
@AmandaPDSC can you please check whether the template description has been amended?

**Comment by nthieberger** [comment]
I've checked the excel doc (now dated 2017) and also changed the date format to make it fit our requirements.

**Comment by enwardy** [comment]
i've successfully uploaded several metadata spreadsheets recently, so I think this is all working ok now
