### ISSUE TITLE
Return to Results bug

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#535]
I just exported a csv file for the CH3 collection and then viewed a few items in the collection, when I clicked the "Return to Results" button, Nabu performed the csv export again instead of performing the search again. The same thing occurs when I click the Items tab at the top. "Return to Results" should only repeat the most recent search, not repeat the most recent action.

**Comment by agrimmtt** [comment]
This has been fixed on staging, and will be fixed on production after the next deploy.
