### ISSUE TITLE
Create an alerts field for downtime

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#539]
We currently have nowhere to display alerts that the catalogue will be down. Intersect are updating a VM this weekend and essence files will be unavailable. Could we add a new field, perhaps in the top bar that appears on every page, that can be updated by administrators (I guess through the dashboard), and where we could enter messages like "Due to routine maintenance this weekend users will be unable to download essence files (audio, video, images). Users can browse metadata as usual."

**Comment by agrimmtt** [comment]
These changes have been deployed to the staging server. You can see an example admin message at http://144.6.225.96/ , and the controls for admin messages are available at http://144.6.225.96/admin/admin_messages

The controls for admin messages are a bit staid and boring and manual. As this is a task that won't be performed often, is it ok that it's like that for the medium term?

**Comment by agrimmtt** [comment]
This has been deployed to production.

**Comment by AmandaPDSC** [comment]
Looks good thanks
