### ISSUE TITLE
Slow saving

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#540]
Intermittent problem of NABU being very slow to save. We think we need to improve NABU performance as per earlier discussions with Terem, maybe splitting functionality into modules?

**Comment by AmandaPDSC** [comment]
Wondering if the issue raised in #506 could be related to this?

**Comment by caratgold** [comment]
http://catalog.paradisec.org.au/collections/CLC/items/MT002/edit

Hit save button then this: 

The catalog.paradisec.org.au page isn’t working

catalog.paradisec.org.au didn’t send any data.
ERR_EMPTY_RESPONSE
Hide details
Reload this webpage
Press the reload button to resubmit the data needed to load the page.

**Comment by caratgold** [comment]
Whilst saving metadata on this entry: http://catalog.paradisec.org.au/collections/CLC/items/MT003

Same as last time: 
The catalog.paradisec.org.au page isn’t working

catalog.paradisec.org.au didn’t send any data.
ERR_EMPTY_RESPONSE
Hide details
Reload this webpage
Press the reload button to resubmit the data needed to load the page.

**Comment by agrimmtt** [comment]
@caratgold Were you trying to submit the same data multiple times per second?

    Started PUT "/collections/CLC/items/MT011" for [IP address] at 2016-03-17 13:54:13 +1100
    Started PUT "/collections/CLC/items/JGA267" for [IP address] at 2016-03-17 14:39:08 +1100
    Started PUT "/collections/CLC/items/JGA267" for [IP address] at 2016-03-17 14:39:09 +1100
    Started PUT "/collections/CLC/items/JGA267" for [IP address] at 2016-03-17 14:40:16 +1100
    Started PUT "/collections/CLC/items/JGA081" for [IP address] at 2016-03-17 15:00:34 +1100
    Started PUT "/collections/CLC/items/JGA081" for [IP address] at 2016-03-17 15:01:43 +1100
    Started PUT "/collections/CLC/items/MT002" for [IP address] at 2016-03-17 15:05:25 +1100
    Started PUT "/collections/CLC/items/MT002" for [IP address] at 2016-03-17 15:05:25 +1100
    Started PUT "/collections/CLC/items/MT002" for [IP address] at 2016-03-17 15:34:35 +1100
    Started PUT "/collections/CLC/items/MT002" for [IP address] at 2016-03-17 15:34:35 +1100
    Started PUT "/collections/CLC/items/MT002" for [IP address] at 2016-03-17 15:34:35 +1100
    Started PUT "/collections/CLC/items/MT003" for [IP address] at 2016-03-17 15:36:56 +1100
    Started PUT "/collections/CLC/items/MT003" for [IP address] at 2016-03-17 16:00:31 +1100
    Started PUT "/collections/CLC/items/MT003" for [IP address] at 2016-03-17 16:00:31 +1100
    Started PUT "/collections/CLC/items/MT003" for [IP address] at 2016-03-17 16:00:33 +1100

If you can wait about five seconds between attempts, that would probably be preferable.

If you didn't submit the same requests multiple times per second, let me know - it might indicate something's wrong.

**Comment by caratgold** [comment]
Yes sorry, it does seem to work sometimes after multiple clicks of 'save' button.

**Comment by caratgold** [comment]
I will refrain and be patient in future. Thanks.

**Comment by caratgold** [comment]
Just now when attempting to save metadata entry for:   http://catalog.paradisec.org.au/collections/CLC/items/MT004

Error was: 

The catalog.paradisec.org.au page isn’t working

catalog.paradisec.org.au didn’t send any data.
ERR_EMPTY_RESPONSE
Hide details
Reload this webpage
Press the reload button to resubmit the data needed to load the page.

**Comment by caratgold** [comment]
Saving entry: http://catalog.paradisec.org.au/collections/CLC/items/MT005
Error: 
The catalog.paradisec.org.au page isn’t working

catalog.paradisec.org.au didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by caratgold** [comment]
Repeating every time i press save.

**Comment by agrimmtt** [comment]
@caratgold with regards to MT004:

According to the records, you visited the edit page at 10:29:13, you looked up a user called nick at about 10:29:50, then someone viewed MT004 at 11:15:16 (possibly you, but with a different IP address), then tried submitting changes at 11:19:38 (the request timed out), then submitted again at 11:24:18, 11:24:19, 11:24:20 (twice). It looks like some of those attempts were successful, and some weren't.

Does this look right?

**Comment by agrimmtt** [comment]
With regards to MT005:

It looks like you successfully submitted changes at 11:54:43, and viewed the page of the updated item the next second, and that you then tried submitting changes at 11:54:48 which timed out.

**Comment by caratgold** [comment]
Yes this is all me, having mixed success.

**Comment by caratgold** [comment]
Just now

Entry: http://catalog.paradisec.org.au/collections/CLC/items/MT007

Error: The catalog.paradisec.org.au page isn’t working

catalog.paradisec.org.au didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by agrimmtt** [comment]
@caratgold That's interesting, I can't see any submissions for MT007. Do you have skype?

**Comment by caratgold** [comment]
Not on this machine but another i do yes.

**Comment by caratgold** [comment]
I'm going to press save once again on MT007 just now.

**Comment by caratgold** [comment]
Same again :( 

"The catalog.paradisec.org.au page isn’t working

catalog.paradisec.org.au didn’t send any data.
ERR_EMPTY_RESPONSE"

**Comment by caratgold** [comment]
Skype name is:    nickgilmore8

**Comment by agrimmtt** [comment]
I've sent a request.

**Comment by agrimmtt** [comment]
I've just visited the Conservatorium and met @caratgold .

A laptop from our office which worked at Terem didn't work when plugged into the ethernet network at the Conservatorium. By contrast, a Conservatorium laptop which didn't work when using the Conservatorium's network started working when tethering from my mobile phone. Nick is planning to discuss internet connection issues with IT.

**Comment by AmandaPDSC** [comment]
It's a bit puzzling, since we don't have other network connection problems that coincide with saving problems. We are also able to browse Nabu fluently but just not save edits consistently. Users have also reported the problem outside of the university campus.

**Comment by agrimmtt** [comment]
@AmandaPDSC Could the people outside the university campus have been VPN-ing into the campus?

Does the error also happen if they try modifying items on the staging server?

**Comment by AmandaPDSC** [comment]
I've just checked with one of our users Petronella and she doesn't seem to have been using VPN when she has had problems saving. She's not someone who tests things on the staging server - I don't think any of us have ever reported issues there.

**Comment by agrimmtt** [comment]
@AmandaPDSC At a time convenient for you, can you (or someone else with the slow saving problem) try editing items on the staging server, and see if you can reproduce the error there?

**Comment by agrimmtt** [comment]
@nthieberger are you able to cause the slow saving problem on the staging server?

**Comment by nthieberger** [comment]
I have tried editing items on the staging server and have no problems

**Comment by AmandaPDSC** [comment]
I have tested saving a number of edits on the staging server this afternoon, with no delays

**Comment by agrimmtt** [comment]
@AmandaPDSC Are you able to get slow saving on the production server?

**Comment by AmandaPDSC** [comment]
is the production server different from the staging server? Can you send me the URL of what you want tested?

**Comment by agrimmtt** [comment]
@AmandaPDSC Sorry, I meant http://catalog.paradisec.org.au/

**Comment by AmandaPDSC** [comment]
I haven't been working on it today, on Tuesday I had a series of errors:
DT1-226, 1.38pm pressed save about 7 times in total, finally saved at 1.41
DT1-279, started saving at 1.57pm, tried to save around 12 times, saved at 14.09
DT1-263, started saving at 2.12, saved at 2.16
DT1-238, added comment only, started saving 2.38, saved after 3 tries 2.39
DT1-046 (adding new item) started saving 2.49, saved after about 20 tries at 2.54

**Comment by AmandaPDSC** [comment]
Sydney ICT have implemented a change to the border security after reviewing the information from Andrew, and the last week of testing suggests that the problem is now resolved
