### ISSUE TITLE
Rif-CS feed

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#547]
Please change this text in the feed from this:
PARADISEC Sydney, Department of Linguistics, second floor Transient Building F12, Fisher Road, The University of Sydney, Camperdown Campus, NSW 2006, AUSTRALIA, Phone: +61 2 9351 2002

to this:
PARADISEC Sydney Unit: Sydney Conservatorium of Music, Rm 3019, Building C41, The University of Sydney, NSW, 2006, Phone +61 2 9351 1279. PARADISEC Melbourne Unit: School of Languages and Linguistics, University of Melbourne, +61 2 8344 8952 | PARADISEC Canberra Unit: College of Asia and the Pacific, The Australian National University, +61 2 6125 6115

**Comment by agrimmtt** [comment]
Should the bit that has `' c/o PARADISEC, Department of Linguistics, The University of Sydney'` be changed?

**Comment by nthieberger** [comment]
I can't see where that appears but, yes, it is out of date so should be replaced with something out of the current contact info. Please end the whole context if you want me to check it.

**Comment by agrimmtt** [comment]
In http://catalog.paradisec.org.au/oai/collection?verb=ListRecords&metadataPrefix=rif , it currently has 

> Alexander Adelaar c/o PARADISEC, Department of Linguistics, The University of Sydney

Shall I change it to

> Alexander Adelaar c/o PARADISEC Sydney Unit, Sydney Conservatorium of Music, The University of Sydney

?

**Comment by nthieberger** [comment]
Any <addressPart type="text"> that includes   a reference to "PARADISEC Sydney, Department of Linguistics, second floor Transient Building F12, Fisher Road, The University of Sydney, Camperdown Campus, NSW 2006, AUSTRALIA, Phone: +61 2 9351 2002" or any part of that, should be changed as per the note above.

Any <addressPart type="text"> that has a depositor name and the old address should never really have been there in the first place
Those entries should be left blank as we do not want any addresses associated with depositors in the feed, and we don't want the PARADISEC address there either.

**Comment by nthieberger** [comment]
And please note that the original issue deals with the Rif-CS feed, NOT the OAI-PMH feed, hence the confusion about 'c/o PARADISEC, Department of Linguistics, The University of Sydney' but they should clearly both be changed.

**Comment by agrimmtt** [comment]
Just to clarify, shall I delete the following portion?

    <physical type="postalAddress">
      <addressPart type="text">
        Alexander Adelaar c/o PARADISEC, Department of Linguistics, The University of Sydney
      </addressPart>
    </physical>

**Comment by nthieberger** [comment]
Yes, I think so. Let's hope it doesn't break our OAI-PMH feed
