### ISSUE TITLE
Add some words to the front page

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#550]
Please add the following words after this paragraph:  "The catalog entry for an item is usually written by the depositor, and some are more detailed than others. In the case of collections that we have digitised from deceased researchers, we do the best we can to describe the records, but often there is little information available. By placing these items in the collection we hope that other researchers will enrich the descriptions as they use the material."

Add:
"We believe the rights in the material presented in this collection have been cleared by the depositors. Please let us know if you think that is not the case for any particular item."

**Comment by agrimmtt** [comment]
http://144.6.225.96/ now has the desired text. This will be pushed to production in the next deploy.
