### ISSUE TITLE
Files failing but archive message says success

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#561]
I have just placed four files in toNabu - all were picked up and I received automated confirmation messages that they were successfully archived, but none have arrived in Nabu. The message received shows a fail right at the bottom, and the files have disappeared from toNabu:

SUCCESS: file CLC-PVM005-01.mov copied into archive at /srv/catalog/CLC/PVM005/
Inspecting file CLC-PVM005-01.mov...
ffprobe version N-76944-g15206ff Copyright (c) 2007-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libdcadec --enable-libfreetype --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvo-aacenc --enable-libvidstab
  libavutil      55.  9.100 / 55.  9.100
  libavcodec     57. 16.101 / 57. 16.101
  libavformat    57. 19.100 / 57. 19.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 17.100 /  6. 17.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x2e9dbc0] moov atom not found
/srv/catalog/CLC/PVM005//CLC-PVM005-01.mov: Invalid data found when processing input
ERROR: unable to process file CLC-PVM005-01.mov - skipping
Error running avprobe, returned pid 32166 exit 1 output: {

}
...done

**Comment by agrimmtt** [comment]
This has been changed to only displaying a message with "SUCCESS" if the entire process of importing a file is successful, as opposed to part of the process.

> SUCCESS: file CLC-PVM005-01.mov copied into archive at /srv/catalog/CLC/PVM005/

will be changed to say

> INFO: file CLC-PVM005-01.mov copied into archive at /srv/catalog/CLC/PVM005/

This change will be be applied on the next deploy.

**Comment by AmandaPDSC** [comment]
In the case of these files they were also moved off Azoulay in this process (but didn't arrive in Nabu). I'm unclear whether it is Nabu or Azoulay that's at fault here.

On 6 May 2016, at 9:58 AM, Andrew Grimm (Terem Technologies account) <notifications@github.com<mailto:notifications@github.com>> wrote:


This has been changed to only displaying a message with "SUCCESS" if the entire process of importing a file is successful, as opposed to part of the process.

SUCCESS: file CLC-PVM005-01.mov copied into archive at /srv/catalog/CLC/PVM005/

will be changed to say

INFO: file CLC-PVM005-01.mov copied into archive at /srv/catalog/CLC/PVM005/

This change will be be applied on the next deploy.

**Comment by agrimmtt** [comment]
@AmandaPDSC the file `/srv/catalog/CLC/PVM005/CLC-PVM005-01.mov` exists:

    deploy@paradisec:/srv/catalog/CLC/PVM005$ ls -l /srv/catalog/CLC/PVM005/CLC-PVM005-01.mov 
    -rw-r--r-- 1 deploy deploy 9755688960 Mar  8 17:02 /srv/catalog/CLC/PVM005/CLC-PVM005-01.mov

However, it isn't listed at http://catalog.paradisec.org.au/collections/CLC/items/PVM005 , because the system couldn't get metadata from the file.

Is this undesired behaviour?

**Comment by AmandaPDSC** [comment]
I'm not sure I understand. The files I mentioned are there now, because after the files I uploaded twice failed, Lauren Booker put them on Azoulay from a different machine and they uploaded successfully. But are you saying that there are multiple versions of these files, including the versions that I uploaded and that failed?

**Comment by agrimmtt** [comment]
@AmandaPDSC can you please ask Lauren where the files are, and the URL for the essence page for the file if an essence was successfully created?

**Comment by AmandaPDSC** [comment]
I see now that Lauren has renamed the files so that the mp4 is called CLC-PVM005-01 and the mov is called CLC-PVM005-02. Whereas the two files I was trying to upload were both called CLC-PVM005-01 with different extensions .mp4 and.mov - could this be causing such uploads to fail? And are you saying the CLC-PVM005-01.mov is in the archive but not showing up in Nabu? What causes the system to fail to get metadata from the file?

**Comment by AmandaPDSC** [comment]
Can there be something in the message that indicates a fail – not just info?

Amanda

**Comment by agrimmtt** [comment]
The message
> ERROR: unable to process file CLC-PVM005-01.mov - skipping

will still be visible

**Comment by AmandaPDSC** [comment]
It would be great to understand what happened with these files that I uploaded twice, and that disappeared. Were you saying that the files are in the archive, but not showing up in Nabu because of some failure to harvest metadata? Has this been resolved by the fixes for this issue?

**Comment by AmandaPDSC** [comment]
Further to this, I've just looked through one of our notifications from yesterday, and the following file has no indication of either success or failure, but yet it seems to now be in Nabu - INFO doesn't really provide us with any useful information unless we know whether the file has been successfully archived or not. Can you advise what we are to interpret from this, and why there is no SUCCESS notification for this file? I don't really see a point in labelling things with INFO - we need to know whether action is required or not, and INFO doesn't seem to tell us that.

INFO: file JB2-006-B.wav copied into archive at /srv/catalog/JB2/006/
Inspecting file JB2-006-B.wav...
ffprobe version N-76944-g15206ff Copyright (c) 2007-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libdcadec --enable-libfreetype --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvo-aacenc --enable-libvidstab
  libavutil      55.  9.100 / 55.  9.100
  libavcodec     57. 16.101 / 57. 16.101
  libavformat    57. 19.100 / 57. 19.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 17.100 /  6. 17.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Input #0, wav, from '/srv/catalog/JB2/006//JB2-006-B.wav':
  Metadata:
    comment         :
                    : Language: "Yanyuwa" jao;
                    : Country: AU;
                    : Notes: [1] story (may 18) 038 drill(17) 089 drill(8) 131 drill(9) shopping 168 story (cooking meat) 193 story (printshop) 211 story (typewriter) 228 Foggdam 295 story (Yarrowanya) 380 story  East Arm 463 story weekend
    encoded_by      : John Bradley
    time_reference  : 0
    umid            : 0x060A2B340101010501010920130000002EDB80DE66131C49B6A7A7FB3BD371D2
    coding_history  : A=PCM,F=96000,W=24,M=stereo,T=AsoAoFPU
                    : A=PCM,F=96000,W=24,M=stereo,T=AsoDoFPU
                    : A=PCM,F=96000,W=24,M=stereo,T=FormatConverterFpu
                    : A=PCM,F=96000,W=24,M=stereo,T=Rewrite FSC
                    : A=PCM,F=96000,W=24,M=stereo,T=DOBBIN (1.0); 2016-05-18; 10:20:11
                    :
  Duration: 00:47:02.45, bitrate: 4608 kb/s
    Stream #0:0: Audio: pcm_s24le ([1][0][0][0] / 0x0001), 96000 Hz, 2 channels, s32 (24 bit), 4608 kb/s
...done

**Comment by agrimmtt** [comment]
@AmandaPDSC 

JB2-006-B.wav's metadata hasn't changed since the last time metadata was generated for it, so neither "SUCCESS" nor "ERROR" is applicable.

Would a new message saying "INFO: file JB2-006-B.wav metadata already exists in Nabu and is unchanged" on a line preceding "...done" be helpful for this situation, to complement the "INFO: file JB2-006-B.wav copied into archive at /srv/catalog/JB2/006/" message at the start?

**Comment by AmandaPDSC** [comment]
Isn't the point of these messages to advise that an actual file has moved from Azoulay to Nabu, not whether the metadata has changed? I check the messages to ensure that files are not getting stuck in the pipeline, or failing to arrive, so if there's been some kind of fail, then I follow it up. My understanding was that SUCCESS indicated that a file had arrived in the archive, and was unrelated to metadata.

**Comment by agrimmtt** [comment]
@AmandaPDSC we haven't dealt with Azoulay before. Do you know who currently handles it?

**Comment by AmandaPDSC** [comment]
Michael Homsey built the new Azoulay server and is providing some ongoing support for troubleshooting any additional issues. I thought Terem had been in contact with him before? So are you saying this is an issue with the way Azoulay is dealing with files?

**Comment by AmandaPDSC** [comment]
I've just had a closer look at these messages and compared them to what they were saying before, and I see now that the metadata import section at the end of each item uses the word SUCCESS, whereas the copy of the file to the archive at the beginning just says INFO. The file copying to the archive is what we're really concerned about. 
Can we get rid of INFO altogether? It's not informative. And restore SUCCESS or FAIL to whether or not the file has copied? ERROR is less useful than FAIL, because the word error appears elsewhere throughout these messages so it makes it difficult to search for failures in file transfer.
(Of course this still doesn't explain what happened to those 4 mov files as the message read "SUCCESS: file CLC-PVM003-02.mov copied into archive at /srv/catalog/CLC/PVM003/" even though the file didn't appear to arrive in Nabu.)

**Comment by agrimmtt** [comment]
Hi @AmandaPDSC ,

If there's a file we want to reject (for example, it doesn't correspond to any collection), but there's a file with the same name in the folder for rejected uploads, what should we do? Is such a scenario possible?

**Comment by AmandaPDSC** [comment]
the scenario seems unlikely to me, but as a general principle the newer file should overwrite the older one. We will sometimes have redigitised or resampled a file and put it through to overwrite an existing file.

**Comment by agrimmtt** [comment]
Hi @AmandaPDSC ,

This ticket is now awaiting deployment.

**Comment by agrimmtt** [comment]
Hi @AmandaPDSC ,

I can see that valid files are being ingested under the current deployment. For example, http://catalog.paradisec.org.au/collections/SUY1/items/160507/essences/1098227

I'm worried that rejected files aren't being moved into a rejected folder. Are you still continuously getting messages like

> ERROR: file WRONG-WRONG-001.tif skipped - not able to read it or write to /srv/nabu/archive_me/Rejected/WRONG-WRONG-001.tif

Or are you now getting messages like

> INFO: file WRONG-WRONG-001.tif copied into rejected file folder at /srv/nabu/archive_me/Rejected/

?

**Comment by AmandaPDSC** [comment]
Here is the most recent error that I can find, from Sunday - but I'm not sure whether that's recent enough for any changes you've implemented?

From: Cron Daemon [mailto:root@paradisec.intersect.org.au] 
Sent: Sunday, 10 July 2016 3:00 AM
To: deploy@paradisec.intersect.org.au
Subject: Cron <deploy@paradisec> if [ ! -f /srv/www/nabu/shared/pids/disable_cron ]; then pgrep -f "[b]in/rake archive:export_metadata" > /dev/null; if [ $? = 1 ]; then export PATH=/home/deploy/.rbenv/shims:/home/deploy/.rbenv/bin:$PATH && eval "$(rbenv init -)...

ERROR: could not find item pid=DWU-Hish_Svd_1 for file DWU-Hish_Svd_1-A.wav - skipping
ERROR: could not find item pid=DWU-Hish_Svd_1 for file DWU-Hish_Svd_1-B.wav - skipping

**Comment by AmandaPDSC** [comment]
It doesn't seem like files are being moved to rejected. See this morning's message below, and the files are still sitting in the same directory.


On 15/07/16 3:00 AM, "Cron Daemon" <root@paradisec.intersect.org.au> wrote:

ERROR: could not find item pid=TS1-N148 for file TS1-N148-A.wav - skipping
ERROR: could not find item pid=DWU-355T9 for file DWU-355T9-A.wav -
skipping
ERROR: could not find item pid=TS1-V9 for file TS1-V9-1.wav - skipping
ERROR: metadata of item pid=TS1-V11 is not complete for file
TS1-V11-1.wav - skipping
ERROR: could not find item pid=TS1-V2 for file TS1-V2-1.wav - skipping
ERROR: could not find item pid=TS1-V6 for file TS1-V6-1.wav - skipping
ERROR: could not find item pid=TS1-V5 for file TS1-V5-1.wav - skipping
ERROR: metadata of item pid=TS1-V13 is not complete for file
TS1-V13-2.wav - skipping
ERROR: metadata of item pid=TS1-V12 is not complete for file
TS1-V12-1.wav - skipping
ERROR: metadata of item pid=TS1-N207 is not complete for file
TS1-N207-B.wav - skipping
ERROR: metadata of item pid=TS1-V13 is not complete for file
TS1-V13-1.wav - skipping
ERROR: metadata of item pid=TS1-V14 is not complete for file
TS1-V14-1.wav - skipping
ERROR: could not find item pid=TS1-V1 for file TS1-V1-1.wav - skipping
ERROR: metadata of item pid=TS1-N207 is not complete for file
TS1-N207-A.wav - skipping
ERROR: could not find item pid=TS1-V8 for file TS1-V8-1.wav - skipping
ERROR: metadata of item pid=DWU-C36 is not complete for file
DWU-C36-A.wav - skipping
ERROR: could not find item pid=TS1-V4 for file TS1-V4-1.wav - skipping
ERROR: could not find item pid=TS1-V7 for file TS1-V7-1.wav - skipping
ERROR: metadata of item pid=TS1-V10 is not complete for file
TS1-V10-1.wav - skipping
ERROR: metadata of item pid=DWU-C36 is not complete for file
DWU-C36-B.wav - skipping
ERROR: could not find item pid=TS1-V3 for file TS1-V3-1.wav - skipping
ERROR: metadata of item pid=TS1-N206 is not complete for file
TS1-N206-1.wav - skipping

**Comment by agrimmtt** [comment]
Hi @AmandaPDSC or anyone else,

I've added an extra debug line to cases like

> ERROR: file WRONG-WRONG-001.tif skipped - not able to read it or write to /srv/nabu/archive_me/Rejected/WRONG-WRONG-001.tif

Which you'll be able to see from 7pm tonight onwards. Can you forward such an email to me?

**Comment by agrimmtt** [comment]
The import process seems to be working properly now.

@AmandaPDSC if you want to change how the export metadata task works, in terms of it also moving rejected files into a "Rejected" folder, please create a new ticket for that, and give it a priority.

**Comment by agrimmtt** [comment]
@AmandaPDSC the debug message will be removed with the next deploy.

**Comment by agrimmtt** [comment]
Deployed. You won't receive any messages beginning with "DEBUG" any more.
