### ISSUE TITLE
Please export a list of audio files

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#570]
Can you please export a list of all audio file names (both wav and mp3) and their lengths in time? We need to find any discrepancies here and identify the cause.

**Comment by AmandaPDSC** [comment]
Would be great if we could make this No.1 priority for the moment

**Comment by agrimmtt** [comment]
@AmandaPDSC I've done some work that will hopefully make it easier to complete ticket #473 and investigate ticket #561 (that's what today's deploy is for). I had also hoped that upgrading the Ruby version would have helped with these tickets, but it didn't.

**Comment by agrimmtt** [comment]
I've sent a list of the files by email just now.
