### ISSUE TITLE
When are checksums checked?

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#571]
Can you please let us know at which point in the file accession the checksum is checked? Files from ANU have checksums from the source. However, we have found a couple of wav/mp3 mismatches in length and so are wondering if the files are actually being checked along the way or not.

**Comment by agrimmtt** [comment]
@nthieberger I haven't checked definitively, but it looks like checksums aren't currently checked. A search of the tickets for "checksum" came up with open tickets #378 "implement checksum checking" and #412 "Checksums". What priority is implementing this?

**Comment by nthieberger** [comment]
We really need to get checksums checked at ingestion, then at transfer and finally on entry into NABU. And we should do random checksumming on the collection every now and then to ensure its integrity

**Comment by stasb** [comment]
@nthieberger the ingestion and transfer currently happen outside of Nabu, so you'll have to speak to whoever is responsible for these components, however we can validate the checksum on entry into Nabu.

- when the data enters Nabu, and a checksum failure is detected, what should happen?
- for regular checksum checking, how often should this be run? Should this be run over all data, or randomly selected bits of data?

**Comment by nthieberger** [comment]
If a checksum fails it should generate a message to admin@paradisec.org.au
informing us of the failure.

Checking should be done on ingestion and then we should probably also run
checks every evening for data integrity. These could work their way through
the collections every night? If they are slow and cpu intensive we probably
don't want them going on for too long, but if they are not then they could
just be running in the background.

Nick

**Comment by nthieberger** [comment]
Thanks for getting checksum reports done. Would it be possible to only report on failed checksums so the report are smaller?

**Comment by stasb** [comment]
@nthieberger yep, I'll change it so it only reports on failed checksums.

**Comment by stasb** [comment]
This feature has been completed and is deployed to production. The regular checksum task is currently not operation, as all cron tasks are currently paused.

**Comment by jodiekell** [comment]
Some recent examples related to the above comment:

8 February 2018 at 13:02
files that failed the checksum:
/srv/catalog/MH2/MELANDAI4/MH2-MELANDAI4-B.wav: FAILED

3 February 2018 at 04:00
files that failed the checksum:
/srv/catalog/MH2/B_ADAT5/MH2-B_ADAT5-B.wav: FAILED open or read
