### ISSUE TITLE
Update to server configuration

### ISSUE THREAD

**Issue by MLR-au** [nabu-catalog/nabu#576]
Im almost ready to release an updated version of the viewer which is significantly different to the current version. Accordingly, we need to do some testing to ensure it behaves as expected. To do this I was wondering if you could make some changes on the server running catalog.paradisec.org.au.

I log in as the user mlarosa which puts me in /srv/www/viewer. In there I can see two folders - master and testing - with "current" as a link to testing. Could you please add another folder "production" in there and update the nginx config so that:

http://catalog.paradisec.org.au/viewer --> /srv/www/viewer/production
http://catalog.paradisec.org.au/test-viewer --> /srv/www/viewer/testing.

In order to not break the viewer when you're making this change it's fine with me if you rename the testing folder to production and then create a new testing folder. I can go in and fix up the git checkouts at some later stage but at least it will keep working in the meantime.

And please ensure my user (mlarosa) owns both of the folders and all of the content.

**Comment by MLR-au** [comment]
I've created a folder `production` in /srv/www/viewer/ and linked `current` to it so now `/viewer` loads the first version of the app which is installed in production.

Could you please update the nginx server config for Nabu (/etc/nginx/sites-enabled/nabu) to also include the following:
```
    location /test-viewer {
      alias /srv/www/viewer/testing;
    }
```

That should be all I need to then install the new version of the app and have it accessible for user testing.

**Comment by MLR-au** [comment]
Hey guys,

Any chance to look at this? I can't show Nick the latest changes until this is done so I'm blocked. Please help!

**Comment by agrimmtt** [comment]
Hi @MLR-au , we work on this project for part of the time rather than every day. We'll address this ticket when it's possible to do so.

**Comment by MLR-au** [comment]
Hi @agrimmtt, I can appreciate that. If you can priotise this small
task I would
be most grateful. Are you able to suggest when the work might happen?

On Friday, 22 April 2016, Andrew Grimm (Terem Technologies account) <
notifications@github.com> wrote:

> Hi @MLR-au <https://github.com/MLR-au> , we work on this project for part
> of the time rather than every day. We'll address this ticket when it's
> possible to do so.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nabu-catalog/nabu/issues/576#issuecomment-213172003>
>


-- 

Marco La Rosa, PhD
email:   m@lr.id.au
phone: +61 401 738 392
skype:  mlr-au

**Comment by agrimmtt** [comment]
@MLR-au I've edited the file `/etc/nginx/sites-enabled/nabu`, though I haven't restarted the web server yet. I'll discuss this with @nthieberger by email.

**Comment by agrimmtt** [comment]
The server was restarted on Wednesday, so this should be resolved now. @MLR-au please re-open if this is not the case.
