### ISSUE TITLE
More file deletions

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#583]
These files have been deleted in NABU, but still exist in the file system:
AW2/01I/
AW2/01II/
AW2/01III/
AW2/01IV/
AW2/01IX/
AW2/01V/
AW2/01VI/
AW2/01VII/
AW2/01VIII/

If the 'Delete Item' function is invoked it should get rid of these files too. I don't want to delete them from the file system in case it causes problems. Can you please advise if I can do that?

**Comment by agrimmtt** [comment]
I've done it for you.
