### ISSUE TITLE
Seeking in audio / video - 206 partial content requests

### ISSUE THREAD

**Issue by MLR-au** [nabu-catalog/nabu#584]
Seeking in HTML5 audio / video requires 206 partial content requests to be supported by the backend web server. If we look in the console of the viewer when seeking we see (extraneous stuff removed for clarity)

- Request
```
Request URL:http://catalog.paradisec.org.au/repository/NT1/98007/NT1-98007-98007A.mp3
Request Method:GET
Status Code:206 Partial Content
Remote Address:192.168.56.103:80

Headers:

--- snip ---
Host:catalog.paradisec.org.au
Range:bytes=17520962-
--- snip ---
```

- Response
```
Response Headers
Accept-Ranges:bytes

--- snip ---

Content-Length:26043862
Content-Range:bytes 17520962-43564823/43564824
Content-Transfer-Encoding:binary
Content-Type:audio/mpeg

--- snip ---

Pragma:no-cache
Server:nginx/1.6.2
Status:206 Partial Content
```

So:
-  a GET on the file occurs with the right status code (206)
- the headers on the GET request specify the starting byte in the RANGE field
- a response is returned with a byte range and encoding

However, the file always plays from the beginning.

I think the issue has to do with the backend ruby on rails app not supporting the byte range request. The console log shows that nginx seems to be configured correctly and is doing the right thing (ie it supports the request). However, the file doesn't get served by nginx directly - it gets served by the rails app.

So - is the rails app sending back the correct byte range and if not, is there a way to access the media file directly via nginx (which would have the nice side benefit of removing some load from the rails app)?

**Comment by nthieberger** [comment]
cf #210

**Comment by MLR-au** [comment]
X-ACCEL-REDIRECT might be the answer. Basically, the rails app tells nginx to serve the media content directly via a header request. A so called internal location is configured that is not directly available to outside users; rather, it's only accessible when the backend app does an internal redirect to it.

See:
http://thedataasylum.com/articles/how-rails-nginx-x-accel-redirect-work-together.html
http://airbladesoftware.com/notes/rails-nginx-x-accel-mapping/

**Comment by agrimmtt** [comment]
Our code didn't fully handle the scenario of partial content. We've fixed the code to do so, and should be working properly now.

If necessary, we can look at X-ACCEL-REDIRECT in the future.

Let me know if there's any problems.

**Comment by MLR-au** [comment]
Hi @agrimmtt - I want to re-open this ticket to say that it's working nicely now - thankyou - but I don't agree that applying the fix in the ruby layer is the best solution if content serving can be securely devolved to nginx.

If X-ACCEL-REDIRECT allows the rails app to hand off media serving to nginx then it seems like an easy speedup to apply to the whole system. Please reconsider this solution as a matter of high priority or help me understand why you believe it's not appropriate.

**Comment by agrimmtt** [comment]
Hi @MLR-au,

I didn't go down the path of using X-ACCEL-REDIRECT because that'd involve dealing with configuring something I'm not familiar with.

The ticket did not explicitly request that X-ACCEL-REDIRECT be used, as opposed to it being a possible solution. I'm not aware of any evidence that serving audio and video files is a performance bottleneck on Nabu.

**Comment by MLR-au** [comment]
Fair point about not requesting a solution via X-ACCEL-REDIRECT. I guess when I wrote the post I wasn't exactly sure whether the issue was in the rails app or somewhere else in the stack so when I read about X-ACCEL-REDIRECT it seemed to me to be a good way to leave the content serving to nginx so as to free up the rails app for everything else.

To that end, I don't think it's a question of whether content serving is a performance bottleneck. This is more about delegating tasks from the rails app so that it doesn't have to do everything. I know nginx is highly performant at serving content so why not let it handle that task? Indeed it's best practice to have the app server handle the dynamic things and the webserver handle the serving of static things - which in this case should include serving audio / video blobs.

I don't have root access on that server so I can't look at the configuration for you. It seems straightforward enough to me so perhaps this can be assigned to another in your team?
