### ISSUE TITLE
Navigate found items

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#587]
We would like to be able to scroll through a list of search results using the next and previous buttons - currently if we view an item returned in a search and then click next, we get the next record in Nabu, not necessarily the next item from the most recent search.

**Comment by nthieberger** [comment]
I searched DT1 and got a found set. At  DT1-007 the 'next' button took me to DT1-254, not DT1-013. And ths 'return to results' button takes me to ne search, having lost the results.

**Comment by enwardy** [comment]
I believe this is now how the search results navigation ('next' , 'previous' ) now works. Please re-open if I'm mistaken
