### ISSUE TITLE
Search for 'not'

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#588]
ability to find 'not' something

**Comment by baristuncay** [comment]
Dupe of https://github.com/nabu-catalog/nabu/issues/589 ?

**Comment by AmandaPDSC** [comment]
This is particularly relevant for the true/false searches. For example as search on ASMPI collection for 'metadata ready' true - produces 215 results, but false produces none, even though there are 242 items in the collection. A false search should produce results where yes is not ticked for 'metadata ready'

**Comment by JonoGillett** [comment]
The above 'metadata ready' difference is potentially related to the issue mentioned in #633
