### ISSUE TITLE
Invert searches, modify found sets

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#589]
It would be great to be able to invert searches, remove some items from a search, add two searches together etc. Referenced in the thread for #106

The issue is really that we can't create search sets, and then add and subtract things to/from the set. Is there a way to do this without completely overhauling the way the data is stored and searched?

We have a collection that needs to have certain text appended to the comments field, but only for a subset of that collection. At present we have no way of doing so, thus we have to edit each record individually.

**Comment by baristuncay** [comment]
Dupe of https://github.com/nabu-catalog/nabu/issues/588 ?

**Comment by nthieberger** [comment]
We need both 588 and 589 resolved so that searches and working with found sets can be more efficient

**Comment by nthieberger** [comment]
Once we are more adept at using the new finding system we can revisit the possibility of merging and inverting found sets

**Comment by JonoGillett** [comment]
The ability to remove individual results from a found result set has already been deployed.
