### ISSUE TITLE
bulk edit of large number of items fails

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#591]
I searched on mime type "xwav" and tried to bulk edit the c. 7000 results by appending a single value in the data category field. The edit timed out. We need to be able to bulk edit large data sets.

**Comment by agrimmtt** [comment]
Hi @AmandaPDSC ,

Should I give this top priority because of the prize application?

**Comment by AmandaPDSC** [comment]
yes please give top priority

**Comment by agrimmtt** [comment]
Hi @AmandaPDSC ,

This has been deployed and should be fixed. Let me know if you have any problems.

**Comment by LindaBarwick** [comment]
Just tried that huge update, and got the "We're sorry, but something went wrong." message.

I will try again with smaller numbers

Linda

**Comment by AmandaPDSC** [comment]
Andrew,

Smaller bulk edits (but still 1000-2000 items) were working when I was doing this yesterday. Only the 7000 one was failing..

Amanda

Sent from my iPad

On 1 Jul 2016, at 6:45 PM, Andrew Grimm (Terem Technologies account) <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #591<https://github.com/nabu-catalog/nabu/issues/591>.

**Comment by LindaBarwick** [comment]
I have been targeting the larger collections that had no DCMI sound tags (diagnosed by a spreadsheet download of 2000 odd items (from the 7000), and have updated about 1000 of them in dribs and drabs with no apparent problems. it was only the very large update that failed.

linda

**Comment by agrimmtt** [comment]
Removing "Urgent (#1)" as per email thread "Nabu deployment 4 July".

**Comment by nthieberger** [comment]
I just tried again, updating 118 items and it failed.

**Comment by AmandaPDSC** [comment]
I just tried updating 242 items in ASMPI collection and it failed - "something went wrong"

**Comment by nthieberger** [comment]
yes, I searched for ASMPI with 'ready for metadata export' as true and found 120 of 242, but searching for the same with 'false' found zero, but should have found 122.

**Comment by nthieberger** [comment]
This is making it difficult to process audio files. I tried updating 63 TS1-X files and it threw an error.

**Comment by AmandaPDSC** [comment]
Yes it would be good if it could be a high priority fix, as it's preventing us from processing files

**Comment by nthieberger** [comment]
This is still a serious problem, can you please work on it now?

**Comment by JonoGillett** [comment]
I'll make it my top priority when working on Nabu

**Comment by JonoGillett** [comment]
@nthieberger @AmandaPDSC would it be ok if we moved the bulk updates to a background process which then emailed you the results on completion (including any files which failed to update)?

Or would this be problematic because you rely on an immediate response from this task?

**Comment by nthieberger** [comment]
Jono,

Is there some benefit to doing this from your perspective? Typically I
think we would like an immediate response, but if it is going to be a more
robust process done in the background we may be able to live with it. Could
it be backgrounded for large updates (maybe >100 records?) but not for
smaller ones?

Nick

**Comment by nthieberger** [comment]
Jono, whatever is going to work, please do go ahead. I just tried updating 1800 items and it failed. This then stops the files getting ingested as the 'ready for metadata export' tab is not checked.

**Comment by nthieberger** [comment]
I bulk updated GS02 to be not private a few hours ago but nothing has changed.

**Comment by nthieberger** [comment]
ok, seems to be fixed, thanks

**Comment by jodiekell** [comment]
Bulk edit does not work. I tried bulk edit on CLC-PVM files last week on Thursday 25th and again today. I get the message on the screen saying "items will be updated shortly, you'll be notified once it's completed", but then nothing happens, no notification, no edits completed.

**Comment by nthieberger** [comment]
I just did a bulk update and it worked and I received the notification. Have you checked your spam folder?

**Comment by jodiekell** [comment]
I just received notification at 3:29pm that all of the bulk item updates have been completed so this problem is now solved.

**Comment by AmandaPDSC** [comment]
bulk edits are not working - no confirmation message is received and the edits are not carried out

**Comment by agrimmtt** [comment]
@AmandaPDSC Did this problem occur recently before the reboot?

**Comment by AmandaPDSC** [comment]
We noticed it was not working on 11 July. It had been working as late as 8 July

**Comment by agrimmtt** [comment]
@AmandaPDSC The problem was caused by "delayed_job", which is responsible for handling tasks which aren't done immediately, not running. I've now got the backlog of tasks processed. Can you please confirm that the previous bulk edits have now been done, and that for new bulk edits, the confirmation message is received and that the edits are carried out?

If this is a persistent problem, I could add the ability for admins to be able to see how many un-processed tasks there are, either in http://catalog.paradisec.org.au/admin or via a dedicated interface which can also show the details of the un-processed tasks. Do you want me to do this?

**Comment by AmandaPDSC** [comment]
The recent bulk edit I performed seems now to have worked @nthieberger and @enwardy can you check whether yours have now been successsful?

**Comment by nthieberger** [comment]
Yes mine too.

**Comment by AmandaPDSC** [comment]
#667 - the planned process monitor should address this issue as well
