### ISSUE TITLE
OAI feed

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#593]
Our OAI-PMH feed is ok for OLAC, but we want to register with OAI as well and their validation process is more stringent. Could you please have a look at the results (below) and advise if it is a big job to tweak the feed to still keep OLAC validity and then to allow us to register with the OAI?

Thanks,

Nick

---------- Forwarded message ----------
From: Apache apache@victoria01.serverfarm.cornell.edu
Date: 6 January 2016 at 13:58
Subject: OAI Validation (step 2): http://catalog.paradisec.org.au/oai/item
To: thien@unimelb.edu.au

We received a request to validate (but not register) the following repository:

Base URL: http://catalog.paradisec.org.au/oai/item
adminEmail: thien@unimelb.edu.au

Complete log available at
http://www.openarchives.org/Register/ValidateSite?log=27549

..............................................................................

Unfortunately your repository did not validate at version 2.0 of the OAI-PMH
according to our OAI protocol conformance tester. The errors received during
testing are listed below.

[Warning] Bad response to
http://catalog.paradisec.org.au/oai/item?verb=GetRecord&identifier=invalid"id&metadataPrefix=oai_dc
Server gave HTTP status code 500

[1] Can't parse malformed response. An XML parsing error may be due to
incorrectly including the invalid identifier in the &lt;request&gt; element of
your XML error response; only valid arguments should be included. A response
that includes &lt;request verb=&quot;GetRecord&quot;
identifier=&quot;invalid&quot;id&quot;
metadataPrefix=&quot;oai_dc&quot;&gt;..baseURL..&lt;/request&gt; is not
well-formed XML because of the quotation mark (&quot;) in the identifier.

[2] Response to this request did not give error code 'badArgument':
verb=ListIdentifiers&until=junk

[3] Response to this request did not give error code 'badArgument':
verb=ListIdentifiers&from=junk

[4] Response to this request did not give error code 'badArgument':
verb=ListRecords&metadataPrefix=oai_dc&from=junk

[5] Response to this request did not give error code 'badArgument':
verb=ListRecords&metadataPrefix=oai_dc&until=junk

[Warning] Only 8 out of 13 error requests properly handled

[6] Error code badArgument should be given to the request:
verb=ListRecords&metadataPrefix=oai_dc&from=2002-02-05&until=2002-02-06T05:35:00Z
The request has different granularities for the from and until parameters.

SUMMARY:

Total exceptions improperly handled: 6 out of 15
Total error count: 6

**Comment by agrimmtt** [comment]
@nthieberger is it ok if I work on this as part of my work on the high-priority Issue #592 "Add new fields and controlled vocabs"? The approach I'd like to take is the following:

* Fix validation for OAI.
* Ensure that OLAC is still valid.
* Add DCMI type field "Data type". (Much of this work has been done, but not merged in)
* Ensure that OLAC is still valid with the addition of "Data type".
* If applicable (I'm not sure if it's relevant or not), check that the addition of "Data type" hasn't broken validation for OAI.

**Comment by nthieberger** [comment]
Yes, please go ahead,

Nick

**Comment by agrimmtt** [comment]
I had a look, and it looks like fixing the output for OAI will be a non-trivial task.

**Comment by stasb** [comment]
This fix is completed and deployed to production.
