### ISSUE TITLE
Generate noisevis images for all mp3 files

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#595]
Use the noisevis routine (emailed to Terem) to create a json or html file (please liaise with Marco LaRosa about how this can best be integrated into the viewer) and we can then store the image with the following naming convention:

SAW2-009-A-spectrum-PDSC_ADMIN.jpg
[filename]-spectrum-PDSC_ADMIN.jpg

The other file may have to have a name like:
[filename]-json-PDSC_ADMIN.jpg

The image will align with the slider to allow users to jump to any location in the audio file.

**Comment by agrimmtt** [comment]
This ticket is dependent on #599 "Request for item specific data endpoint".

**Comment by agrimmtt** [comment]
This ticket is awaiting feedback from @MLR-au .

**Comment by MLR-au** [comment]
HI all, apologies for the silence; far too many projects on the go.

I don't understand why this ticket is dependent on #599. The data endpoint the viewer will eventually use has nothing to do with the noisevis files other than they will be referenced in the data endpoint.

Accordingly, generation of the noisevis files for all of the mp3 files in the catalog does need to wait for me.

**Comment by JonoGillett** [comment]
@MLR-au not sure how these got linked, but you're right this should be able to continue without you're input.

I've run some checks on files in the collection and I can't find any set of parameters which fix the black image files. Without knowing what the noisevis app is doing there isn't anything else we can do.

@nthieberger How do you want us to proceed? I can update the job to include the parameters you provided us on the 7th of September however, as you mentioned, that will still produce black images.

For reference the parameters were:
> ./noisevis_mac -i BP2-94T2-A.wav -o BP2-94T2-ATES.png -p -s 255,255,255 -m0,0,255 -e 255,0,0 t0.3 -v false
_And I believe the 't0.3' should probably be '-t0.3', so I'm not sure if that's being applied_

**Comment by nthieberger** [comment]
I tried this locally and it all works fine (but needs to run on wav files I think rather than mp3 files). I've included the parameters documentation here.
[noise_spectrum_visualisation_parameters.pdf](https://github.com/nabu-catalog/nabu/files/568185/noise_spectrum_visualisation_parameters.pdf)

For instance, the following parameters produced a good image:
./noisevis_mac -i /Users/thien/Downloads/noisevis_working/IG1-006-A.wav -o /Users/thien/Downloads/noisevis_working/Test.png –p –v false –sc 0,0,0 –s 455,255,255 –m 0,0,655 –e 855,0,0 –t 0.8 

./noisevis_mac -i IG1-006-A.wav -o /Users/thien/Downloads/noisevis_working/Test2.png –v false –s 355,100,200 –m 0,0,555 –e 655,655,655 –t 0.3 –p –sc 0,0,0

**Comment by JonoGillett** [comment]
@nthieberger those parameters still produce black images from some mp3s. For example the previous test case was BP2-94T2-A.mp3 and that still fails. However the associated WAV file works but produces 2 waveforms.

The noisevis application returns some errors while running on files which produce the black image. Presumably the file has some metadata issues.
```
Noise spectrum visualisation for language archives
Copyright (c) 2015 Fraunhofer IAIS

[mp3 @ 0x3409440] Incorrect BOM value
[mp3 @ 0x3409440] Error reading frame TXXX, skipped
[mp3 @ 0x3409440] Skipping 0 bytes of junk at 2007.
[mp3 @ 0x3409440] Estimating duration from bitrate, this may be inaccurate
```

**Comment by nthieberger** [comment]
Yes, this needs to run on wav files it seems, not mp3. We may be stuck with two images and can get the navigator to run withthem if necessary. I have asked the noisevis developers for help but they are not responding.

**Comment by nthieberger** [comment]
This routine will work if you can first convert each stereo file to a mono file (with ffmpeg perhaps?) and maybe downsample to 48khz to save on processing time, and then run noisevis over the output file to generate a single image.

**Comment by stasb** [comment]
@nthieberger Hi Nick, I am trying to use this library locally however I keep experiencing errors when trying to process any wav files. Would you be able to email me the latest version of noisevis, and also please provide me your OSX version that you had when successfully running noisevis_mac locally on your machine?

**Comment by nthieberger** [comment]
Hi, the implementation of this viewer of audio files is a KPI of a current project that will end soon so we really need to get it implemented. Can you please add this to the current urgent priorities.

**Comment by nthieberger** [comment]
Given that it seems to be a problem to get noisevis working, can we perhaps aim to incorporate wavesurfer (js) and to allow proper HTML5 seeking of media so that the user does not have to donload the whole file (for mp3 delivery online). To seek to a particular fragment of HTML5 audio, append #t=starttime,endtime to the ULR. Here's an example:

http://kenhale.kaytetye.com.au/system/media_item/media/3/audio.mp3#t=450,453

This is the W3C Recommendation doc: https://www.w3.org/TR/media-frags/

**Comment by nthieberger** [comment]
This one http://wavesurfer-js.org/example/elan/?scroll

**Comment by nthieberger** [comment]
The intent of this issue is to provide a visual cue to content in an audio file. If that can be done by using an off-the-shelf algorithm , like wavesurfer, thane that may be better. And we can then delete all noisevis items in the collection

**Comment by johnf** [comment]
@nthieberger Based on this issue can I assume all the noisevis code is redundant and I can remove it in favour of using a better mechanism like wavesurfer at some stage?

**Comment by nthieberger** [comment]
Yes, noisevis is not required, thanks

**Comment by johnf** [comment]
@nthieberger Can I also confirm that I should delete all the spectrum files

e.g.
./MD5/H119716/MD5-H119716-A-spectrum-PDSC_ADMIN.json
./MD5/H119716/MD5-H119716-B-spectrum-PDSC_ADMIN.jpg

**Comment by nthieberger** [comment]
Yes, they can be deleted
