### ISSUE TITLE
Move files to Rejected if export metadata task fails

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#597]
This concerns files in the forDobbin folder where the metadata task fails for some reason (metadata incomplete or matching metadata not found for example)

**Comment by agrimmtt** [comment]
@AmandaPDSC can you please specify the full path of the "forDobbin" folder?

**Comment by AmandaPDSC** [comment]
parapd00470.srv.sydney.edu.au/Processing Area/forDobbin

**Comment by agrimmtt** [comment]
This change has been deployed.
