### ISSUE TITLE
Request for item specific data endpoint

### ISSUE THREAD

**Issue by MLR-au** [nabu-catalog/nabu#599]
@nthieberger @agrimmtt @JonoGillett 

A recurring theme with Nabu seems to be the addition of 'extra' things to items that are
hidden from view by being tagged with PDSC_ADMIN. Whilst these extra bits don't make
sense to the user, they are required by the viewer (consider image thumbnails, audio spectra
etc).

Although the viewer handles these extra things well enough, there's no escaping the fact
that it's only a guess as to whether they actually exist for any given item and when they don't,
the user experience is less than ideal. As an example, consider missing thumbnails or the fact
that the viewer can't tell if the user is even logged in or not.

As a potential remedy to these problem may I ask what would be involved in creating an item 
specific data feed?

For example, given an item:
http://catalog.paradisec.org.au/collections/NT1/items/98007

Navigating to:
http://catalog.paradisec.org.au/collections/NT1/items/98007/data.json

--> would produce a JSON object with all of the data known for that item. 

If this route required a valid login in order to access it the viewer could redirect the 
user to the login page on a 401 unauth immediately mitigating one major issue (https://github.com/MLR-au/pdsc-collection-viewer/issues/11).

If you open the browser console in the viewer and look for 'ParadisecService: getItem response'
you'll see the JSON object the viewer constructs from the OAI XML feed and the various XML
files it discovers in the feed. If Nabu were able to generate something like that not only 
would it simplify the viewer but it would enable the viewer to render only what is required 
as it would know what's actually available.

If you think this is possible then reach out so I can tell you the things in that data structure you 
don't need to reproduce.

Thoughts?

Marco

**Comment by agrimmtt** [comment]
@MLR-au 

That sounds good. We'll look into whether it'll be http://catalog.paradisec.org.au/collections/NT1/items/98007/data.json or a slightly different path, but this approach looks fine.

**Comment by MLR-au** [comment]
Great! Get in touch before you start creating the feed so I can give you an overview of what the viewer does to create that data structure.

At the very least I can point you at the code I've written to transform the various XML sources into JSON data structures. This last bit is really important - there are a number of interlinear and transcription data formats that the viewer converts from XML to JSON before transforming them into the data structure you see in the console.

**Comment by nthieberger** [comment]
Is this ready to go? Andrew, do you need any more information from Marco?

**Comment by agrimmtt** [comment]
This is awaiting feedback from @MLR-au .
