### ISSUE TITLE
Search fail for partial filename CLC-R

### ISSUE THREAD

**Issue by LindaBarwick** [nabu-catalog/nabu#601]
In the CLC collection (private), we are not able to successfully search on items with partial filename CLC-R - in advanced search it returns no items, and in standard search it returns only 8 (2 of which do not actually have that in the item name)

when searching the same collection for other partial filenames the search works, strangely it seems only to affect this subset
<img width="1117" alt="basicsearch" src="https://cloud.githubusercontent.com/assets/904300/18463400/24245330-79cd-11e6-9fde-5f18ae3bce7c.png">
<img width="1148" alt="advancedsearch" src="https://cloud.githubusercontent.com/assets/904300/18463401/2425d58e-79cd-11e6-979b-1b26d8157b1b.png">

**Comment by stasb** [comment]
@LindaBarwick Hi Linda, I have just modified how search works on Nabu, which should solve the problems you have experienced. Could you please try it out on staging (http://144.6.225.96/), and let me know if search now behaves in an acceptable way.

**Comment by nthieberger** [comment]
Looks good thanks.

**Comment by stasb** [comment]
This is now deployed and working in production.
