### ISSUE TITLE
Password reset not always working, can we allow admins to reset passwords?

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#602]
Some users say they do not receive password update information so it is probably going to their spam filter. Can we add functionality to allow admins to type in a new password for users for cases like these?

**Comment by JonoGillett** [comment]
@nthieberger I have deployed a version of this to staging, please take a look and let me know if it works for you. The password reset is available as a button in the top right on the view/edit pages of the user admin (e.g. http://144.6.225.96/admin/users/3330)
It takes you to a simple form with new password and confirmation which then updates the user's password.

Question: Currently an admin user can edit the password of any user in the system - do you want any security around this e.g. you can't change other admin passwords?

**Comment by JonoGillett** [comment]
Released on 08/02/17
