### ISSUE TITLE
Quote to improve metadata fields of Collector & Country

### ISSUE THREAD

**Issue by enwardy** [nabu-catalog/nabu#604]
Could Terem please quote PARADISEC on:

- adding an attribute of 'collector' to the user table as a new checkbox that can be searched from the Admin area 
- adding a field that allows a narrative about each user (=collector) to be added
- amending the two feeds to allow export of that narrative field
- adding one or two additional 'Party Identifier' fields for a Collector, for different types of party identifiers (e.g. NLA, ORCID)
- adding a link next to each entry in the 'Country' field similar to the "See other information in this language" link next to each language in the 'Languages' field.

**Comment by enwardy** [comment]
we still need to get this costed as a whole, but I will also now make individual Issue tickets for each of the separate tasks so they can be kept distinct from each other in discussions.

**Comment by AmandaPDSC** [comment]
Re: "adding a field that allows a narrative about each user (=collector) to be added" - we need to clarify where this field would be situated. One suggestion is that the current "find similar" link next to collector (which goes to a Google search and is not that useful for lesser-known collectors) - could instead go to a page with a short bio and direct links to further information (put together by us). This would have to be different to the current user pages - as only administrators can see those

**Comment by enwardy** [comment]
quote for this specific workset no longer required
