### ISSUE TITLE
adding an attribute of 'collector' to the user table

### ISSUE THREAD

**Issue by enwardy** [nabu-catalog/nabu#605]
which can be searched from the Admin area

this could be as a checkbox or a true/false field.

**Comment by JonoGillett** [comment]
@enwardy is the expectation that this field be automatically derived from the existing data?

**Comment by JonoGillett** [comment]
@enwardy Please check out the user admin on staging (http://144.6.225.96/admin/users) to see the current approach. For now I've derived the flag based on whether the user appears in any collection/item 'collector' field - *Note: this was done as a one-time job, future users will not be automatically set as collectors*
You can also manually edit this from the user edit view of the admin dashboard.

To list all collectors in the system select the 'Collectors' tab at the top of the Users list or use the checkbox in the right-hand filters box.

Question: do you expect that a user's 'collector' flag should automatically update as they are added/removed from the 'collector' field of collections or items?

**Comment by enwardy** [comment]
seems good Thanks. 

I can't see a checkbox for 'Collector' in the right-hand filters box, only ones for 'Contact only' and 'Admin'.

To answer your question: I suppose that would be ideal if it could automatically update. Is it much more complicated?

**Comment by JonoGillett** [comment]
@enwardy it's definitely doable. obviously more complicated than not doing it, but if it's going to be beneficial then that's no issue.

Another question: if the collector field in a Collection is updated, should that change affect the Items in that Collection, or are they independent?

For example given existing state:
- XX1 has collector Jono
- XX1-001 has collector Jono
- Jono has collector flag set to true
- Fred has collector flag set to false
After a change:
- XX1 collector changed to Fred
The state will be as follows:
- XX1 will have collector Fred
- XX1-001 will still have collector Jono
- Jono will still have collector flag set to true
- Fred will have collector flag set to true

Does that make sense, or should the collector details of items also update when a collection is updated?

**Comment by JonoGillett** [comment]
This was released on 08/02/17.
If the collection->item collector field update is desired please feel free to re-open.

**Comment by nthieberger** [comment]
Yes, we want to be able to have more than one collector, so do we do it this way, or can we allow >1 collector in the collection?

**Comment by AmandaPDSC** [comment]
covered by #306 - closing
