### ISSUE TITLE
Lag in recognising new items/collections

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#611]
I added a new collection (ZM1) and then tried to upload a metadata file into it, but it is not recognised. It also gives me a strange error message: "ERROR: Not a new collection ZM1 - can't overwrite. " I cannot find the collection in a search. I expect I have to wait for it to be indexed, does that happen together with the cronjob, that is, every hour?

**Comment by nthieberger** [comment]
Can it re-index after creation of new items and collections please

**Comment by JonoGillett** [comment]
This has been deployed into production - please let me know if it still seems to be slow.

**Comment by enwardy** [comment]
i think it's ok now. please re-open if not
