### ISSUE TITLE
problem editing language map co-ordinates

### ISSUE THREAD

**Issue by enwardy** [nabu-catalog/nabu#612]
I edited the map co-ordinates in a language record in Nabu admin and saved it, but now when I go in to a Collection or Item try to "set map from language" for that language (which was Tok Pisin) it tells me there is No matching map data found from language.

**Comment by nthieberger** [comment]
This was meant to have been fixed by Andrew #577

**Comment by enwardy** [comment]
seems to be working now. closing this issue
