### ISSUE TITLE
generate spreadsheet reporting discrepancies in duration wav/mp3

### ISSUE THREAD

**Issue by LindaBarwick** [nabu-catalog/nabu#616]
We are trying to figure out whether we have an issue with our audio processing and need a list of all wav and mp3 files across the collection with bitlength, duration, mono/stereo, date created, DOI, operator. Some durations may be miscalculated as per bug report #615

**Comment by LindaBarwick** [comment]
any progress with this @JonoGillett ?

**Comment by LindaBarwick** [comment]
@JonoGillett any progress please?

**Comment by JonoGillett** [comment]
Apologies Linda, I started this last week but it has been having issues due to (I assume) the tiered filesystem thing. About every third file I try and inspect the metadata of takes ages.

**Comment by AmandaPDSC** [comment]
please try this again now that Intersect have made the files available online

**Comment by LindaBarwick** [comment]
@JonoGillett can you please try to run this report again?

**Comment by j03w** [comment]
From my understanding the CSV export is base on information stored in the database which got recorded at the time the media file got processed. Since the information stored is wrong the export will always be wrong regardless of how many time you try to export it.
Apply new patch to ffmpeg as suggested on #615 might potentially fix the issue for new imports

**Comment by j03w** [comment]
Apologies for my last comment I didn't know what version of ffprobe we are using and just assumed that it's old version. 

Either way after more investigation I'd like to conclude that this is not an issue on `nabu` but the system that actually process the audio files. The wave files actually got cut to the length reported through `nabu`.

If there's nothing more we can do I might close this off.

@LindaBarwick @JonoGillett
