### ISSUE TITLE
sort by countries in basic search results

### ISSUE THREAD

**Issue by LindaBarwick** [nabu-catalog/nabu#617]
![image](https://cloud.githubusercontent.com/assets/904300/24638096/29e125fe-1929-11e7-8e62-4337dc84097a.png)
It would be useful to be able to sort by country n basic search view, as can be done for the fields ID, title, Collector, Language as given, Modification date

**Comment by JonoGillett** [comment]
Countries and Languages of Collections are now sortable.
Countries of Items are now sortable.

This has been deployed into staging, please take a look and see if it meets your needs.

**Comment by JonoGillett** [comment]
This has been deployed into production

**Comment by enwardy** [comment]
looks good, thanks
