### ISSUE TITLE
update Ruby and Rails

### ISSUE THREAD

**Issue by LindaBarwick** [nabu-catalog/nabu#620]
as discussed in today's meeting - @JonoGillett please provide time estimate

**Comment by AmandaPDSC** [comment]
@JonoGillett I think we need you to advise whether this is high priority. If not, can you downgrade the urgency?

**Comment by JonoGillett** [comment]
This is worth doing - as discussed it can probably happen in combination with migrating to the new infrastructure. E.g create a new staging server with updated versions of things and test in parallel with current staging.

**Comment by enwardy** [comment]
ok. we're happy to wait until we are migrating to the new Sydney Uni infrastructure. But that might not happen for 1 year (+?). So it is ok for this update to Ruby and Rails to wait that long? @JonoGillett

**Comment by nthieberger** [comment]
Now being undertaken
