### ISSUE TITLE
handling import of files with same name as existing file

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#621]
To avoid importing duplicate files (and creating a doi problem) we need to checksum files with the same name as an existing file (so a check for duplicate filenames needs to be done when a file is about to be ingested). If it is the same then the file is put into a new folder 'DuplicateFilesRejected" . It the checksums are different then we assume the new file is an improvement and we import it, but generate a list of the doi of the overwritten file that has to be deactivated. This list can be incremetally added to and stored as a file in a folder on Azoulay called "DoiToBeDeactivated"

**Comment by AmandaPDSC** [comment]
@nthieberger  is this solved now by #623 ?

**Comment by nthieberger** [comment]
yes, it looks good
