### ISSUE TITLE
API for all items

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#622]
Jono said some work had been done to create a feed for all items (not just non-private items as in the OAI-PMH feed) so can that be finalised please?

**Comment by JonoGillett** [comment]
There is an API which could be consumed by the Viewer located at `http://catalog.paradisec.org.au/collections/<Collection Identifier>/items/<Item Identifier>/data.json`
e.g.
`http://catalog.paradisec.org.au/collections/LB1/items/KOMEDYA/data.json`

This returns a JSON object containing all the details requested previously my Marco for use in the viewer.

@nthieberger is Marco available to verify that this data meets his requirements?

**Comment by JonoGillett** [comment]
This has been deployed into production

**Comment by nthieberger** [comment]
It seems that the following non-private collections are not being exposed via the RiF CS feed, but they should be
AN1
AU1
CH4
CHA1
DH2
DN1
EF1
EP2
External
GB01
GB02
GB03
GB04
GB05
GB06
GB07
GB08
GB09
GB10
GB11
GB12
GB13
GB14
GB15
GB16
GB17
GB18
GB19
GB20
GB21
GB22
GB23
GB24
GB25
GB26
GB27
GB28
GB29
GB30
GB31
GB32
GB33
GB34
GB35
GB36
GB37
GB38
GB39
GB40
GB41
GB42
GB43
GB44
GB45
GB46
GB47
GB48
GB49
GB50
IG1
IG2
IG3
IG4
IG5
IG6
IG7
IG8
IG9
JHER
JM5
JV1
JW2
KK1
LAN1
LSNG02
LSNG03
LSNG04
LSNG05
LSNG07
MAR1
MW1
MW2
MW3
MW4
RCSB1
SD1
TANI
TG1
TG2
VKS
ZF1
