### ISSUE TITLE
Date and time needed in activity log

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#624]
In the admin area, neither the activity log nor dashboard or file processing areas show dates and times that actions have occurred. The activity log in particular is not that useful with out time/datestamps.

**Comment by JonoGillett** [comment]
@AmandaPDSC  This has been deployed into the test environment, please take a look.

**Comment by AmandaPDSC** [comment]
Thanks, I can see the timestamp in the Collection Activity of the Activity Log, but not Item Activity - can it be both?

**Comment by JonoGillett** [comment]
Ah my mistake, I forgot to add it there as well. I'll include the same behaviour in both when I push the production release later today.

**Comment by JonoGillett** [comment]
This has been deployed into production
