### ISSUE TITLE
Show all items button is not working (neither are the show 10 or show 50).

### ISSUE THREAD

**Issue by juliamiller** [nabu-catalog/nabu#625]
This feature was working on Wed. Today it is not (I was out of office Thursday, so I do not know if it was working then).

**Comment by nthieberger** [comment]
It is working for me (in Chrome). Can you try a different browser?

**Comment by juliamiller** [comment]
I usually use Chrome. I just tried it on Firefox. No joy there either.
I have tried on two computers, but both are PCs (one on the ANU network, one off- the ANU network). Perhaps there was an update that has caused this?

**Comment by juliamiller** [comment]
I just tried it on the mac with Chrome. Also not working.

**Comment by JonoGillett** [comment]
@juliamiller Is this for a particular search that you've run, or just any search?
Also, are you able to elaborate on what behaviour you see when you click them (e.g. is it the 'Something went wrong" page, or some other error)?

I was just able to use each of the "Show X" buttons, and although the "show all" took a while it returned the expected results

**Comment by nthieberger** [comment]
I am now finding that it is working erratically. At the item or collection level view none of the 'show' buttons works. But if I go from a particular collection back to the general opening screen then the 'show' buttons work. 
From here, neither "show all" nor "show 50" works
http://catalog.paradisec.org.au/collections/NT1

**Comment by juliamiller** [comment]
@JonoGillett This is just to expand the list of items seen on a given collection page. It is an action I do so often it is second nature and I have never had it choke up on me before. Then today it does not work from any collection page. I am not using loads of processing power in the background, so this should be an instantaneous action. 

The event listeners are not firing in Chrome (looking to the Inspect element interface).

**Comment by JonoGillett** [comment]
@juliamiller Apologies - looks like I'd changed the way those behaved on only some screens. I have now resolved this and deployed a new version. Please let me know if the problem persists.

**Comment by juliamiller** [comment]
@JonoGillett So I was looking item DV in the LRB3 collection today. This item has 72 content files. The buttons that show up after clicking View from the collections page [Show 10] [Show 50] [Show all 25]. It looks like the default presentation for this is 25 content files. So nothing changes when I click on [Show all 25]. When I click [Show 50], 50 files are displayed. Then the buttons are [Show 10] [Show 50] [Show all 50]. The only way I can see the remaining 22 files is to press "Last>>" above the buttons. Then the final 22 files are presented.

Also from the collection for LRB3, the "Show" buttons for showing the 18 items are: [Show 10] [Show 50] [Show 100] [Show all 18]. This is an odd set of choices. If I am remembering correctly, on should have a choice of the following;
If items are fewer than 10: no button needed
If items number between 11 and 25:  [Show 10] [Show all] (and maybe there was [Show 10] to allow user to toggle back to a abbreviated list)
If items number between 25 and 50:  [Show 10] [Show 25] [Show all] 
If items number between 51 and 100: [Show 10] [Show 25] [Show 50] [Show all]
If items number over 100:   [Show 10] [Show 25] [Show 50] [Show 100] [Show all]

![nabu-resizing-1](https://cloud.githubusercontent.com/assets/10249439/26540909/f6970d8c-4496-11e7-8614-9fda5982a4e9.JPG)
![nabu-showall01](https://cloud.githubusercontent.com/assets/10249439/26540911/f6bca056-4496-11e7-8172-ec6d7d321ebc.JPG)
![nabu-showall02](https://cloud.githubusercontent.com/assets/10249439/26540912/f6c7d05c-4496-11e7-8a4e-9f1481709132.JPG)
![nabu-showall03](https://cloud.githubusercontent.com/assets/10249439/26540913/f6cad108-4496-11e7-8cc9-2c278d05e5df.JPG)

**Comment by JonoGillett** [comment]
@juliamiller I've resolved the incorrect 'all' count issues now, please check that it's working as expected.

**Comment by juliamiller** [comment]
@JonoGillett When I go to my dashboard, the [Show 50] or [Show all 27] doesn't work.
However, these buttons are now fully functional at the collection level, the item level, and at the content file level.

**Comment by nthieberger** [comment]
Julia, is this now working?

**Comment by LindaBarwick** [comment]
@juliamiller can you please comment?

**Comment by juliamiller** [comment]
@JonoGillett @LindaBarwick @nthieberger The buttons are working fine now, thanks. I had another part to this, however. The resizing is not working well at the Item, but I also created an issue #627 specifically for that second bit, so I'll close this  @issue.
