### ISSUE TITLE
Bulk update to delete information in a field

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#626]
We need to be able to delete information in a field, for example, the DT1 collection has 'Vatican State' as a country but that needs to be deleted for each entry it is in (there are 445). Currently we can find those entries but have no way of deleting the country.

**Comment by nthieberger** [comment]
looks like there are only 83 but the issue remains that we would ideally be able to delete information globally. If this is a major problem to fix then we can talk about whether it needs to be implemented or not.

**Comment by j03w** [comment]
@nthieberger the feature has been implemented on the per entry not on the collection itself, just waiting for the review currently.

In either case, I think we should revisit relationships between collection and its items/entries. Currently the collection could have countries, languages and few other things associated to it that may not be on any of the entries in the collection.

**Comment by nthieberger** [comment]
Hi, I don't understand what the 'review' is? Will this feature be in the production version  after that?
 Thanks.

**Comment by j03w** [comment]
@nthieberger yup

**Comment by nthieberger** [comment]
I just bulk updated the DT1 countries with 'Vanuatu' and did not 'append'. This deleted the existing country (Vatican State) so is a good result.

**Comment by enwardy** [comment]
so @nthieberger do we still require the initial request made in this Issue? "Bulk update to delete information in a field"?

**Comment by nthieberger** [comment]
This is still open. Is there a way to specify deletion of items in a bulk edit? Append/do not append can do this in some circumstances, but is not the same as deletion (e.g. if you don't want to add new data but just want to get rid of what is there now)

**Comment by JonoGillett** [comment]
Estimate relates to cleaning up and releasing the staging version of the delete functionality

**Comment by JonoGillett** [comment]
@nthieberger just to confirm, with the tests you've done for replacing the value looking good, you simply want the ability to remove any values in a given field/fields for all items in the search results. Is that correct?

For example:
* some records in a result set have 2 countries, others have 1 - you want to remove all of these regardless
* you want to clear any value in the operator field
etc..

**Comment by agrimmtt** [comment]
@nthieberger Has there been any update on this since Jono's last comment?

**Comment by nthieberger** [comment]
I did a bulk up[date yesterday and nothing has happened. It did not update
the items required.

**Comment by agrimmtt** [comment]
@nthieberger Has this been resolved?

**Comment by nthieberger** [comment]
Yes, it is now working
