### ISSUE TITLE
Page resizing not working very well.

### ISSUE THREAD

**Issue by juliamiller** [nabu-catalog/nabu#627]
It seems to be ok at the collection level, but not at the item level or content file level. This includes when in edit mode.

**Comment by juliamiller** [comment]
@JonoGillett Also checking back with you on this issue-- The Nabu page resizing on collections pages is a bit off, but much improved. But the resizing on Items pages is not working well. Also the player on essence file pages is not resizing well either. This is the case for both Chrome and Firefox.

**Comment by juliamiller** [comment]
@JonoGillett Hi, just checking on the status of this issue. There is still a re-sizing glitch on the Items-level sites.
![collection-level](https://user-images.githubusercontent.com/10249439/32752982-4d9aa456-c91f-11e7-97fc-3d0c71eec863.JPG)
![item-level](https://user-images.githubusercontent.com/10249439/32752986-51eb5122-c91f-11e7-9749-be635f711105.JPG)

**Comment by juliamiller** [comment]
@JonoGillett Page resizing is still has a glitch on the item-level pages.
![collection-level](https://user-images.githubusercontent.com/10249439/32753090-b4dc1cd0-c91f-11e7-84d7-e3834e301cb0.JPG)
![item-level](https://user-images.githubusercontent.com/10249439/32753096-b6fdfae2-c91f-11e7-894a-9b5fa9f398f4.JPG)

**Comment by enwardy** [comment]
same (or similar enough) to issue #438  to merge them?

**Comment by juliamiller** [comment]
Yes, I believe so.

**Comment by AmandaPDSC** [comment]
this issue covered in #438
