### ISSUE TITLE
Error message when attempting to play MP3 or wav

### ISSUE THREAD

**Issue by juliamiller** [nabu-catalog/nabu#632]
So Don (DK1) just tried to access his files and got an error message. I attempted on the same item w same results. I then tried it on a file in AHA1 and got the same error.

**Comment by juliamiller** [comment]
I tried to send the screenshot, but I am now home, sick, on my back, using my mobile...

**Comment by juliamiller** [comment]
![img_5338](https://user-images.githubusercontent.com/10249439/27819735-eb12737a-60de-11e7-9c46-4ef3be31e8a2.PNG)

**Comment by nthieberger** [comment]
Get him to play the mp3, not the wav file

**Comment by juliamiller** [comment]
I got the error on both, I think... did you try?

Dr Julia Colleen Miller
Senior Data Manager
ARC Centre of Excellence for the Dynamics of Language
College of Asia and the Pacific | The Australian National University
Tel:  +61 2 6125 6115<tel:+61%202%206125%206115> | dynamicsoflanguage.edu.au​<http://www.dynamicsoflanguage.edu.au/>

On 4 Jul 2017, at 5:59 pm, nthieberger <notifications@github.com<mailto:notifications@github.com>> wrote:

Get him to play the mp3, not the wav file

**Comment by juliamiller** [comment]
Indeed. Same results with MP3. 
![img_5340](https://user-images.githubusercontent.com/10249439/27820797-54453162-60e3-11e7-8674-3fd4375ed257.PNG)

**Comment by nthieberger** [comment]
Yes, the mp3 plays ok for me in this item so I'm not sure what the issue is.

**Comment by LindaBarwick** [comment]
working ok for me too

**Comment by juliamiller** [comment]
Ok, I managed to try it on the mac lappy. All good. Could there be an issue with accessing media on a mobile device?

**Comment by juliamiller** [comment]
Ah, just tried on the macbook pro using Safari. Same error. Is this a known issue?

**Comment by juliamiller** [comment]
To summarise: I get the error when using safari and chrome on a mobile device (iPhone, iPad). Get error when using laptop with safari. Works fine with laptop and chrome.

**Comment by LindaBarwick** [comment]
Works on chrome and firefox for me on Mac laptop, not safari

**Comment by nthieberger** [comment]
no longer a problem
