### ISSUE TITLE
Search fail

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#633]
Having unsuccessfully updated all KK1 file metadata I then needed to search for items that did not have 'ready for metadata export' checked. When I did that search (KK1 + false in that field) it says there are zero hits, but that is not true. Something is wrong with the search function.

**Comment by nthieberger** [comment]
same result in
![screen shot 2017-07-05 at 2 28 15 pm](https://user-images.githubusercontent.com/611488/27849191-81d18a4e-618e-11e7-8ea6-5e7aa91bd31e.jpg)
 'builder mode'

**Comment by nthieberger** [comment]
Seems like 'builder mode' needs some work. Searching for "identifier contains KK1-13" gets zero hits, but doing it in a basic search gets 100 hits

**Comment by nthieberger** [comment]
I have managed to update items by searching for 100 at a time, so is there a timeout issue with too many items?

**Comment by nthieberger** [comment]
Another related problem: advanced search for KK1 collection and 2013 as a creation date throws an error, also in builder mode.

**Comment by enwardy** [comment]
not sure about the initial issue described in this ticket (if it is still an issue), but the 'builder mode' complaint above is still problematic (Searching for "identifier contains KK1-13" gets zero hits, but doing it in a basic search gets 100 hits)

**Comment by nthieberger** [comment]
seems the problem is that checkboxes are treated as being in a zero state unless checked, not as 'false' by default. Jono will look into fixing this

**Comment by JonoGillett** [comment]
There are two separate issues here:
- 'Identifier' in the builder is _only_ the item identifier (i.e. 13, not KK1-13) - the query builder should detect the '-' character and search on collection + item identifier
- As Nick mentioned above, there is a potential TRUE, FALSE, NULL issue - the query builder needs to be updated
