### ISSUE TITLE
turn on verbose logging for archive:import files

### ISSUE THREAD

**Issue by LindaBarwick** [nabu-catalog/nabu#638]
We need verbose logging for archive:import files cron jobs - so that we can check durations of mp3 and wav are matching.

please turn this on as soon as possible

**Comment by LindaBarwick** [comment]
Hi Jono and co, this job is becoming urgent, can you please advise?

**Comment by JonoGillett** [comment]
@LindaBarwick verbose audio information should now logged in the import script. Please run a test file through and you should see the diagnostic information.

**Comment by AmandaPDSC** [comment]
no verbose reports seem to be coming through now

**Comment by JonoGillett** [comment]
@AmandaPDSC apologies, I accidentally reverted this during the redeploy. it's back on now and I've fixed the release to not revert it
