### ISSUE TITLE
User merge does not update collections for merged users

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#641]
I merged the user Johhny Tjia (TJ1) and am now unable to access the TJ1 collection or to change eh collector to the new merged user.

**Comment by enwardy** [comment]
@nthieberger I think maybe you've gotten the collection name mixed up - Johnny Tjia's collection is JT1 , which seems a-ok and accessible. Leaving this Issue Open for now to await confirmation from you on that..

**Comment by nthieberger** [comment]
yes, that seems right
