### ISSUE TITLE
Don't show link to viewer unless user is logged in

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#646]
When a non-logged in user attempts to use the viewer by clicking the view file contents link, there is no error message telling them they need to log in first. Instead the viewer seems to be loading files but never resolves. Can we please implement an error alert that says "You need to be signed in to view/download files" if someone clicks on this link, but isn't logged in?

**Comment by nthieberger** [comment]
please hide the 'View file contents' for non-logged in users
