### ISSUE TITLE
Viewer issues

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#647]
This relates to the js viewer but I'll make note of it here to be dealt with at some point. 
This item has an elan (.eaf) transcript that is not being presented in the viewer, but should be.

http://catalog.paradisec.org.au/collections/AC1/items/013

**Comment by JonoGillett** [comment]
The estimate here is based on the fact that we would first have to learn how the viewer works/is built before we could make any changes.

If this is done by Marco it should be less.

**Comment by nthieberger** [comment]
I'll get Marco to work on this
