### ISSUE TITLE
csv export of all items stops at LD1-v0312

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#652]
An export of all items as csv stops before it reaches the end. I just downloaded a 13.7 Mb file that is incomplete. As we use this csv file to check on NABU contents it is important that it be complete.

**Comment by nthieberger** [comment]
Maybe the download could be a job done offline and then reported to the user with a download link?

**Comment by enwardy** [comment]
is your time estimate (<16h) related to Nick T's above suggested solution (doing it as an offline job)? Or is it referring to fixing the csv export as it currently functions?
@JonoGillett

**Comment by nthieberger** [comment]
Can you please work on this asap? I need the full list to be able to diagniose issues in the collection

**Comment by agrimmtt** [comment]
@nthieberger Are you happy with the functionality that has been deployed to production?
