### ISSUE TITLE
Data endpoint is too open

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#657]
Can you please make the data endpoint (e.g. http://catalog.paradisec.org.au/collections/LG1/items/09091401/data.json) available only to logged in users? At the moment it is open to the world and announces what files there are, even in closed items and private items. Can it not be available for private items please?

**Comment by AmandaPDSC** [comment]
#664

**Comment by marcolarosa** [comment]
@nthieberger @JonoGillett I think this whole endpoint can now be removed given the work in #662.
