### ISSUE TITLE
password seems to need to be longer than ~5 characters?

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#658]
Resetting a password for a user generates an error if the password is not long enough. I have had this happen with a 4 and 5 character password, but not when I have an 8 or 10 character password. It is fine to have a minimum number, butthat needs to be explicitly stated for the user

**Comment by nthieberger** [comment]
Please add information on the sign in page to let users know that a password must be 8 characters

**Comment by NickWardPDSC** [comment]
password length is flagged if a user tries to sign up with a too-short-password:

"Password is too short (minimum is 6 characters)"
