### ISSUE TITLE
Search Fail

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#661]
The buoilder mode hasn't worked in this instance. Searching for collection MH2 with NOT closed access condtions returned no items, but it should have had many.

![screen shot 2018-03-20 at 9 20 28 am](https://user-images.githubusercontent.com/611488/37625423-fcf6fd42-2c1f-11e8-8396-7396b218206a.jpg)

**Comment by NickWardPDSC** [comment]
builder mode search appears to be working fine.
