### ISSUE TITLE
Enable gzip for static resources in nginx configuration

### ISSUE THREAD

**Issue by marcolarosa** [nabu-catalog/nabu#663]
Hi,

As per title, please enable gzip'ing of static resources in the nginx configuration to speed up content serving.

Following is a browser console screenshot showing that the response is not zipped.

![screen shot 2018-04-11 at 9 46 06 am](https://user-images.githubusercontent.com/2639995/38589267-598337c0-3d6d-11e8-964f-102d3fb1a848.png)

An example is @ https://gist.github.com/rcanepa/0b9beaac137f7d45754b58822bfd0092

Or if the nginx version is new enough it looks like there's a module that can be compiled / loaded to figure it all out automatically (I've not used it so YMMV): https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html

Thanks!

**Comment by agrimmtt** [comment]
@marcolarosa It looks like it's an application-wide problem, not just related to the viewer.

**Comment by danburnusyd** [comment]
Looks like it can be done at the server level: http://nginx.org/en/docs/http/ngx_http_gzip_module.html

**Comment by johnf** [comment]
The new nginx config does this by default
