### ISSUE TITLE
Media files don't load in firefox

### ISSUE THREAD

**Issue by marcolarosa** [nabu-catalog/nabu#665]
Seems like media files don't load in firefox and I think the issue is that the Content-Type is being set incorrectly.

For example, open up dev tools in firefox and navigate to http://catalog.paradisec.org.au/viewer/#/AC1/013/media/AC1-013-B?transcription=AC1-013-B.eaf.

In the response headers you'll see "Content-Type | application/octet-stream" which I think is the issue.

This is odd because if you navigate to the mp3 directly viz: http://catalog.paradisec.org.au/repository/AC1/013/AC1-013-B.mp3 it loads and plays.

Can you please investigate?

Related to https://github.com/marcolarosa/pdsc-collection-viewer/issues/17

**Comment by marcolarosa** [comment]
https://github.com/marcolarosa/pdsc-collection-viewer/issues/17

**Comment by marcolarosa** [comment]
OK - this is a massive issue. Following is a screenshot from firefox showing the error in the console. 

If I put the movie file into the browser (http://catalog.paradisec.org.au/repository/NT1/98007/NT1-98007-98007B.mp3) it loads without issue but via the viewer the Content type is set incorrectly so it doesn't load.

![screen shot 2018-08-09 at 12 05 20 pm](https://user-images.githubusercontent.com/2639995/43874072-02a074ea-9bcd-11e8-9f5d-3f7d399954a5.png)

**Comment by nthieberger** [comment]
Well we can just tell users they have to use chrome (or IE?)

**Comment by marcolarosa** [comment]
Ummm sure - we can. But it also should just work...

**Comment by NickFG** [comment]
Just a heads up, the link above suggests your talking about an mp3. Which is not a video file, simply digital audio.

**Comment by agrimmtt** [comment]
I've made a change that uses the actual mime type, rather than "application/octet-stream". I can't test that this fixes the problem using my machine.

@nthieberger I don't think I'm able to do deployments, because I can't run `ssh deploy@catalog.paradisec.org.au `. Can you merge develop into master, and then deploy master, when you are ready to do a deployment?

**Comment by AmandaPDSC** [comment]
also SAW2-008-A.mp3 is not playing in Safari

**Comment by nthieberger** [comment]
@mpeard can you please check  that andrew grimm's commit above has been deployed. It seems to be the thing that would solve this issue. Thanks.

**Comment by NickWardPDSC** [comment]
I think this is resolved. (Might be a periodically recurring issue, as browsers require updates etc?)
