### ISSUE TITLE
catalog xml files is not complete

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#666]
Hi, can you please check why the catalog xml file for this item does not include the eaf files which are in the catalog? http://catalog.paradisec.org.au/collections/NT1/items/20003

I have tried editing and resaving the catalog entry but it does not seem to be being updated. So, is the catalog xml file being updated when a catalog entry is edited and saved?

**Comment by marcolarosa** [comment]
hi @JonoGillett we've also found issues with SN1-MM20130708Museum & NT5-TokelauOf. Specifically, some files visible in the UI are not listed in the XML.

Can I ask - is the background update triggered when an item is saved? Does it also trigger when content is uploaded to an item?

As far as I know, the items @nthieberger has sent me for testing have not been edited or updated recently so if the CAT xml update happens on save but not data upload that might explain the difference.

**Comment by nthieberger** [comment]
The Cat.xml files are not all correct and it is not due to a lag. NT5-tokelauOf and it doesn't have the eaf file in it. SN1 is missing both mxf files a webm and an mp4 file.

**Comment by JonoGillett** [comment]
@nthieberger  As @marcolarosa suggested - the only process I know of which updates the XML files is when an item is saved. This means that new essences inside an existing file do not currently cause the item XML file to be updated.

From a previous task we have a batch XML updater which I am running at the moment to bring all the items back in line with the essences they contain.

However it raises the question of should we have a ticket for updating the XML on new essence creation as well?

**Comment by nthieberger** [comment]
yes please, I'll add that
