### ISSUE TITLE
Update catalog xml file on any change to an item

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#667]
Following #666 , the cat xml file should be updated for any change to an item, whether in the catalog or by addition of an essence item.

**Comment by nthieberger** [comment]
I just updated a record and the cat.xml file has not been updated. Could there be a time lag, or a queue that these jobs go into that is not running?

**Comment by nthieberger** [comment]
OK, I checked again, I updated the catalog entry for AC2-SICOMPV105 but the xml file has not been updated. We really need this to work for the raspberry pi catalogs to be accurate representations of items.

/srv/catalog/AC2/SICOMPV105/AC2-SICOMPV105-CAT-PDSC_ADMIN.xml

**Comment by AmandaPDSC** [comment]
Process has been restarted and @mpeard will implement a process monitor to alert if the process stops

**Comment by mpeard** [comment]
Monitoring has been implemented.
