### ISSUE TITLE
OLAC feed needs to update on release from private status

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#672]
I made two collections not private but the OLAC feed has not included them (BB2 and CS1). This should happen once the 'private' checkbox is unchecked.

**Comment by agrimmtt** [comment]
@nthieberger I can view http://catalog.paradisec.org.au/oai/item?verb=GetRecord&identifier=oai:paradisec.org.au:BB2-204205&metadataPrefix=olac without any problems. Does this problem still exist, and if so, how can I reproduce it?

**Comment by nthieberger** [comment]
looks ok so no need to proceed with this
