### ISSUE TITLE
Google maps not loading for Australian viewers

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#677]
Region problem with Google maps?

**Comment by AmandaPDSC** [comment]
Seems to be resolved - presumably a Google problem

**Comment by enwardy** [comment]
looks like the map problem is back - not loading today. (Safari and Chrome, on Mac; and Firefox on PC)

**Comment by enwardy** [comment]
as I understand it, this should be fixed once the new API is added, that @nthieberger shared with Peter Danckwerts by email on 9 October. So we're just awaiting that to see if this issue will be resolved...
