### ISSUE TITLE
ADD to 'cite as' field

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#681]
The 'cite as' field should include http://dx.doi.org/ before the doi. Can this please be added globally and also to the script that adds a citation form for new items

**Comment by nthieberger** [comment]
The 'cite-as' field used to say the item was in the paradisec collection but doesn't now, e.g.:

Robert Early (collector); Morin Custom Stories, PDF/X-WAV/MPEG, 2019-09-21. DOI: 10.26278/5d0badada082a

Could it please be of the form:
Robert Early (collector); Morin Custom Stories. Item RE1-001 in paradisec.org.au, PDF/X-WAV/MPEG, 2019-09-21. DOI: 10.26278/5d0badada082a

That is, include the collection and item identifer and the url

**Comment by mpeard** [comment]
Cite-as field standardised across items and collections to the above.

**Comment by nthieberger** [comment]
Thanks, looks good!

Nick
