### ISSUE TITLE
Download failure in Safari

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#691]
Downloading in Safari strips the filename and replaces it with 'true.mp3'. Can that be fixed? If not, we can warn people not to use Safari, butthat would be a less preferred option.

**Comment by jodiekell** [comment]
Thanks Nick, please let me know how you go with this John

**Comment by johnf** [comment]
@jodiekell @nthieberger I've made a change which I think might fix this, can you please test in Safari

**Comment by jodiekell** [comment]
Thanks @johnf that is fixed, I just downloaded a jpg and mp3 and both had the correct file name @nthieberger

**Comment by nthieberger** [comment]
Thanks Jodie, I've taken the admin message off the catalog page
