### ISSUE TITLE
advanced search, no entry allowed in the essence details box items

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#695]
Entry not allowed in the following

Choose a mimetype...
Filename	
Mime Type	
FPS	
Sample Rate	
Channels

**Comment by nthieberger** [comment]
Actually, mimetype dropdown is empty, and should have all current mimetypes in it.

**Comment by johnf** [comment]
Mimetypes dropdown is fixed.

**Comment by johnf** [comment]
Nick this may solve the speed problem, the mimetypes issue was making the backend load every single essence entry from the DB into RAM!!

Was there anything else broken here. I can set channels etc
