### ISSUE TITLE
Install the image viewer from the old server

### ISSUE THREAD

**Issue by marcolarosa** [nabu-catalog/nabu#697]
hi @johnf 

In my homedir on the old server you'll see some content that needs to be installed on the new server:

```
mlarosa@catalog:~$ ls -l
total 36
lrwxrwxrwx 1 mlarosa mlarosa   19 Feb 14  2019 current -> production.20190214
drwxr-xr-x 5 mlarosa deploy  4096 Jul 20  2015 master
drwxrwxr-x 6 mlarosa mlarosa 4096 Aug  8  2016 production.20160823
drwxr-xr-x 4 mlarosa mlarosa 4096 Apr 23  2018 production.20180423
drwxr-xr-x 4 mlarosa mlarosa 4096 May  9  2018 production.20180509
drwxr-xr-x 5 mlarosa mlarosa 4096 Jun  5  2018 production.20180605
drwxr-xr-x 4 mlarosa mlarosa 4096 Sep  3  2019 production.20190214
drwxr-xr-x 4 mlarosa mlarosa 4096 Feb 14  2019 production.20190902
drwxr-xr-x 4 mlarosa mlarosa 4096 Feb 14  2019 production.20190903
drwxr-xr-x 5 mlarosa mlarosa 4096 Jun  5  2018 testing
```

This is the image viewer that gets loaded when you click `view file contents` on an item:
![Screenshot 2023-03-06 at 2 53 09 pm](https://user-images.githubusercontent.com/2639995/223015874-002aef81-5515-431a-978b-b187fb6effcb.png)

The current setup has the /viewer pointing to my home dir but you can install it anywhere you want on the new server as it will not be getting any updates (the current setup was decided by Syd IT so I could update the viewer as required).

So, you need to map `https://syd-paradisec-prod.intersect.org.au/viewer/#` to the folder where you install that content. You should be able to get the webserver config off the old server.

**Comment by johnf** [comment]
@marcolarosa Thanks I've found this. I can add it to the public directory in the main app so it get's auto deployed
Do you have the original source for this available? There are some small changes I'd like to make in how it connects to graphql so it can work in the staging environment

**Comment by marcolarosa** [comment]
I think it's this one: https://github.com/CoEDL/nabu-collection-viewer-v1 but it's been so long since I've looked at it or updated it!

It doesn't use graphql at all if I recall. From memory, it reads the OAI-PMH feed and constructs the item representation from that.

**Comment by johnf** [comment]
Thanks Marco. It's now deployed
