### ISSUE TITLE
The "Next Item" button is going to the previous item, not the next item

### ISSUE THREAD

**Issue by juliamiller** [nabu-catalog/nabu#705]
fyi the "Previous Item" is working fine.

**Comment by johnf** [comment]
@juliamiller Do you have an example of how you discovered this?

@nthieberger  This is something that might need a bit more thinking. I wonder if these buttons might be a bit confusing.
FOr example I went to a collection, clicked on the first item and assumed that the next previous would move through the items in that collection.

That's not how it works, though, it's based on the search you perform. It's moving through the items that were discovered in the item search.

It's very inefficient, too as it stores the search results in the user session just so it can iterate through them, which can cause the cookies to get too big.

**Comment by AmandaPDSC** [comment]
@johnf the next button going to the next found item in a search isn't working either. I searched on "Tagalog", viewed 
LB1-VT9308. The next button takes me in sequence to: AC1-000; MBG1-006; then the Next buttons disappear and I instead have the options "Previous Item", "Edit Item" and "Duplicate Item"

**Comment by nthieberger** [comment]
The 'Show all 36' in this one also not working: https://catalog.paradisec.org.au/collections/NT1?items_page=3, also show 50 (discussed elsewhere)

**Comment by johnf** [comment]
I've fixed the 'Show all' buttons in collections for the items and in items for the files

**Comment by johnf** [comment]
@nthieberger Let's have a discussion about how the next and previous buttons top right should work.

Right now they are based on the search you did, not on for example to click next through the items in a collection.

Not sure what the team needs/wants here

**Comment by AmandaPDSC** [comment]
Is it possible to have Next go to next item in a found search set. But if no search has been performed to go to the next item in the collection?



On 25 Mar 2023, at 9:53 am, John Ferlito ***@***.***> wrote:

﻿

@nthieberger<https://github.com/nthieberger> Let's have a discussion about how the next and previous buttons top right should work.

Right now they are based on the search you did, not on for example to click next through the items in a collection.

Not sure what the team needs/wants here

**Comment by juliamiller** [comment]
Hi @johnf Sorry for the delayed clarification on my original issue. I often have to move through items in a collection one at a time to confirm files have made it into the catalog. I usually click on the first item. When I am ready to look at the next item, I click on the next button. If I need to go back and look at an item a few items earlier in the list, I use the previous item button. I mostly use these buttons to navigate from the collection page, rarely from a search.

**Comment by johnf** [comment]
OK I think I have a good solution
* If no search then next and prev go through the buttons in order
* If you have searched it goes through the search results till you clear the search
* The search is autocleared when you close the window or tab in your browser

**Comment by nthieberger** [comment]
Sounds good, thanks.

**Comment by AmandaPDSC** [comment]
This sounds good to me too. But opening a new Nabu tab this morning, my previous search has been remembered, and when I go to the items tab, I'm only shown one item (AC1-420), with no 'Return to Restults' button at top left to go back to my search results. Without this button, there doesn't seem to be a way to go back to a list of all items and perform a new search.

**Comment by johnf** [comment]
@AmandaPDSC Can you try going to items so you can clear your search.

Does this behaviour still occur? It might have still been caching the search the old way.

Return to Results now only shows if there is a saved search

**Comment by AmandaPDSC** [comment]
I think Return to Results always needs to be there. When a search only finds one item, then clicking on the Items tab just returns to that one item (not a list showing 1 item, but the item detail itself), so there is no way to go back to Items in order to clear the search, without that button. I was only able to clear it by going to Collections and performing a new search there

**Comment by nthieberger** [comment]
Yes, and clicking on 'items' should go back to the items screen with a search box

**Comment by NickWardPDSC** [comment]
think this is resolved
