### ISSUE TITLE
add "New User" not working 

### ISSUE THREAD

**Issue by NickWardPDSC** [nabu-catalog/nabu#707]
the "New User" button at top-right of this page https://catalog.paradisec.org.au/admin/users/ throws an error.

**Comment by nthieberger** [comment]
I tried duplicating an item and it also failed. But I did add a new item from the collection level and it worked (https://catalog.paradisec.org.au/collections/AS1/items/dictionary)

**Comment by johnf** [comment]
New user issues resolved

**Comment by johnf** [comment]
Item duplication should be worjing again
