### ISSUE TITLE
No maps anywhere in catalog

### ISSUE THREAD

**Issue by NickWardPDSC** [nabu-catalog/nabu#708]
no maps!

**Comment by johnf** [comment]
Ahh you must be the one creating the weird error I keep seeing.

what browser an OS are you using?

Do you have any sort of ad blocking or similar turned on?

**Comment by NickWardPDSC** [comment]
hi John, I'm on Chrome, Amanda on Firefox (and Julia also on Chrome) are all getting the same issue. Also Amanda just tested on her iphone in Safari, also no maps there. So it looks like a wider issue

**Comment by nthieberger** [comment]
I only see the map on the opening screen, but not in items or collections,
on Chrome on Mac

**Comment by nthieberger** [comment]
OK, now the maps are gone from all screens for me

**Comment by johnf** [comment]
I can't duplicate this, but I can see some errors in sentry that are probably related.
Could you please add a screenshot here of the front page where there isn't a map
I you could also open the javascript console (F12 in Chrome I think) and send me a screenshot of the console error.
Also the network tab is there anything red in there

**Comment by nthieberger** [comment]
<img width="541" alt="Screenshot 2023-03-18 at 2 50 47 pm" src="https://user-images.githubusercontent.com/611488/226147841-d1252f23-1523-4602-bee0-cb0d31da66ff.png">
<img width="714" alt="Screenshot 2023-03-18 at 2 42 47 pm" src="https://user-images.githubusercontent.com/611488/226147844-6e92a1ad-e50d-48ef-b1b9-f54f5e5b279f.png">
<img width="552" alt="Screenshot 2023-03-18 at 2 51 45 pm" src="https://user-images.githubusercontent.com/611488/226147868-240dc905-2b58-46f1-a605-83bf70650110.png">
<img width="557" alt="Screenshot 2023-03-18 at 2 52 32 pm" src="https://user-images.githubusercontent.com/611488/226147886-1749b9d5-bff3-41fc-8157-0bd1e9ceac98.png">

**Comment by johnf** [comment]
I've made a change to how the maps scripts are loaded which I'm hoping will fix this. Could yo please give it another test

**Comment by nthieberger** [comment]
OK, the first time I loaded it, the font page hada map, but then when I
went to items and collections, neither of which had a map, then back to the
home page, it also did not have a map

**Comment by NickWardPDSC** [comment]
nope I'm still seeing no maps. (strange thing was when I first loaded the home page there was a map... but then on any subsequent page loads, no map)

**Comment by johnf** [comment]
That last bit of info helped, I was able to replicate it!
I think I've solved it now

**Comment by NickWardPDSC** [comment]
yes - looks solved! cheers :)

**Comment by AmandaPDSC** [comment]
maps showing as expected now
