### ISSUE TITLE
NABU is slow

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#711]
All ws going quite quickly for a while but today it seems it is working slowly?

**Comment by nthieberger** [comment]
<img width="1067" alt="Screenshot 2023-03-19 at 8 11 53 am" src="https://user-images.githubusercontent.com/611488/226198105-afcc1b60-9a3e-4cae-9ada-ea7d646beb7b.png">

**Comment by johnf** [comment]
Hmm that means something strange is happening in the javascript in the browser rather than the server. Hopefully sentry has something in the logs
