### ISSUE TITLE
left hand pane does not shrink

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#712]
when the window is not full width.   <img width="1448" alt="Screenshot 2023-03-19 at 8 08 57 am" src="https://user-images.githubusercontent.com/611488/226197988-0b51f76a-5384-4f44-950f-a234e41d97a5.png">

**Comment by johnf** [comment]
@nthieberger Is this new? I think it's the same behaviour as before. In my testing both shrink but only down to a certain amount

**Comment by nthieberger** [comment]
ok, but this is on a laptop so is it possible to make each pane shrink a little more to avoid overlap?
