### ISSUE TITLE
OLAC validation fails

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#714]
http://www.language-archives.org/register/register.php

Validation Log
Archive: https://catalog.paradisec.org.au/oai/item

Retrieving Data
Fetching data for protocol request: verb=Identify OK

Fetching data for protocol request: verb=ListMetadataFormats OK

Fetching data for protocol request: verb=ListIdentifiers&metadataPrefix=olac OK

Fetching data for protocol request: verb=ListRecords&metadataPrefix=olac OK

Fetching data for protocol request: verb=GetRecord&metadataPrefix=olac&identifier=oai:paradisec.org.au:AA1-001 OK

Validating XML Responses
Testing protocol request: verb=Identify
- Xerces-J OK

Testing protocol request: verb=ListMetadataFormats
- Xerces-J OK

Testing protocol request: verb=ListIdentifiers&metadataPrefix=olac
- Xerces-J OK

Testing protocol request: verb=ListRecords&metadataPrefix=olac
ERROR: Test failed

Here are some URLs which may help in diagnosing the problem:

https://catalog.paradisec.org.au/oai/item?verb=ListRecords&metadataPrefix=olac
[Local copy](http://www.language-archives.org/register/tmp/https:@@catalog.paradisec.org.au@oai@item_LR.xml) of that response that we've tested
[Xerces-J error log](http://www.language-archives.org/register/tmp/https:@@catalog.paradisec.org.au@oai@item_LR.xml-xercesj.txt)
[XML Schema validator](http://www.language-archives.org/tools/xsv)
[Repository Explorer for this archive](http://rocky.dlib.vt.edu/~oai/cgi-bin/Explorer/oai2.0/testoai?archive=https://catalog.paradisec.org.au/oai/item)
Testing protocol request: verb=GetRecord&metadataPrefix=olac&identifier=oai:paradisec.org.au:AA1-001
ERROR: Test failed

Here are some URLs which may help in diagnosing the problem:

https://catalog.paradisec.org.au/oai/item?verb=GetRecord&metadataPrefix=olac&identifier=oai:paradisec.org.au:AA1-001
[Local copy](http://www.language-archives.org/register/tmp/https:@@catalog.paradisec.org.au@oai@item_GR.xml) of that response that we've tested
[Xerces-J error log](http://www.language-archives.org/register/tmp/https:@@catalog.paradisec.org.au@oai@item_GR.xml-xercesj.txt)
[XML Schema validator](http://www.language-archives.org/tools/xsv)
[Repository Explorer for this archive](http://rocky.dlib.vt.edu/~oai/cgi-bin/Explorer/oai2.0/testoai?archive=https://catalog.paradisec.org.au/oai/item)
Checking OLAC version in Identify response...... OLAC 1.1 dynamic

Checking OLAC version in ListRecords response...... OLAC 1.1 dynamic

OLAC-PMH Validation
Testing protocol request: verb=Identify
Identify: description element has an olac-archive element - OK
Identify: adminEmail thien@unimelb.edu.au appears in a participant element with role Project Director - OK
The Base URL in the repository file and the one supplied in the form match - OK

Testing protocol request: verb=ListMetadataFormats
ListMetadataFormats: olac present - OK
ListMetadataFormats: correct number of metadataPrefix elements - OK
ListMetadataFormats: correct number of metadataPrefix elements - OK
ListMetadataFormats: correct number of metadataPrefix elements - OK
Testing protocol request: verb=ListRecords&metadataPrefix=olac
ListRecords: at least one record was found - OK
Validation Result:
FAILURE

**Comment by johnf** [comment]
I've emailed the addresses at the bottom of my page. I think it might be an issue on there end. I've tested using the code their website uses and it works fine.

**Comment by nthieberger** [comment]
OK, but our OLAC report shows zero records: http://www.language-archives.org/metrics/paradisec.org.au. It may take a day or two to refresh, but right now it is not clear it is harvesting our feed.

**Comment by johnf** [comment]
Now fixed. I discovered language-org's own feed and copied their XML schmea references

**Comment by johnf** [comment]
@nthieberger did you get the email to re-register the archive?

**Comment by nthieberger** [comment]
Looks like we are being picked up again: http://www.language-archives.org/metrics/paradisec.org.au , with some strange quirks, probably a problem at OLAC, e.g., this page http://www.language-archives.org/language/sky should contain this item, bit doesn't: https://catalog.paradisec.org.au/collections/External/items/SikaianaCollection

**Comment by johnf** [comment]
Maybe it was still processing, it has it now
