### ISSUE TITLE
Cannot delete an item

### ISSUE THREAD

**Issue by juliamiller** [nabu-catalog/nabu#716]
Hi John,
I am trying to delete the item: https://catalog.paradisec.org.au/collections/YPG1/items/20190521_02
It has no associated files, it is also marked as private, yet I cannot delete it. 

When I click on the delete button, the page just refreshes and moves back to the top of page.

**Comment by johnf** [comment]
fixed

**Comment by juliamiller** [comment]
Thank you!

**Comment by juliamiller** [comment]
Issue has been fixed.
