### ISSUE TITLE
Cannot connect to Nabu catalog via SFTP

### ISSUE THREAD

**Issue by juliamiller** [nabu-catalog/nabu#717]
Not sure if there is a new address for the catalog, something with the certificate, or what else might be preventing me from connecting using a key and filezilla. Here is the error msg I received: 
<img width="575" alt="Screen Shot 2023-03-21 at 10 40 13 am" src="https://user-images.githubusercontent.com/10249439/226489984-c2da1283-7120-419e-9153-39a76b3f8704.png">

I had been able to connect prior to this, but I am also setting up a new workstation:

<img width="517" alt="Screen Shot 2023-03-21 at 10 55 15 am" src="https://user-images.githubusercontent.com/10249439/226490195-70833b74-528f-475c-8e4a-661f73e12eb5.png">

**Comment by johnf** [comment]
@juliamiller I'll have this sorted out tomorrow, I need to set up the new server for access

**Comment by johnf** [comment]
@juliamiller 
Can you try now but change your user to ```catalog```

On the old server you had two keys, respectively ending in
*  julia.miller@anu.<snip>
* rsa-key-20150324

Do you still need both?

**Comment by juliamiller** [comment]
@johnf I changed user to catalog and had the same results:
<img width="521" alt="Screen Shot 2023-03-22 at 8 54 10 am" src="https://user-images.githubusercontent.com/10249439/226750369-4a69b297-b538-4b3a-bced-c77c24322e7d.png">


<img width="543" alt="Screen Shot 2023-03-22 at 8 55 40 am" src="https://user-images.githubusercontent.com/10249439/226750480-eb6f51e9-a1fd-4511-94a1-44c37b2f611e.png">

I am not sure which key I use. For this Filezilla connection to the catalog I use the ssh-rsa key. But I also connect to the catalog using Terminal to r-sync for bulk downloads, and for this I use a password. Perhaps the julia.miller@anu one is for this connetion? 

I use a different ID and PWRD (SYD UniKey) connect to our server (Azoulay) so I don't think those would be for this connection. 

I guess just keep both if it is not a problem.

**Comment by juliamiller** [comment]
And I have just tried to connect to Nabu using the same protocol as I do for connecting to our Azoulay server (via Unikey & pwd ) and had the same negative result:

<img width="521" alt="Screen Shot 2023-03-22 at 9 06 26 am" src="https://user-images.githubusercontent.com/10249439/226752704-0b1dfa0f-6e12-47d2-b13b-f68a4f16b9b3.png">

<img width="532" alt="Screen Shot 2023-03-22 at 9 06 44 am" src="https://user-images.githubusercontent.com/10249439/226752730-eab7c572-ff1d-461a-8b25-58b5b791b1d3.png">

**Comment by johnf** [comment]
@juliamiller It's rejecting your SSH key as it is quite old. It is using SHA-1 instead of SHA-2, which is now considered insecure.

Are you able to generate a new key? Either a new RSA or an ED25519?

**Comment by juliamiller** [comment]
@johnf Or is it appropriate to attach it here?

**Comment by johnf** [comment]
@juliamiller Doesn't really mnatter but probably better to email. If you click on @johnf it should take you to my profile and you'll find my email address

**Comment by juliamiller** [comment]
@johnf Done, thanks!

**Comment by juliamiller** [comment]
Success with new key and catalog as user! Thanks John!
