### ISSUE TITLE
Edit Collection displays all page sections in single column

### ISSUE THREAD

**Issue by NickWardPDSC** [nabu-catalog/nabu#720]
(*Not critical, I don't think this is impacting functionality) . Normally when editing an item or a collection, the editing page looks more or less similar to the display version. However today when editing a collection, all of the different areas of the page (the 'boxes', such as Collection Details, Access Information, Items in Collection, etc) are displaying in a single column, rather than in the usual two columns.

**Comment by johnf** [comment]
fixed
