### ISSUE TITLE
Glitches in viewing some items

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#721]
AC1-420 is a result in a Basic Search at Item level, when I try and 'View' Item I get a 'something went wrong' page

**Comment by johnf** [comment]
FIxed

**Comment by johnf** [comment]
@AmandaPDSC Have you tested this, can I close it?

**Comment by AmandaPDSC** [comment]
Yes, can now view this item after finding it in a basic search, thanks
