### ISSUE TITLE
maybe we've seen this before? Finding an item, then unable to go to 'items' tab

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#728]
Search for item AC1-002, then click on 'Items', nothing happens, but it should go back to the items screen. Only way out is to go to 'Collections' and clear the seach, then the items screen can be seen again

**Comment by AmandaPDSC** [comment]
same as what's described in #705

**Comment by johnf** [comment]
SHould be fixed as part of the search fixes

**Comment by nthieberger** [comment]
yep
