### ISSUE TITLE
graphiql page not working

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#729]
At the bottom of the API page there is a link to https://catalog.paradisec.org.au/paradisec.graphql as a guide to using graphiql, but it doesn't work. I fthat page exists, please link to it, if not, maybe delete the link?

**Comment by johnf** [comment]
Fixed

**Comment by johnf** [comment]
@nthieberger Is this one OK now?

**Comment by nthieberger** [comment]
looks good thanks
