### ISSUE TITLE
Collection level Advanced Search issues

### ISSUE THREAD

**Issue by NickWardPDSC** [nabu-catalog/nabu#730]
I'm trying to do an advanced search at collection level, seem to be a few bugs:

depending on which field I search, either gives a "this page isn't working" (Chrome), or just reloads the blank search form (and returns no search results).

(Advanced search in Item level seems to be working ok)

**Comment by johnf** [comment]
SHould be fixed

**Comment by NickWardPDSC** [comment]
I'm still just getting "We're sorry but something went wrong" error for any advanced Collection search. I'll check if others are having the same issue

**Comment by nthieberger** [comment]
Yes, same for me

**Comment by johnf** [comment]
I've reworked how all the search works off the back of our workshop discussion, hopefully, it now meets all the requirements and is a bit more self-intuitive.

**Comment by johnf** [comment]
@nthieberger @NickWardPDSC @AmandaPDSC 
Can you play with search and let me know your thoughts

**Comment by NickWardPDSC** [comment]
@johnf  it looks good to me, all seems functional. thank you!

**Comment by AmandaPDSC** [comment]
Looks like it's all working as expected for me too
