### ISSUE TITLE
Files slow to view/play in Nabu

### ISSUE THREAD

**Issue by NickWardPDSC** [nabu-catalog/nabu#731]
I realise this may just be a limitation of our current storage system that will improve when we switch to S3, but I'll put it here anyway, as it's definitely worse now than it was before the recent changeover to the new-Nabu. 

Basically playing an mp3 - either in File Viewer, or the 'Preview' player within Nabu - often there will be a delay of (up to) a couple of minutes before it loads and plays.

**Comment by johnf** [comment]
@NickWardPDSC If you then say pull up another browser or maybe even on another computer or your phone. Does it play straight away or does it have the same delay.

There are two possible issues here. First is it's being pulled from tape. If so it should be fine the second time. Also I'm think there is some weird network problem causing NFS to be slow.

Anyway hopefully we are on new storage very soon!

**Comment by NickWardPDSC** [comment]
yes it's slow only the first time. If I then go back to the page to play it again it plays straight away. (should have mentioned that)

**Comment by NickWardPDSC** [comment]
..so if there's nothing to be done about this issue for now then feel free to close it, or I can, thanks @johnf
