### ISSUE TITLE
files stuck in NABU/toNabu

### ISSUE THREAD

**Issue by NickWardPDSC** [nabu-catalog/nabu#732]
the 11 "KK3-" files currently in the toNabu folder have been in there since I think around last Wednesday or Thursday (i.e. 5-6 days ago).

Not sure if any other files have successfully moved through to the archive in that time, but I don't think so.

thanks @johnf

**Comment by johnf** [comment]
azoulay NFS mount was hung again, rebooting now

**Comment by johnf** [comment]
Also manually kicked off an import job
