### ISSUE TITLE
"Delete collection and contents" button not working

### ISSUE THREAD

**Issue by NickWardPDSC** [nabu-catalog/nabu#733]
this button (in the 'Edit Collection' page) is throwing a "We're sorry but something went wrong" error.

**Comment by johnf** [comment]
Fixed

**Comment by NickWardPDSC** [comment]
hm, no still same error for me. (also, oops, it's not in the 'edit collection' screen, just in the normal Collection view screen)

**Comment by johnf** [comment]
forgot to deploy the code! try now

**Comment by NickWardPDSC** [comment]
thanks!
