### ISSUE TITLE
Cannot associate a country to a newly added language

### ISSUE THREAD

**Issue by juliamiller** [nabu-catalog/nabu#736]
I have just added a new language [pgz] Papua New Guinean Sign Language (PNGSL) to our list of language codes. Languages need to be associated with a country, otherwise it is non-functional (we cannot access as a subject or contact language in the dropdown list in the collection/item).

It seems like the function of associating a country to language is broken. When I am in the admin area editing the language, if I click on the button "Add New Countries Language" nothing happens except the URL changes from "https://catalog.paradisec.org.au/admin/languages/7615/edit" to "https://catalog.paradisec.org.au/admin/languages/7615/edit#".

I have tried to edit this on Chrome and Safari. I have tried by eliminating the boundary coordinates for the map (copied from Tok Pisin, a language with similar location), and I have tried without the "(PNGSL)" in case the non-alpha characters were somehow interfering.

**Comment by juliamiller** [comment]
Hi @johnf I'm wondering if you've had a chance to look at this. Still need to associate the pgz language code to Papua New Guinea, but I am unable to.
Thanks!
Julia

**Comment by nthieberger** [comment]
Where are languages assigned to countries? I can't see that in the language
list. Is it in a hidden table?

**Comment by juliamiller** [comment]
<img width="809" alt="Screen Shot 2024-02-27 at 2 37 39 pm" src="https://github.com/nabu-catalog/nabu/assets/10249439/e3e9dba3-a6b0-4ec2-badf-18cbfff09ca6">

**Comment by juliamiller** [comment]
I added pgz, but I cannot associate PNG to it.

**Comment by juliamiller** [comment]
<img width="730" alt="Screen Shot 2024-02-27 at 2 37 54 pm" src="https://github.com/nabu-catalog/nabu/assets/10249439/a88745eb-66b1-4b52-9296-812d3e2a7805">

**Comment by juliamiller** [comment]
It says the language has ben updated, but still no country listed under blue banner

**Comment by juliamiller** [comment]
<img width="803" alt="Screen Shot 2024-02-27 at 2 37 07 pm" src="https://github.com/nabu-catalog/nabu/assets/10249439/b76f5850-a617-46a5-9833-e9e02d2b7cd6">

**Comment by juliamiller** [comment]
When I was creating the language, I couldn't associate the country. I tried to "force it by using the same bounding limits as tok pisin
<img width="421" alt="Screen Shot 2024-02-27 at 2 41 29 pm" src="https://github.com/nabu-catalog/nabu/assets/10249439/b00eb263-dc24-4ba6-a589-9e020f5da3c7">

**Comment by juliamiller** [comment]
I'm fairly certain I deleted it and tried again a few times, but perhaps I'm missing something in the process?

**Comment by johnf** [comment]
Fix for this is rolling out now, should be live in 15

**Comment by juliamiller** [comment]
Hmm. Still getting same results. I'll try again tomorrow. (I did sign out of my browser, just in case).

**Comment by nthieberger** [comment]
I did add PNG to pgz, thanks John!

**Comment by juliamiller** [comment]
Yes! Thanks, I've added it to LWR2.
