### ISSUE TITLE
NABU metrics not updating?

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#737]
Metrics do not include a recent collection (PC1), e.g. here's the list that does not include it. Does this need to be reindexed?

P130_19 | 88 | 94 | 28.3 GB | 32:39:53.498
-- | -- | -- | -- | --
PCL1 | 3 | 12 | 3.25 GB | 10:04:04.997
PK1 | 48 | 250 | 21.1 GB | 52:27:07.829

**Comment by nthieberger** [comment]
Actually, scratch that, but change this issue to: please alphabetise the collections listed in the metrics

**Comment by johnf** [comment]
I just happened to notice it wasn't alphabetised when I was speeding it up, so fixed by coincidence!
