### ISSUE TITLE
User sign in problem

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#738]
We got this from a user:

I'm having difficulty logging into PARADISEC. It keeps going around and around asking me to confirm my email, which I do, and then it asks again.

**Comment by johnf** [comment]
@nthieberger I used the resend confirmation instructions on the sign in page and checked the mail logs.
The email is definitely being accepted by aol

Jun 24 10:08:30 syd-paradisec-prod postfix/pickup[116264]: 3851CA00D6: uid=1001 from=<admin@paradisec.org.au>
Jun 24 10:08:30 syd-paradisec-prod postfix/cleanup[117735]: 3851CA00D6: message-id=<649633fe2efab_3cb1863c92443@syd-paradisec-prod.mail>
Jun 24 10:08:30 syd-paradisec-prod postfix/qmgr[1721]: 3851CA00D6: from=<admin@paradisec.org.au>, size=3698, nrcpt=1 (queue active)
Jun 24 10:08:33 syd-paradisec-prod postfix/smtp[117737]: 3851CA00D6: to=<*******@aol.com>, relay=mx-aol.mail.gm0.yahoodns.net[98.136.96.93]:25, delay=3.7, delays=0.03/0.02/2.7/1, dsn=2.0.0, status=sent (250 ok dirdel)
Jun 24 10:08:33 syd-paradisec-prod postfix/qmgr[1721]: 3851CA00D6: removed
