### ISSUE TITLE
catalog report causes crash

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#740]
I can't access the catalog report in the admin section

**Comment by johnf** [comment]
@nthieberger Did you get an error?
I can load it OK now, it does take a very long time though about 10 seconds.
Some sections of that report are huge though, might be something for us to revisit
e.g. maybe the changed items is something you click on to expand, would likely make it run much faster.

**Comment by nthieberger** [comment]
It just gave 'I'm sorry' error message

**Comment by johnf** [comment]
@nthieberger Can you try this now. I actually improved it so it;s faster

**Comment by nthieberger** [comment]
Yes, it works fine, thanks
