### ISSUE TITLE
cannot edit users

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#745]
Trying to edit a user i nthe admin dashboard throws an error

**Comment by NickWardPDSC** [comment]
also trying to edit a user and the error appears to be with the (new?) unikey field:
<img width="556" alt="Screenshot 2023-11-29 at 12 11 35 pm" src="https://github.com/nabu-catalog/nabu/assets/58243294/382856fe-888d-4c9b-a810-dd1bcabc2618">

**Comment by NickWardPDSC** [comment]
fixed, thanks John
