### ISSUE TITLE
csv not functioning

### ISSUE THREAD

**Issue by jodiekell** [nabu-catalog/nabu#747]
I tried to export a CSV from an item search and it didn't work. I received the following message.

This page isn’t working.
catalog.paradisec.org.au is currently unable to handle this request.
HTTP ERROR 500

**Comment by johnf** [comment]
Can you try this now, I suspect my recent download fix fixed this too

**Comment by jodiekell** [comment]
Still not working unfortunately

**Comment by AmandaPDSC** [comment]
working again - thanks John
