### ISSUE TITLE
Page not working - catalog.paradisec.org.au/admin/country_boundaries

### ISSUE THREAD

**Issue by NickWardPDSC** [nabu-catalog/nabu#756]
https://catalog.paradisec.org.au/admin/country_boundaries

Bad gateway
The web server reported a bad gateway error.

Ray ID: 85c4a67ad9e7a87d
Your IP address: 27.32.17.126
Error reference number: 502
Cloudflare Location: Sydney
27.32.17.126

85c4a67ad9e7a87d

**Comment by johnf** [comment]
@NickWardPDSC This should be fixed

**Comment by NickWardPDSC** [comment]
fixed thanks
